### ISSUE TITLE
IllegalArgumentException when creating a new hierarchy

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#10]
## Description
Looking at the stacktrace, "it" does not try to find the column in the store I have defined but in the store "above" (in the references).

## Reproduce
Run all the notebook.
Notebook: [Notebook.zip](https://github.com/atoti/atoti/files/4414599/Notebook.zip)
Data: [data.zip](https://github.com/atoti/atoti/files/4414597/data.zip)

## Context
- Atoti version: atoti-plus-0.3.0.20200331222743

## Logs
[logs.txt](https://github.com/atoti/atoti/files/4414594/logs.txt)

## Related issues
**java.lang.IllegalArgumentException: MtM is not part of the cube's datastore selection** when trying to create a measure from the same store as above: 
[related_logs.txt](https://github.com/atoti/atoti/files/4414982/related_logs.txt)

**RuntimeException: The level 'Instrument Currency' should share its dictionary with the field 'Base Currency'** whatever the MDX query sent to the server.

**Comment by fabiencelier** [comment]
Hello @Harold7665 
I have fix this issue, you should now be able to create hierarchies after any join
The fix will be available in the next release
