### ISSUE TITLE
more specific doc focusing on "Query Data"

### ISSUE THREAD

**Issue by flebr1** [atoti/atoti#100]
## Description

Currently (as-of v 0.4.1) the documentation about querying data (w/t Python API... not considering "pure UI" options here) is disseminated in the "Basics" tutorial, mostly, and doesn't include full coverage of the query API.

Notably, we are not talking about pure "query session" anymore (I think it was mentioned more explicitly in the old tutorials). I was able to locate https://docs.atoti.io/0.4.1/lib/atoti.html?highlight=query#atoti.open_query_session after a bit of search through the API ref, but tbh, only because I pretty much knew already what I was looking for.

Not sure if we should add a more specific "Query Data" section in existing "Basics" tutorial, or within the "Data Access" part of the doc (under "Help & Reference") or in a new dedicated part... but I think it's worth (re)documenting more explicitly all the options for "Data Query".

Then, more specifically for the "query session" mode, we should also document the requirement on back-end Rest API _min_ version.

Thanks

**Comment by fabiencelier** [comment]
This used to exist and have been removed in the tutorial refactoring: https://docs.atoti.io/0.4.0/tutorial/08-Queries.html

We should add something back into the doc, possibly the same page ?

I don't want to add it into "Basics" because "Basics" is made for new users and this query_session stuff is mostly for existing AP clients.

**Comment by rcolle** [comment]
Agree with @fabiencelier . We could add it back as an extra tutorial.

**Comment by flebr1** [comment]
Yes.  That's fine by me.

I would also emphasize on the fact that my ask is twofold: one is about mentioning (again) about the "query session" feature, but the other is about the fact that right now we don't have a clear entry point / section summarizing all API options to query data.

Atm in the "Help & Reference" section, we have a "Data Access" entry... wondering if we should/could rename that "Data Loading" (as it seems that's more of what's addressed in there atm), and add another entry called "Data Querying"...?
