### ISSUE TITLE
Client unable to use atoti - connection issues

### ISSUE THREAD

**Issue by SBrown52** [atoti/atoti#102]
Hi,

One of ActiveViam's clients are trying to use atoti on a project. When they try to create a conda environment they a `HTTP 000 CONNECTION FAILED` error when trying to connect to https://conda.atoti.io/win-64/current_repo.json

My first thought would be that since other people are able to use it, would it possibly be an issue with their network and files blocking it? However when I go to that URL I get the same error message.  

## Steps to reproduce
Below is a screenshot sent to me from their developer. As you can see, they are using Anaconda and windows.

![image](https://user-images.githubusercontent.com/9969195/87440489-f4015000-c5e9-11ea-89e9-41a6af4cc878.png)

**Comment by fabiencelier** [comment]
I don't have any issue on Linux, I see "similar" logs when using the `--verbose` option but it does not stop the env creation or the atoti installation:
```
$ conda create -n atoti --verbose
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
Unable to retrieve repodata (response: 404) for https://conda.atoti.io/linux-64/current_repodata.json

Unable to retrieve repodata (response: 404) for https://conda.atoti.io/linux-64/repodata.json

initializing UnlinkLinkTransaction with
  target_prefix: /home/fabien/miniconda3/envs/atoti
  unlink_precs:
    
  link_precs:

## Package Plan ##

  environment location: .../atoti

Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

I will try and check on my windows

**Comment by fabiencelier** [comment]
It also works fine on windows 10.
I'm pretty sure this should not stop the environment creation. I have run the command with `--debug` and conda fallbacks on other URLs like that:
 - https://conda.atoti.io/win-64/current_repodata.json (404)
 - https://conda.atoti.io/win-64/repodata.json (404)
 - https://conda.atoti.io/noarch/current_repodata.json (404)
 - https://conda.atoti.io/noarch/repodata.json (SUCCESS)

We don't have a win-64 folder as the package is not OS specific.

You may have an old version of conda that acts differently. I have 4.8.3 and it works fine.
Can you share your version ?

You can also try with the `--verbose` or `--debug` option to see if you have more info.

**Comment by SBrown52** [comment]
Thanks Fabien, I will pass that on to the client and ask them to try the two options

**Comment by SBrown52** [comment]
I would add as well that we don't actually want to use atoti per se, but we want to query the cube in python and get the data into pandas for further analysis. The client currently does a lot of reporting using Excel, and we want to replace that with python and notebooks. Unfortunately, we have to use the full atoti stack just to be able to query an existing cube - there was a previously stand alone project for doing this, maybe we could investigate splitting atoti up so we can just use the modules we need?

**Comment by SBrown52** [comment]
Client has resolved the issue
