### ISSUE TITLE
Documentation on Plotly Charts customization

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#105]
## Description

We have been asked few times on how we can customize the plotly charts in atoti's visualization or web application.
It would be nice to have some documentations on how we can achieve it, just as described in https://github.com/atoti/atoti/issues/104

**Comment by fabiencelier** [comment]
On one hand I don't like this way of customizing the widgets as I think it is really hard to use and impossible to discover. This can scare new users by making atoti looks hard to use and configure.
On the other hand this is the only way to do it at the moment so we might as well document it to make it less difficult to use.

What I think is difficult at the moment:
  - finding the state editor: this is not a place people usually look at.
  - finding where to edit in the JSON: this is really not user friendly
  - finding which parameter can be used: one have to search and read the plotly documentation 

On the long run I think we should have tools to cover most of the basic use cases (color, size, font of text, width and shape of lines...) and keep this JSON editing mode for advanced use cases only

**Comment by fabiencelier** [comment]
Also if we document the JSON edition as the official way to customize the widget we can think about making it more accessible/discoverable than to *Property inspector tab* then *Advanced tools*.
For instance I am thinking about adding a button on the chart to directly open this pannel, or including the JSON editor in the atoti tab (for example in the "Style" pannel)

**Comment by HuifangYeo** [comment]
I agree it would be nice to have a function on the chart to perform the customization instead of going to the cell properties. This way, there's less things users have to pay attention to.
