### ISSUE TITLE
Error with at when trying to shift to the value of another level

### ISSUE THREAD

**Issue by SamTaz** [atoti/atoti#11]
Hello,

The Atoti documentation mentions that: 

> at takes the value of the given measure shifted on one of the level to the given value.
> 
> The value can be a literal value or the value of another level

And using the value of another level was working at some point as @fabiencelier uses it in https://github.com/activeviam/atoti/issues/940

But for me I cannot seem to make it work.

I am working on a soccer notebook where on one line of the facts I have `Team` and `Opponent`, managed to create a measure `Team Goals` and was trying to compute a measure `Opponent Goals` with the following line:
`m["Opponent Goals"] = atoti.at(m["Team Goals"], {level["Team"]: level["Opponent"]})`
But I can never see any result for the `Opponent Goals` measure in a pivot table, even when all hierarchies are expressed.
On the other hand if I "hardcode" the opponent doing the following:
`m["Norwich Goals"] = atoti.at(m["Team Goals"], {level["Team"]: "Norwich"})`
Then the measure is computed as expected.

Find below a short notebook allowing you to reproduce (1st of april atoti version):
[atWithLevelIssue.zip](https://github.com/atoti/atoti/files/4421446/atWithLevelIssue.zip)

**Comment by fabiencelier** [comment]
I can reproduce with this example:

```python
import pandas as pd
import atoti as tt
teams_df = pd.DataFrame({
    "team": ["a", "a", "a", "b", "b", "c"],
    "opponent": ["b", "c", "d", "c", "d", "d"],
    "day": [1,2,3,3,2,1]
})
goals_df = pd.DataFrame({
    "team": ["a", "a", "a", "b", "b", "b", "c", "c", "c", "d", "d","d"],
    "day": [1,2,3,1,2,3,1,2,3,1,2,3],
    "goals": [0,1,0,2,0,3,0,0,1,1,0,2]
})

session = tt.create_session()

match = session.read_pandas(teams_df, keys=["team", "opponent"])
goals = session.read_pandas(goals_df, keys=["team", "day"])
match.join(goals, mapping={"team": "team", "day":"day"})

cube = session.create_cube(match)
m = cube.measures
lvl = cube.levels
m["goals"] = goals["goals"]
m["opponent goals"] = tt.at( m["goals"], { lvl["team"] : lvl["opponent"] })
cube.query(m["goals"], m["opponent goals"], levels=[lvl["team"], lvl["opponent"]])
```

team  |  opponent | goals | opponent goals
-- | -- | -- | --
a | b | 0 | None
a | c | 1 | None
a | d | 0 | None
b | c | 3 | None
b | d | 0 | None
c | d | 0 | None

**Comment by fabiencelier** [comment]
After investigating here is what happens: when doing `at( m["goals"], { lvl["team"] : lvl["opponent"] })` for instance for team A and opponent B we shift to the position team B and opponent B where there is no fact (no team plays against itself) so the result of the measure is empty.

`at` is not the solution here, what you can do is creating 2 goals stores and join one on `team` and the other on `opponent`.

This should work but it is not ideal as you will duplicate the data and increase the memory usage. 

What you really need, but is not possible yet, is to join the same goals store twice on the base store. We are working on it internally to provide this new possibility.

**Comment by SamTaz** [comment]
The inability to join the same goals store twice on the base store is indeed what lead me to try something with an `at` and it would be really great to have it.

From what you say also, it seems that I was in fact doing only half of the necessary shift. Tried with:
`m["Opponent Goals"] = atoti.at(m["Team Goals"], {level["Team"]: level["Opponent"], level["Opponent"]: level["Team"]})`
And it now works when levels Team and Opponent are expressed.
I'm not sure though such measure definition is performant or a best practice :)

Thanks !
