### ISSUE TITLE
CSV separator at the end of the row

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#114]
## Description
Sometime we get CSVs that doesn't follow the proper csv format and we end up with csv that have a last column empty. Atoti can't read this csv because the last column (empty) doesn't have a name.

**Comment by fabiencelier** [comment]
As discussed this is not really the CSV standard so we don't plan to support it at the moment.

There are many ways to workaround that, one being using `sed` to remove the last character of each line:
```bash
sed 's/.$//' input.txt > output.txt
```

I am closing this issue at the moment but if anyone has the same use case feel free to comment
