### ISSUE TITLE
UnsupportedOperationException: Cannot read 'int' value from an instance of ArrayChunkLongNullable

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#115]
Hello!

I’m trying to pick a value from vector based on the number of contributors in the current location, as follows m['T Critical Value'] = m['CriticalValuesVector.VALUE'][m['contributors.COUNT']] and getting this exception: UnsupportedOperationException: Cannot read 'int' value from an instance of ArrayChunkLongNullable  Why is that? and is there a way to solve it?

## Steps to reproduce

The code reproducing the issue is available in this notebook:

https://github.com/atoti/notebooks/blob/statistics/statistics/drug-efficacy/main.ipynb

## Actual Result

UnsupportedOperationException: Cannot read 'int' value from an instance of ArrayChunkLongNullable

## Expected Result

I want to pick first, second or nth value - depending on the number of contributors.COUNT in this current location.

**Comment by bloussou** [comment]
It is due to the type of `m['contributors.COUNT']` which is `long`. `long` will be supported to access array elements.
