### ISSUE TITLE
Existing measure not found

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#116]
## Steps to reproduce
Hello,
I have an unexpected behaviour when sending some MDX queries to ActivePivot. The query is slow (and I need 60 seconds of time out) so I am adding filters and "sometimes", I have the following exception with existing measure that are not found anymore.
I have no idea of a way to reproduce it in a simple notebook. What could I provide you in order to investigate?

The notebook is: [Application.zip](https://github.com/atoti/atoti/files/4953598/Application.zip)

## Actual Result
IllegalArgumentException: Unknown measure contributors.COUNT: [StackTrace.txt](https://github.com/atoti/atoti/files/4953582/StackTrace.txt)
The full logs are: [subprocess.zip](https://github.com/atoti/atoti/files/4953603/subprocess.zip)

## Expected Result
Filtered results.

## Environment
- atoti: 0.4.2.20200715142716
- Python: 3.8.4
- Operating System: win32

**Comment by fabiencelier** [comment]
Hello

This is likely a bug in a post processor for measure named __hidden_31. What we need to do is find out which measure depends on __hidden_31 among the 9 measures you have queried to understand what is __hidden_31 then investigate this post processor.

Can you provide the data to reproduce the issue ?

We will add the type of the measure in the auto-generated names so we will have more info if this happen again. (https://github.com/activeviam/atoti/pull/1519)

**Comment by Harold7665** [comment]
Thank you.

The data are available here (shared to you at the moment): https://drive.google.com/drive/u/0/folders/13RcYJWTZWDXj28PPtuLYetbAiwOxyKQf

I think the bug comes with my query... When I get results, they are wrong. I am working with day to day comparison (shift) and ActiveUI filters on the previous day in order to distinguish all the new data (for a given day), this is the first time I am doing this with Atoti measures and ActiveUI filters (in both cases the results are wrong).

**Comment by fabiencelier** [comment]
I can reproduce with the following:

```python
m["test"] = tt.where(m['Previous ECL'] != None, m['ECL'] - m['Previous ECL'])
mdx = """
SELECT 
NON EMPTY {
    [Measures].[test]
} ON COLUMNS,
NON EMPTY [Hierarchies].[Contract ID].[Contract ID].members ON ROWS
FROM (
    SELECT  Filter([Hierarchies].[Contract ID].[Contract ID].Members, NOT IsEmpty([Measures].[Previous ECL])) ON COLUMNS
    FROM [IFRS9]  
    WHERE ([Hierarchies].[Reporting Date].[ALL].[AllMember].[2019-06-30], [Hierarchies].[Legal Entity].[Legal Entity].[Germany], [Hierarchies].[Segments].[ALL].[AllMember].[DIRECT], [Hierarchies].[Sector].[ALL].[AllMember].[Finance]))  WHERE ([Hierarchies].[Reporting Date].[ALL].[AllMember].[2019-06-30], [Hierarchies].[Legal Entity].[Legal Entity].[Germany], [Hierarchies].[Segments].[ALL].[AllMember].[DIRECT], [Hierarchies].[Sector].[ALL].[AllMember].[Finance])
"""
session.query_mdx(mdx, timeout=60)
```

But I cannot reproduce with a simpler example. This query also has a HUGE query plan created by the subselect filter not isempty, and I cannot reproduce the issue without this subselect so I might be related.

**Comment by bloussou** [comment]
Hello,
Do you reproduce with the latest version of atoti ?

**Comment by Harold7665** [comment]
Hello,
This is a bit old and I do not have the data anymore. I close it considering that it is now working and I will reopen if I see the issue again (but until now it never happened).
Thanks.
