### ISSUE TITLE
Error with Sclicing hierarchy and date_shift 

### ISSUE THREAD

**Issue by Osmane-bel** [atoti/atoti#118]
Hello, 
I can't use "date-shift" module with my sclicing hierarchy "Date" here. I think the error comes from the all level that doesn't exist on the hierarchy.
I want here to get the previous Value of the desired measure. It doesn't work with the "exact" or "previous" method. 

## Steps to reproduce

Cells 27 : 
m["previousValue"] = tt.date_shift(m["portfolioValue"], h["Date_Hierarchy"], offset="1D", method='exact')
## Actual Result

MdxException: Cannot resolve element [Hierarchies].[Date_Hierarchy].[ALL].[AllMember]. Hint: ALL is not a level of the Date_Hierarchy hierarchy

## Environment

- atoti:  0.4.1
- Python:
- Operating System:

## Logs (if relevant)

[performances.zip](https://github.com/atoti/atoti/files/4960669/performances.zip)

**Comment by fabiencelier** [comment]
Hello,

Thank you for reporting an issue :)

I think that is it the pivot table widget that is in a bad state and not a bug with date_shift.
I have run you notebook and do see the issue in the query Cell 27, but if I reset the widget and build the same pivot table (`Date_Hierarchy` on Rows and `portoflioValue` and `previousValue` in Measures) I have no issue:

![pivot table date_shift](https://user-images.githubusercontent.com/17087544/88203087-0d3d7880-cc4a-11ea-9e0f-970a7a7d7aca.png)

I am not sure how this widget ended up in a bad state like that. My guess is that you have first created the view with a non slicing hierarchy then put it slicing and the widget still tries to query All, but I might be something else.

Can you confirm that if you reset the widget you can see the shifted measure correctly ? (To reset you can either with right click > reset widget or call `PerfomanceCube.visualize()` in a new cell)

**Comment by fabiencelier** [comment]
Also as a side note: If _previousValue_ is the value of the previous day you should use an offset of "-1D" :wink: 

```python
m["previousValue"] = tt.date_shift(m["portfolioValue"], h["Date_Hierarchy"], offset="-1D", method='exact')
```

**Comment by Osmane-bel** [comment]
Hello, 

Checking the problem does come from there. I had indeed created my hierarchy in non sclicing at the beginning and then I modified it. By creating a new visualization it works. 

Thanks for your help :)

**Comment by fabiencelier** [comment]
I'm colisng this issue :)

If you have other bugs or questions feel free to open new issues.
If you want to chat about atoti you can also contact us on gitter: https://gitter.im/atoti/atoti
