### ISSUE TITLE
Partial joins for store with multiple keys

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#120]
## Steps to reproduce
Refer to attached notebook.
[geopricing.zip](https://github.com/atoti/atoti/files/4977677/geopricing.zip)

The store DistanceMatrix is made up of composite keys - ShopId and _CompetitorShopId.
![image](https://user-images.githubusercontent.com/35210495/88480191-0e8ede00-cf87-11ea-9233-4eae77c653f2.png)

However, it is not possible to join at the same time:
- distanceMatrix to the ProductSales by ShopId
- distanceMatrix to the CompetitorPrices by CompetitorId

Currently I managed to compute distance bucket by setting the conditions as follows: 
```
m["Same Competitor"] = tt.filter(1, (lvl["_CompetitorShopId"] == lvl["CompetitorShopId"]))
m["Count within distance threshold"] = tt.agg.sum(
    tt.where(
        (m["Same Competitor"] == 1) & (tt.agg.mean(m["Competitor distance KM.VALUE"]) < m["Distance Threshold"]), 1, 0
    ),
    scope=tt.scope.origin(lvl["ShopId"], lvl["_CompetitorShopId"]),
)
```
However, as we expand the use case such that I need to get the `CompetitorPrice` of products where it's within a given distance threshold, I kept running out of memory when I try to visualize the `Price Index` which uses the `CompetitorPrice.MEAN`
```
m["CompetitorPrice.MEAN"] =  tt.filter(
    tt.where(
        (m["Competitor distance KM.VALUE"] < m["Distance Threshold"]), m["CompetitorPrice.VALUE"], None
    ), 
    (lvl["_CompetitorShopId"] == lvl["CompetitorShopId"])
)
```

What is the best way to join the table with the minimal replication of data?

**Comment by Skyscimitar** [comment]
Hi Huifang! As you have correctly pointed out, atoti currently only supports star schemas for the datastore, so the references you want are currently impossible to create.
Unfortunately, the only way to create this join would be to merge the DistanceMatrix and the CompetitorPrices store, which does require a lot of data replication.
Sorry we don't have a better solution.

**Comment by HuifangYeo** [comment]
(╥︣﹏᷅╥)
