### ISSUE TITLE
Support reading zipped CSV

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#123]
## Description

A potential user has requested to support reading zipped CSV files as this was the way they stored large CSV files on AWS S3 buckets.

Parquet format could be the answer for better compression but:
- some are gzipping parquet files as well
- depending on their existing ecosystem they might not be able to change format.

When I tried loading a CSV file using atoti:

```python
import atoti as tt
session = tt.create_session()
res = session.read_csv(
    "results.zip",
)
res.head()
```

I had the following error:

```
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
<ipython-input-4-5e6ba34aa82e> in <module>
      1 res = session.read_csv(
----> 2     "results.zip",
      3 )
      4 res.head()

~/.conda/envs/atoti-release/lib/python3.7/site-packages/atoti/_docs_utils.py in wrapper(*args, **kwargs)
     16         @wraps(func)
     17         def wrapper(*args: Any, **kwargs: Any) -> Callable:
---> 18             return func(*args, **kwargs)
     19 
     20         # Collecting docstring and docstring templates

~/.conda/envs/atoti-release/lib/python3.7/site-packages/atoti/session.py in read_csv(self, path, keys, store_name, in_all_scenarios, sep, encoding, process_quotes, partitioning, types, watch, array_sep, sampling_mode)
    433             array_sep,
    434             pattern,
--> 435             mode,
    436         )
    437 

~/.conda/envs/atoti-release/lib/python3.7/site-packages/atoti/exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     73             raise AtotiJavaException(
     74                 cause, str(java_exception), java_exception,
---> 75             ) from None
     76         except Py4JNetworkError as error:
     77             raise AtotiNetworkException(str(error))

AtotiJavaException: Could not detect the separator of /home/XXXX/results.zip among the expected separators "\t", "|", ",", ";". Please specify the separator.
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path
```

However, if my information is correct, the underlying technology (CSV source) "can process .zip, .gz, .tar.gz archives or flat (text) files." 

Would it be possible to bring support in atoti as well?

**Comment by fabiencelier** [comment]
I think we already have the core technology for reading the zipped CSV files and only our discovery does not support it.

We could add the support for it but I think it's low priority as there is an obvious workaround (unzip the files or read it with pandas/spark)

Pandas has a [compression](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) parameter and works like that:

> compression{‘infer’, ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None}, default ‘infer’
>    For on-the-fly decompression of on-disk data. If ‘infer’ and filepath_or_buffer is path-like, then detect compression from the following extensions: ‘.gz’, ‘.bz2’, ‘.zip’, or ‘.xz’ (otherwise no decompression). If using ‘zip’, the ZIP file must contain only one data file to be read in. Set to None for no decompression.

**Comment by HuifangYeo** [comment]
Hi @fabiencelier,

during the demo today, the attendee was asking for the possibility of this as well.
He would like to try loading daily gzip of 5GB for 20 days.

**Comment by bloussou** [comment]
Hi @HuifangYeo,

I'm looking at it now. This should be added in a next version.

Best
