### ISSUE TITLE
Parameter lookup store

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#124]
## Description

When implementing complex aggregation functions, we often need to use parameters. At the moment a way to upload parameter data - is to upload them into a data store, but then it has to be joined with the base store somehow, otherwise it is not visible.

Please advise regarding the possibility to access stores which are not connected with the base store.
Examples:
1. In this notebook I'm creating a field "Experiment" to connect with the critical values table - which is an ugly construction: see cell 27: https://github.com/atoti/notebooks/blob/statistics/statistics/drug-efficacy/main.ipynb

2. In the finch Accelerators, see data model - there're always stores that are not connected with the risk data, and utilities allowing to lookup values based on conditions: https://support.activeviam.com/confluence/display/KB/SIMM+Data+Model

**Comment by Skyscimitar** [comment]
Hello! You should be able to do this using a parameter hierarchy (see [doc](https://docs.atoti.io/0.4.2/lib/atoti.html?highlight=parameter%20hierarchy#atoti.cube.Cube.create_parameter_hierarchy)). This allows you to create a single level hierarchy with a given set of members, which would be your `t-critical` values in this use case.

**Comment by APolyakova** [comment]
Hi @Skyscimitar thank you for this advice, I tried it out - having a hierarchy with critical values as members - however there seems to be now way to lookup a critical value and compare it with a measure in the cube? Is there a trick I don't know?

I need a measure which will lookup a critical value having the index (degrees of freedom) equal to contributors count. Then I need to compare a measure "t-statistic" with a "critical value"

<img width="734" alt="Screen Shot 2020-07-30 at 1 09 13 PM" src="https://user-images.githubusercontent.com/37184538/88970024-923a1a80-d266-11ea-8127-0c056c47485f.png">

```
cube.create_parameter_hierarchy(
    "Critical Values", list([t.ppf(0.95, d) for d in range(1, df.shape[0] + 1)]), index_measure="Degrees of Freedom"
)
```

<img width="592" alt="image" src="https://user-images.githubusercontent.com/37184538/88970122-b990e780-d266-11ea-8055-9fe3e7b7ee3e.png">

**Comment by APolyakova** [comment]
I'm closing this ticket as I found an alternative solution and I'm not blocked.

I might need to reopen when return to the SBM use case.
