### ISSUE TITLE
adding statistical functions - student, gauss, beta, chi-square

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#126]
Hi team

Could you please consider exposing these three most common stat functions -  pdf, cdf, ppf - for the common types of distributions

They are very common for stat analysis, hypothesis testing, confidence intervals, etc. For example, we've been working on this notebook for the gallery and we've tabulated the pdf function for different degrees of freedoms, but if it's easy to expose them in an atoti module, that would great.

https://github.com/atoti/notebooks/blob/statistics/statistics/drug-efficacy/main.ipynb

**Comment by APolyakova** [comment]
+ F distribution please.

**Comment by fabiencelier** [comment]
Hello,

I am willing to add these functions but I am not an expert on the subject.

We will probably not re-implement this ourselves at the moment and use an existing Java library. It would be helpful if you can point to Java methods we can use. For instance for [erf](https://docs.atoti.io/0.4.3/lib/atoti.math.html?highlight=erf#atoti.math.erf) we use [apache commons math](http://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/special/Erf.html)

**Comment by APolyakova** [comment]
Hi Fabien, I found these documents for java:

pdf -  density
cdf  - cumulativeProbability
ppf - inverseCumulativeProbability

**normal**: https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/distribution/NormalDistribution.html

**t, aka student** - https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/distribution/TDistribution.html

**chi-square** - https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/distribution/ChiSquaredDistribution.html

**F-distribution** - https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/distribution/FDistribution.html

**Beta** (VaR precision use case @robbiemouat ) - https://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/distribution/BetaDistribution.html

**Comment by APolyakova** [comment]
in scipy 
https://docs.scipy.org/doc/scipy/reference/stats.html

functions: ppf, pdf and cdf.

normal - norm

t, aka student - t

chi-square - chi2

F-distribution - F

Beta - beta

**Comment by fabiencelier** [comment]
Thank you for the links !

Correct me if I'm wrong but it looks like these distributions have different API, for instance NormalDistribution has `mean` and `standard deviation` while ChiSquaredDistribution has `degreesOfFreedom`.

So I think each distribution should have it's own specific API like this  

```python
# Density examples
atoti.stats.normal.pdf(
    point: Measure,
    mean: float = 0,
    standard_deviation: float = 1
)
atoti.stats.normal.pdf(
    point: Measure,
    degrees_of_freedom: int
)

# Cumulative Probability
atoti.stats.normal.cdf(
    point: Measure,
    mean: float = 0,
    standard_deviation: float = 1
)
atoti.stats.normal.cdf(
    point: Measure,
    degrees_of_freedom: int
)
```

### Naming

There are still a few point to discuss about naming:
  - package could be `atoti.stats`, `atoti.math.distribution`, `atoti.math.stats` or even directly `atoti.math`
  - functions:
      - `pdf` to match scipy or `density` to be more explicit
      - `cdf` or `cumulative_probability` ...

### Performance

I will check if creating the distributions in Java is costly or not (`new NormalDistribution(double mean, double sd)` for instance)
If it is fast we can take the params as measure and create a new distribution for each point according to the value of the params.
If it is slow we will have to create the distribution only once for all the points so we will have to take constants for parameters other  than `point`

**Comment by APolyakova** [comment]
Hi @fabiencelier I think atoti.stats could be a good name!

Also looking at your API example - is there a spelling error, because the degrees of freedom will be a parameter of chi2 not normal, correct? so should be this way, right?

atoti.stats.chi2.pdf(
    point: Measure,
    degrees_of_freedom: int
)


Best regards,
Anastasia

**Comment by fabiencelier** [comment]
This will be added into the next release, there will be the following new modules:

- atoti.stats.beta
- atoti.stats.chi2
- atoti.stats.f 
- atoti.stats.normal 
- atoti.stats.t

They all have the three functions `pdf`, `cdf`, `ppf`

**Comment by fabiencelier** [comment]
This has been added in 0.5.0 in the experimental [stats module](https://docs.atoti.io/0.5.0/lib/atoti.experimental.stats.html)
