### ISSUE TITLE
Shift measure is not correctly updated

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#127]
## Steps to reproduce
**Run 1**: 
![run_1](https://user-images.githubusercontent.com/7359377/89010056-2e6b2c80-d30e-11ea-93da-c1f88d56373a.PNG)
**Run 2**: 
![run_2](https://user-images.githubusercontent.com/7359377/89010079-34f9a400-d30e-11ea-80aa-95dfd6dd003a.PNG)

**Please be careful of the cell number in both screenshots**. As you can see in the **Run 1**, I am updating the **Test** measure and the **Test DtD** measure is wrong (no TOP value) when in the **Run 2**, I am directly using the right definition of the **Test** measure.

Notebook: [TestsSupport.zip](https://github.com/atoti/atoti/files/5005625/TestsSupport.zip)

## Environment
- atoti: 0.4.3.20200730092801
- Python: 3.8.5
- Operating System: win32

**Comment by fabiencelier** [comment]
Hello,
I don't understand what's the issue here. Can you explicit what is unexpected and what you expect ?

**Comment by Harold7665** [comment]
Hello,
I expect 2.377 for Test and -0.198 for Test (DtD) on the second result of Run 1. Instead, I only get 2.377 for Test.
