### ISSUE TITLE
Provide standalone python client for querying existing cubes

### ISSUE THREAD

**Issue by SBrown52** [atoti/atoti#128]
## Description

We have a few clients who would love to have a simple python library to query ActivePivot. Although it's possible to query the cube from any python code and return an object, having a supported API provided by ActiveViam would make it easier for clients to get started and use one.

There used to be an open source python connector created by an intern that several people were using, but this is no longer available.

Atoti now provides this functionality, however it is a bit of a pain to go through the whole process of installing atoti if all you need is to query an existing cube. Please consider splitting this off into a simple, easy to use module that everyone can use.

## Context

A number of clients would like a python API to query existing cubes, but not so simple and a bit bloated to install the full atoti package.

**Comment by SBrown52** [comment]
Any updates?

**Comment by rcolle** [comment]
Hi Sam.

Thanks for reporting this.
We're in the process of simplifying the atoti installation as much as possible.
I assume it would be OK to install the complete `atoti` package if it's as simple as `pip install atoti`, wouldn't it?

Thanks
Romain

**Comment by SBrown52** [comment]
Hi Romain,

Do I really need the full `atoti` package to query an existing cube (which includes download all those dependencies, a license etc? All I need and want is a simple python client. Basically I would like this back: https://github.com/activeviam/paris-internship-python-connector

Thanks,
Sam

**Comment by tibdex** [comment]
Hi Sam, we don't plan to extract the query capabilities to a dedicated package for now.

**Comment by SBrown52** [comment]
Just in case you were thinking about this again, I imagine it working as follows. 

Named to be decided but something like `activepivot-client`, `ap-client`, `atoti-client`
```
pip install ap-client
```

And then use it like the remote query api is already used
```
import ap-client as apc
remote_cube = apc.open_query_session("http://localhost:9090", auth=apc.query.create_basic_authentication("admin", "admin")
remote_cube.query(.....)
```

The benefits would then be that any existing customer or user could query the cube programatically using **our** python library.
