### ISSUE TITLE
Quick filter is case sensitive

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#132]
## Steps to reproduce
Please see the gif below, can the search be case-insensitive?
![quick_filter](https://user-images.githubusercontent.com/35210495/90491899-26ffac00-e173-11ea-99ab-e65aa2ecfbb1.gif)

## Environment
- atoti: 0.4.2
- Operating System: win32

**Comment by tibdex** [comment]
This is fixed in 0.5.0.
