### ISSUE TITLE
Scatterplot legend size

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#133]
## Steps to reproduce
The width of the the legend for scatter plot is taking up majority of the chart space when the dashboard space is halved.
My text field is trimmed.
![image](https://user-images.githubusercontent.com/35210495/90499217-db053500-e17b-11ea-9423-78bc06745aea.png)

Please see attached notebook, publish the chart widget and add a random widget to the same dashboard.
[Reddit.zip](https://github.com/atoti/atoti/files/5089632/Reddit.zip)

## Environment

atoti: 0.4.3.20200731141215
Operating System: win32

**Comment by tibdex** [comment]
Hi, I didn't look at your notebook yet but could it be a resize issue? What happens if you drag the bar between the two widgets? Does the Plotly chart rerenders with the expected size?

**Comment by HuifangYeo** [comment]
![scatter plot resizing](https://user-images.githubusercontent.com/35210495/90503657-6386d400-e182-11ea-985e-990a58e49868.gif)

**Comment by mtadams007** [comment]
It looks like the width is taking up so much space because one of the labels in it is very long. If you scroll down in the legend you can see there's a label with a long twitter url which is causing the legend to take up so much space
