### ISSUE TITLE
date_diff in business days

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#134]
Dear R&D team,

could you please consider implementing a function that will compute number of business days given a business calendar.

The example of this function in numpy: https://numpy.org/doc/1.18/reference/generated/numpy.busday_count.html

Use case: in SA-CCR we are computing number of days from today to maturity, and using that calculation to adjust notional, etc.  In the current version of the SA-CCR notebook we are using calendar days (not business days) as an approximation. 

See note in the regulation asking to use business days - para 52.49: https://www.bis.org/basel_framework/chapter/CRE/52.htm?inforce=20191215

It's ok for a prototype to use calendar days, but to be compliant we would need to use business days.

**Comment by fabiencelier** [comment]
Our [date_diff](https://docs.atoti.io/0.4.3/lib/atoti.html?highlight=date_diff#atoti.date_diff) supports different time units while this workday/holidays logic only makes sense for days so we might want to add new function such as the numpy `busday_count`.

I like the idea of a `weekmask` parameter as an array of size 7 defaulting to `[1,1,1,1,1,0,0]` combined with a `holidays` parameter which is a list of dates (defaulting to None)

**Comment by tibdex** [comment]
This would be a nice feature indeed but it's not planned for now.
