### ISSUE TITLE
Scatterplot size 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#136]
## Steps to reproduce
Before I add measure to the scatterplot, I could see my data spreaded. However, after adding the size, instead of increasing the size of the markers, the markers are all concentrated together. Is this expected?

![scatterplot size](https://user-images.githubusercontent.com/35210495/90609492-b4f09b00-e236-11ea-96cc-3f550035f788.gif)

## Environment

- atoti: 0.4.3.20200731141215
- Operating System: win32

**Comment by mtadams007** [comment]
I'm unable to reproduce. Could you share your notebook so I can investigate further? Thanks!

**Comment by HuifangYeo** [comment]
Hi @mtadams007 

I can't seem to replicate it anymore either. I'll close the case for now.
