### ISSUE TITLE
NPE when doing a MDX query on a larger amount of data

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#140]
## Steps to reproduce
![NPE](https://user-images.githubusercontent.com/7359377/91437686-8d1eba00-e86a-11ea-95ec-fd8f66975e83.PNG)
Dashboard: http://15.236.119.245:8080/#/dashboard/ba2
Notebook: http://15.236.119.245:8888/lab

## Actual Result
NullPointerException when doing this MDX query on a large amount of data.
Notes: 
- The query is about 4 920 810 contracts.
- The CPU usage is low when the query failed (under 10% for 1 or 2 seconds).
- It works when the only measure on the query is [Measures].[contributors.COUNT].
- The query with both [Measures].[contributors.COUNT] and [Measures].[ECL ] works by increasing the TimeOut to 120 seconds.
- The NPE happens when querying the [Measures].[ECL (DtD)].
- Sometimes I also get a **java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024** with the previous query, see the second file of logs.

## Expected Result
No exception except TimeOutException.

## Environment
- atoti: 0.4.3.20200820214258
- Python: 3.8.5
- Operating System: linux

## Logs
- [subprocess.zip](https://github.com/atoti/atoti/files/5136082/subprocess.zip)
- [subprocess.zip](https://github.com/atoti/atoti/files/5136303/subprocess.zip)

**Comment by rcolle** [comment]
This looks like a core bug. 
Can you share your notebook?
Also, can you confirm that you use the `sum_product` function?

**Comment by Harold7665** [comment]
In fact I am using the sum_product function to calculate the ECL.
Here is the full notebook: [Application.zip](https://github.com/atoti/atoti/files/5136331/Application.zip)
I am going to simplify it and to update this comment.

**Comment by rcolle** [comment]
Filed https://support.activeviam.com/jira/browse/APS-12868

**Comment by rcolle** [comment]
@Harold7665 can you also share the data files?

**Comment by Harold7665** [comment]
Hello,
Data are available here: https://drive.google.com/drive/u/0/folders/1X3FfXuQW6I9MYEzHa6y3FYIl_yhDYG-F (shared by default to Romain and Fabien - ask if you need an access).

**Comment by Harold7665** [comment]
I have tested again on the smaller dataset I used 1 month ago and the NPE happens even on this one, so there is no link to the amount of data.
