### ISSUE TITLE
Pivot Table - Expansion and collapse resulting in "The 2 objects do not have the same dimensionality"

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#141]
## Steps to reproduce

I have multi-level hierarchy `timeline` with 2 levels:
- date
- hour

I didn't expand the date but added a single level hierarchy instead. If I collapse the date level, it's fine. But on expanding again, I encounter the exception 
```
IncompatibleSetsException: The 2 objects do not have the same dimensionality: [[timeline], [coin_symbol]] and [[timeline]]
``` 
![collapse_expand_exception](https://user-images.githubusercontent.com/35210495/91526811-0daaec80-e937-11ea-935f-02b3b9a807a8.gif)

## Expected results
1. I could understand if I use "Expand By", my intention is for quick exploration. Hence collapsing the level, it will not be persisted. However, I added `coin_symbol` from content editor instead of using "Expand by" function, it should be a persisted level. I.e. even if I collapsed the level, I should be able to open it again. 

2. If it has to behave the way "Expand By" works, then `coin_symbol` should be removed from the atoti editor's rows when the level is all collapsed. It would be more consistent this way.

## Environment

- atoti: 0.4.2
- Operating System: win32

**Comment by HuifangYeo** [comment]
Refer to attached notebook.
[Expand_collapse.zip](https://github.com/atoti/atoti/files/5140353/Expand_collapse.zip)

**Comment by tibdex** [comment]
Hi Hui Fang, this issue is not applicable with the new UI in atoti 0.5.0.
