### ISSUE TITLE
Unexpected behavior in expanse/collapse in Pivot table after changing order of levels in rows

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#142]
## Steps to reproduce

`coin_symbol` is a single level hierarchy while `timeline` has 2 levels.
After expanding on `timeline` level to the `hour` level, I added the `coin_symbol` level. 
I needed the `coin_symbol` level to be on top of `timeline` instead. After changing sequence, the expand collapse started behaving weird.  Please see the below GIF.

![collapse_after_change_seq](https://user-images.githubusercontent.com/35210495/91527747-e7864c00-e938-11ea-9a36-de24d10eb0d4.gif)

Refer to last visualization in attached notebook.
[Expand_collapse.zip](https://github.com/atoti/atoti/files/5140349/Expand_collapse.zip)

## Environment
- atoti: 0.4.2
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, this issue is not applicable with the new UI in atoti 0.5.0.
