### ISSUE TITLE
Understanding values created in auto creation mode

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#143]
## Steps to reproduce

I have the following schema where `followers_count.VALUE` and `retweet_count.VALUE` is automatically created during cube creation in auto mode:
![image](https://user-images.githubusercontent.com/35210495/91532303-b27df780-e940-11ea-9186-eb26486f93e2.png)

I could understand the `followers_count.VALUE` available at the `tweet_id` level but why are there some values on some `hour` level:
![image](https://user-images.githubusercontent.com/35210495/91532174-83678600-e940-11ea-9748-6ebdb459008c.png)

Please see last visualization in attached notebook:
[measures.zip](https://github.com/atoti/atoti/files/5140619/measures.zip)

## Environment
- atoti: 0.4.2
- Python: 3.8.5
- Operating System: win32

**Comment by fabiencelier** [comment]
.VALUE are [single_value aggregations](https://docs.atoti.io/0.4.2/lib/atoti.html?highlight=single_value#atoti.agg.single_value) which from the doc is equal to:

> the value of the aggregated elements if they are all equal, and to None otherwise.

So for the hours where all the values are the same you have a value and for those where you have at least 2 different values it is null.

This is sometimes useful (for instance when you have correlated levels such as client name and client id)  but it is often confusing so we are planning to change this behavior to make it null above the key fields of the store.

**Comment by a-manai** [comment]
Hi,
To add to @fabiencelier 's answer, please note that since recently, `.VALUE` measures are no longer automatically created from store fields.
