### ISSUE TITLE
Manage the logs

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#144]
## Description

We need a way to deal with the logs file that can end up too big if you leave your instances running. Either delete them after the session is killed, or maybe delete them every hour. 

## Context

On the simcorp PoV we have a vm that stopped running because the logs took all the space available on the vm.

**Comment by fabiencelier** [comment]
I have hundreds of log folders in my `~/.atoti/logs/` folder and I only have a few MB, there might be an issue with your logs if they get so big

Does any lib has such feature of log management so we can see what already exists ? I'm not aware of anything like that for spark

**Comment by Skyscimitar** [comment]
I just checked my logs folder and I've reached 51Gb of logs, I imagine this is due to having larger projects running for long periods of time on my computer. Since things like license checks are continuously logged, if the atoti server is running for a long time it can start to build up.

**Comment by fabiencelier** [comment]
I also have process running for hours every day with License and health checks logged, I don't think that's the issue.

Can you check if you have a few huge log files that make most of your folder and what's in it ? It could be related to https://github.com/activeviam/atoti/issues/553 for instance, where a log is added for each line of the CSV.

**Comment by rcolle** [comment]
Spark does not automatically clean the logs, but there is an option for it.

See spark.history.fs.cleaner.enabled:
https://spark.apache.org/docs/latest/monitoring.html

**Comment by tibdex** [comment]
[`create_logging_config()`](https://docs.atoti.io/latest/lib/atoti.config.html#atoti.config.create_logging_config) can be used since 0.5.3.
