### ISSUE TITLE
Slow create_cube and load_all_data on large dataset

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#145]
## Steps to reproduce

Download `2019-Oct.csv` file (5.28GB - 42.448.764 rows) from https://www.kaggle.com/mkechinov/ecommerce-behavior-data-from-multi-category-store

Then run the following lines: (I used `%%time` to obtain the timing, running each line in a separate cell)
```python
import atoti

# CPU times: user 4.73 ms, sys: 4.05 ms, total: 8.77 ms
# Wall time: 4.91 s
session = atoti.create_session()

# CPU times: user 8.12 ms, sys: 4.26 ms, total: 12.4 ms
# Wall time: 323 ms
october_store = session.read_csv('2019-Oct.csv')

# CPU times: user 2.11 ms, sys: 0 ns, total: 2.11 ms
# Wall time: 9.75 s 
cube = session.create_cube(october_store)

# CPU times: user 4.51 ms, sys: 2.73 ms, total: 7.24 ms
# Wall time: 1min 55s
session.load_all_data()

# CPU times: user 24.2 ms, sys: 13.8 ms, total: 38 ms
# Wall time: 1.77 s
cube.query(m['contributors.COUNT'])
```

Do the same thing with `2019-Nov.csv` (8.38GB - 67.501.979 rows):

```python
# CPU times: user 2.29 ms, sys: 0 ns, total: 2.29 ms
# Wall time: 15.3 s
cube = session.create_cube(november_store)

# CPU times: user 9.56 ms, sys: 2.94 ms, total: 12.5 ms
# Wall time: 3min 17s
session.load_all_data()

# CPU times: user 30.1 ms, sys: 7.25 ms, total: 37.4 ms
# Wall time: 1.7 s
cube.query(m['contributors.COUNT'])
```

## Actual Result

Two things worth noting:
- although only 10.000 rows have been loaded, `create_cube` takes 10 seconds with the 5.3GB file and 15 seconds with the 8.4GB file.
- `load_all_data` which loads the CSV files and create the cube takes 2 minutes with the 5.3GB file and 3 minutes 17 seconds with the 8.4GB file

In comparison, with pandas the 5.3GB file is loaded in 40 seconds...

```python
import pandas as pd

# CPU times: user 36.9 s, sys: 2.67 s, total: 39.6 s
# Wall time: 39.6 s
october_df = pd.read_csv('2019-Oct.csv')

# CPU times: user 15 µs, sys: 1e+03 ns, total: 16 µs
# Wall time: 19.6 µs
october_df.shape[0]
```

And the 8.4GB file is loaded in 1 minute 7 seconds...

```python
import pandas as pd

# CPU times: user 1min 2s, sys: 5.11 s, total: 1min 7s
# Wall time: 1min 7s
november_df = pd.read_csv('2019-Oct.csv')

# CPU times: user 11 µs, sys: 1 µs, total: 12 µs
# Wall time: 14.8 µs
november_df.shape[0]
```

## Expected Result

(1) I would expect `create_cube` to be much faster and to depend for the greater part on the loaded data (i.e. 10.000 in each case). It seems to be impacted by the underlying large file.

(2) Is there any way we can improve the file loading/cube creation time and get closer to/beat pandas timing?

Note that I haven't changed the `max_memory` parameter and/or set any JAVA flags as I think most of our users would not tweak those parameters. If some of those improve timings or fix the issue please document them. 

## Environment

- atoti: 0.4.4.20200901144640
- Python: 3.8.5
- Operating System: linux
- CPU:  Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz; 4 cores, 8 threads
- RAM: 32GB

**Comment by rcolle** [comment]
This is caused by the fact that the data set contains some very high cardinality fields that are automatically used as hierarchies (in this case `user_session` notably).
If you create a cube without default hierarchies, you get the following times:

```
%%time
cube = session.create_cube(october_store, mode="manual")
Wall time: 5.04 s

%%time
session.load_all_data()
Wall time: 31.7 s
```

The parsing is done at a pretty reasonable rate on my laptop (assuming a ~200MB bandwidth on my hard drive):
`INFO: 5 GiB 286 MiB (5668612855), 42448765 lines, 42448764 records read from 2019-Oct.csv in 34s (156 MiB 445 KiB (164034204)/s, 1228351 lines/s, 1228351 records/s) (2704 tasks, 2.11% reading, 4.85% decoding, 0.08% waiting, 18.04% stripping, 60.95% parsing, 13.94% publishing)`

ActivePivot / `atoti` has to materialize the hierarchies to provide advanced filtering / slicing / dicing capabilities, which is why it can take a longer time when some high cardinality (gt 100.000) hierarchies exist.

**Comment by rcolle** [comment]
We have discussed at some point the idea of no automatically including a field as a hierarchy if its cardinality is too high.
However, it's not supported by ActivePivot (unless we compute the cardinality beforehand, but that'll likely increase the creation time too much)

**Comment by jbe456** [comment]
>We have discussed at some point the idea of not automatically including a field as a hierarchy if its cardinality is too high.

That would be awesome. It could be another mode as well if you think it's too costly for regular data set. Anyway, once we document it in an article, people should know to use the `manual` mode for now.

`create_cube` still takes 9 seconds in manual mode prior to loading the data. Have you looked into improving that as well since there is no "high cardinality" hierarchy to create at this point of time?

```python
# CPU times: user 2.13 ms, sys: 605 µs, total: 2.74 ms
# Wall time: 8.7 s
cube = session.create_cube(october_store, mode='manual')
```

**Comment by fabiencelier** [comment]
> although only 10.000 rows have been loaded, create_cube takes 10 seconds with the 5.3GB file and 15 seconds with the 8.4GB file.

There is an issue in the CSV sampling where much work is done even if only a few are used. 

Related internal issue: https://support.activeviam.com/jira/browse/APS-12918

**Comment by tibdex** [comment]
With the upcoming release where the sampling has been removed since tables/stores are not reloaded every-time the session structure changes:

```
%%time
october_table = session.read_csv("2019-Oct.csv", table_name="Test")
Wall time: 17.3 s

%%time
cube = session.create_cube(october_table, mode="manual")
Wall time: 4.27 s

%%time
cube.query(cube.measures['contributors.COUNT']) # 42,448,764
Wall time: 1.52 s

%%time
pd.read_csv("2019-Oct.csv")
Wall time: 51.5 s
```

Tested on macOS with a 2,3 GHz 8-Core Intel Core i9 and 32 GB 2400 MHz DDR4.
