### ISSUE TITLE
& character in pivot table members make the export to HTML fail

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#148]
## Steps to reproduce

```python
import atoti as tt
import pandas as df

data = df.DataFrame({
    "c1": ["a", "b&c"],
    "v":[10.0, 20.0]
})
session = tt.create_session()
store = session.read_pandas(data, store_name="data")
cube = session.create_cube(store)
cube.visualize()
# put c1 level on rows to display "b&c"
# export to HTML
```

Looks like `&` is not correctly escaped and the export fails.

## Actual Result

[Untitled.zip](https://github.com/atoti/atoti/files/5195613/Untitled.zip)

![broken html](https://user-images.githubusercontent.com/17087544/92607720-c74d7a00-f2b4-11ea-8dd3-cf49717d7043.png)

## Env

- atoti: 0.4.3
- Browser: Firefox

**Comment by Skyscimitar** [comment]
HTML entities in tabular widgets are now correctly encoded.
The fix will be available in the next release.
