### ISSUE TITLE
Array indexing doesn't support array[-1]

### ISSUE THREAD

**Issue by dudu-creator** [atoti/atoti#149]
## Steps to reproduce

```python
m = cube.measure
m[new]  = m[old][-1]
```

## Actual Result

<pre>
error in cube.query
error: Cannot access index -1 in a vector of size 250
</pre>

## Expected Result
No error and `array[-1]` should be equivalent to `array[atoti.array.len(array)-1]`
## Environment

- atoti: 0.4.3
- Python: 3.8.5
- Operating System: Mac

**Comment by dudu-creator** [comment]
opps I think this should be **Feature Request** instead of a Bug as we do have a workaround here. Please re-label it if you can.

Thanks,
Junchao

**Comment by bloussou** [comment]
Hi Junchao,
This will be available in the next release.
Best

**Comment by dudu-creator** [comment]
Sounds great!
