### ISSUE TITLE
Filter got removed when level is removed

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#150]
## Steps to reproduce
I have a custom filter:
```
Filter(
  [Hierarchies].[text].[text].Members,
  InStr(
    1,
    [Hierarchies].[text].CurrentMember.MEMBER_CAPTION,
    "trump"
  ) > 0
)
```
If I remove the level "text" from the rows/columns, the filter also get removed.

![filter_got_removed](https://user-images.githubusercontent.com/35210495/93161573-65be5d00-f745-11ea-9b35-5488459b1d98.gif)

## Environment

- atoti: 0.4.3
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, this issue is not applicable with the new UI in atoti 0.5.0 so I'm closing it.
