### ISSUE TITLE
Widget loading failed - Unknown measure

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#151]
## Steps to reproduce
I have an existing cell with `cube.visualize()` and it uses a measure which is no longer available.
The atoti editor is no longer available for the cell, hence it is not possible to use it to modify the query.  
Sometimes, it is difficult to recall what type of visualization was saved in the notebook and what it is intended for.
![Unknown measures 0](https://user-images.githubusercontent.com/35210495/93189372-a5e90400-f774-11ea-81c9-82a01771ed73.png)

I had to go to the cell meta to update which is more technical and not user friendly.
![fix_unknown_measure](https://user-images.githubusercontent.com/35210495/93199686-3f1e1780-f781-11ea-8af3-c39c1132679c.gif)

## Environment

- atoti: 0.4.3
- Python: 3.8.5
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, as for #147, the problem will go away when the query will be executed on the client side again.
