### ISSUE TITLE
Support measure descriptions

### ISSUE THREAD

**Issue by SBrown52** [atoti/atoti#167]
## Description

Add support for measure descriptions in atoti

## Context

In standard AP cubes, we often add a measure description to provide any information, to explain what the measure is - basically, provide a description as it suggests.

Perhaps I create some measures in a cube, and share the session url with another user. It would be great if they could read the description for any measures I created. For example from the tutorial, we create the percentage of parent measures, but you need the product hierarchy in order to view the values. In a normal AP project, we would add this information to the description so users are aware. It would be nice to be able to do something similar in atoti:

```
m["Percent of parent amount"].description = "Amount.SUM as a percentage of it's parent. Needs to be used with the Product hierarchy"
```

## Other information (if relevant)
I tried the snippet. It didn't fail, but nothing appears in the UI.  Looking at the doc, it does not look like descriptions are supported.
https://docs.atoti.io/0.4.3/lib/atoti.html#module-atoti.named_measure

**Comment by fabiencelier** [comment]
+1 for this, it should be easy to add and useful when sharing project with other users.

For anyone wondering, it's displayed when hovering the measure in ActiveUI

![descr](https://user-images.githubusercontent.com/17087544/95588292-8aa3a880-0a43-11eb-9bd0-384982213802.png)

**Comment by SBrown52** [comment]
Nice @fabiencelier, look forward to seeing it!
