### ISSUE TITLE
Impossible de joindre la communaute 

### ISSUE THREAD

**Issue by fercus** [atoti/atoti#173]
Une erreur s'est produite lors de l'envoi de votre inscription.

**Comment by jbe456** [comment]
Thanks @fercus for reporting it. I can indeed reproduce the issue. We'll take care of it and let you know once it's fixed.

![image](https://user-images.githubusercontent.com/4415696/97169350-34946c00-178a-11eb-864d-aef32d13378c.png)

**Comment by jbe456** [comment]
Hello @fercus  the issue has been resolved. You may subscribe via our website from now on.
