### ISSUE TITLE
Support sparse vectors in atoti

### ISSUE THREAD

**Issue by SBrown52** [atoti/atoti#174]
## Description

Support the concept of sparse vectors in atoti

## Context

Some calculations such as IMA-DRC use large vectors of up to 1m elements, however most of the values may be 0 (or other value where they are all the same). Storing large vectors such as this consumes large amounts of memory. We have previously created custom SparseVector implementations to work around this in AP projects, and these feature in a number of our finance accelerators. It would be great if these were available in atoti.

Another use case is vectorised cashflows in liquidity projects which benefits from using sparse vectors.

## Other information (if relevant)

You can search for sparse vector details on ActiveViam's confluence page for more information about this.

**Comment by fabiencelier** [comment]
It would be even better to have it supported in the core ActivePivot !

Then I think we should always detect normal vectors but let the user force a sparse type if necessary.

Some links about it:

 - [Confluence page about performance]( https://support.activeviam.com/confluence/pages/viewpage.action?spaceKey=KB&title=MRA+Sensi+cube+performance+testing+-+Sparse+versus+plain+vectorized+cube) (slower but really less memory)
 - [ReadOnlySparseVector](https://github.com/activeviam/market-risk-accelerator/blob/dda62bc68f6f047d6bebbc39a5eccbcea6c79824/risk-core/src/main/java/com/activeviam/risk/core/vector/impl/ReadOnlySparseVector.java) implementation in Market Risk Accelerator

**Comment by SBrown52** [comment]
Fastest way to get something in the core is to ask for it in atoti 😉

**Comment by Acriss** [comment]
That sounds true :eyes:

**Comment by tibdex** [comment]
Indeed, this would need to be done in ActivePivot first.

**Comment by fabiencelier** [comment]
Related internal issue: https://support.activeviam.com/jira/browse/PIVOT-4621
