### ISSUE TITLE
Atoti+ 0.4.3 widget not showing in Jupyter Lab

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#176]
## Steps to reproduce

Notebook attached
[aotitplus_widget_not_showing.zip](https://github.com/atoti/atoti/files/5480490/aotitplus_widget_not_showing.zip)

## Actual Result

Widget not showing:
"Waiting for cube connection
Execute the cell to start using this widget."

## Expected Result

Access to the widget configuration

## Environment

- Atoti+: 0.4.3
- Python: 3.7.8
- Operating System: win32

**Comment by tibdex** [comment]
Hi Xavier, do you see an error in the browser console or in the network tab?

**Comment by xpilasav** [comment]
No

**Comment by xpilasav** [comment]
By looking at the console of the browser, I was able to see "Activating atoti extension version 0.4.4" which is not the intended version I was expecting as I  want to use Atoti+ 0.4.3
the install command needs to be 
conda create -n <env_name> --yes atoti-plus=0.4.3 jupyterlab jupyterlab-atoti**=0.4.3** nodejs openjdk python
