### ISSUE TITLE
Copper join bug on AllMember

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#177]
## Steps to reproduce
Once you run the code in the snippet go in the ui and run those two queries:
`SELECT
  NON EMPTY {
    [Measures].[m1]
  } ON COLUMNS,
  NON EMPTY Hierarchize(
    DrilldownLevel(
      [copper_join].[l2].[ALL].[AllMember]
    )
  ) ON ROWS
  FROM [main]
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS`

`SELECT
  NON EMPTY {
    [Measures].[m1],
    [Measures].[m2]
  } ON COLUMNS,
  NON EMPTY Hierarchize(
    DrilldownLevel(
      [copper_join].[l2].[ALL].[AllMember]
    )
  ) ON ROWS
  FROM [main]
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS`

You should see that the top member for m1 changed.
I think it is related to https://support.activeviam.com/jira/browse/APS-12716 but I just wanted to reported it to be sure it is a known bug.

```
import atoti as tt
import pandas as pd
size_main = 100

df_main = pd.DataFrame({
    "l1": [str(i) for i in range(size_main)],
    "m1": [i for i in range(size_main)]
})

df_copper_join = pd.DataFrame({
    "l1": [str(i%3) for i in range(size_main * 3)],
    "l2": [str(i) for i in range(size_main * 3)],
    "m2": [i for i in range(size_main * 3)]
})
session=tt.create_session()
main_store = session.read_pandas(df_main, store_name="main")
copper_join_store = session.read_pandas(df_copper_join, store_name="copper_join", keys=["l2"])
main_store.join(copper_join_store, mapping={"l1":"l1"})
cube = session.create_cube(main_store)
lvl=cube.levels
m=cube.measures
m["m1"] = tt.agg.sum(main_store["m1"])
m["m2"] = tt.agg.sum(copper_join_store["m2"])
```

## Environment

- atoti: 0.4.4.20201030172317
- Python: 3.8.6
- Operating System: win32

**Comment by a-manai** [comment]
Hello Alexis,

Thanks for reporting this bug. It has recently been fixed, and related issues and concepts are also being discussed [here](https://github.com/atoti/atoti/issues/35).

Cheers,
Alex
