### ISSUE TITLE
Filter on sibling causes sibling widgets to be disconnected

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#178]
# Steps to reproduce

I have page level filters with `coin_symbol` as a slicing hierarchy.
The chart "cryptocurrency forecast" is set to filter siblings on click:
```
"configuration": {
        "handlers": {
          "click": [
            {
              "args": {
                "scope": "only-siblings"
              },
              "key": "member-filter"
            }
          ]
        }
}
```

On clicking a point on the chart, the rest of the widgets get disconnected from the parent filter as a widget level filter is added for `coin_symbol` despite there is already one on the page level.

![filter-sibling](https://user-images.githubusercontent.com/35210495/98505169-8d3c2c80-2293-11eb-88ed-d57fbd5a7229.gif)

## Environment

- atoti: 0.4.3
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, the next release will use ActiveUI 5 that doesn't support disconnecting a widget from parent filters (yet). It will thus make this issue non-applicable.
