### ISSUE TITLE
Better documentation for agg.single_value

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#18]
## Description

Right now `agg.single_value` is documented [here](https://docs.atoti.io/0.3.1/lib/atoti.html#atoti.agg.single_value) and says:

>Perform a single value aggregation of the input measure.

- Could we give more precision? It seems it looks for all values across the scope and if all the ones defined have the same value, it returns that value, otherwise it returns null (i.e. when there exist at least two different defined values).
- Could you add an example in the [tutorial](https://docs.atoti.io/0.3.1/tutorial/02-measures.html)? I had to look at https://github.com/activeviam/atoti/blob/f333a60d8630d4e361d98ceb1690d6c4ae8efb49/python/atoti/tests/test_measures.py#L155-L158 to understand how it works and what it does.

**Comment by fabiencelier** [comment]
Hello Julien,

Thanks for reporting the missing documentation. I have added a doc and example, it will be available is 0.3.2
