### ISSUE TITLE
date_diff: IllegalArgumentException: Input N/A of type class java.lang.String

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#180]
The check on empty values in a datetime column doesn't work, hence the date difference fails. Tested with !=None and !="N/A".

Kindly advise

## Steps to reproduce

This code snippet can be used to reproduce the issue:

```
import pandas as pd
import datetime


import numpy as np
df = pd.DataFrame(
    data={
        "first_date": [
            np.nan,
            datetime.datetime.strptime("2018-06-29", "%Y-%m-%d"),
            datetime.datetime.strptime("2018-06-30", "%Y-%m-%d"),
        ],
        "second_date": [
            datetime.datetime.strptime("2018-06-29", "%Y-%m-%d"),
            datetime.datetime.strptime("2018-06-30", "%Y-%m-%d"),
            datetime.datetime.strptime("2018-07-15", "%Y-%m-%d"),
        ],
        "values": [1.0, 2.0, 3.0]
    }
)

import atoti

session = atoti.create_session()
ds = session.read_pandas(
    df,
    store_name="base_store",
    keys=["first_date", "second_date"],
)
cube = session.create_cube(ds, "Olist")
h = cube.hierarchies
m = cube.measures
lvl = cube.levels

list(lvl)

m["first_date"] = atoti.agg.single_value(
    ds["first_date"]
)
m["second_date"] = atoti.agg.single_value(
    ds["second_date"]
)


m["wait_time_atoti"] = atoti.where(
    (lvl["first_date"] != None)
    & (lvl["second_date"] != None),
    atoti.date_diff(
        m["first_date"], m["second_date"]
    ),
)
```

Then try visualizing m["wait_time_atoti"] together with first_date and second_date

## Actual Result

date_diff: IllegalArgumentException: Input N/A of type class java.lang.String

## Expected Result

date difference is computed for date where both first date and second date are not empty

## Environment

- atoti: 0.4.4.20201104153759
- Python: 3.8.6
- Operating System: darwin

**Comment by fabiencelier** [comment]
Hello,

`atoti.where(condition, measure1, measure2)`  evaluates measure1 and measure2 everywhere and then choose between them according to the condition. This means that even if the condition is false your date_diff is computed with N/A and make the computation fail.

What you can do is use [filter](https://docs.atoti.io/0.4.3/lib/atoti.html#atoti.filter) instead:

```python
m["wait_time_atoti"] = atoti.filter(
    atoti.date_diff(
        m["first_date"], m["second_date"], unit="days"
    ),
    (lvl["first_date"] != "N/A")  & (lvl["second_date"] != "N/A")
)

cube.query(m["wait_time_atoti"], levels = [lvl['first_date'], lvl['second_date']])
```

| first\_date  | second\_date | wait\_time\_atoti |
|--------------|--------------|-------------------|
| 2018\-06\-29 | 2018\-06\-30 | 1                 |
| 2018\-06\-30 | 2018\-07\-15 | 15                |

**Comment by fabiencelier** [comment]
Thinking again about it, as "N/A" comes from a date level it should not raise an exception when used in `date_diff` but it should instead returned a value such as NaN or None.

**Comment by APolyakova** [comment]
Thank you @fabiencelier !
