### ISSUE TITLE
White labelling: Allow putting a logo into the top nav bar

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#183]
User story: As a user, I'd like to be able to customize the appearance of the atoti UI when I create my own APP. As a minimum, I want to be able to put my own logo next to atoti logo.

**Comment by tibdex** [comment]
Possible since 0.5.0 in Atoti+ by using [`create_config()`'s `branding` parameter](https://docs.atoti.io/0.5.0/lib/atoti.config.html#atoti.config.create_config).
