### ISSUE TITLE
atoti to Atoti+: cube.visualization shows query failed.

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#187]
## Steps to reproduce
I have used an atoti notebook in Atoti+ and added in security as follows:
```
role_test = tt.config.create_role("ROLE_TEST")
user_test = tt.config.create_basic_user("tester", "pass1", roles=["ROLE_TEST"])

basic = tt.config.create_basic_authentication(
    [user_test], realm="Configuration Tutorial"
)
```
When running the cells in the notebook, the `cube.visualize` executed and showed the visualization for a while before showing query failed message.

![atoti_to_atotiPlus](https://user-images.githubusercontent.com/35210495/100037063-61e14200-2e3c-11eb-963e-b8d32c5d4633.gif)

No exceptions in the logs. Please find the notebook used
[main.zip](https://github.com/atoti/atoti/files/5586934/main.zip)
[subprocess.log](https://github.com/atoti/atoti/files/5586937/subprocess.log)

## Environment

- atoti: 0.4.3
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, thanks for reporting this. It will be fixed in the next release.
