### ISSUE TITLE
atoti to Atoti+: database - cannot connect to content server

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#188]
## Steps to reproduce

My database is created with atoti. However, for the same notebook, I tried to upgrade to Atoti+.
I encountered the error: Could not connect to Content Server.

[ActiveUI_Report_11_24_2020__10_11_16_AM.zip](https://github.com/atoti/atoti/files/5587344/ActiveUI_Report_11_24_2020__10_11_16_AM.zip)

I deleted the database and restarted the notebook. This time it worked.

## Expected Result
As part of upgrade, I would like to retain the dashboards that I have created previously using atoti.
If I were to delete the db, it means that I have to recreate the dashboards all over again.

## Environment

atoti: 0.4.3
Operating System: win32

**Comment by tibdex** [comment]
Looks a lot like #15. Did you set up security in your Atoti+ session? If so, which type? You encountered the error in the JupyterLab extension or in the app?

**Comment by HuifangYeo** [comment]
Yup, I set up security:
```
role_test = tt.config.create_role("ROLE_TEST")
user_test = tt.config.create_basic_user("tester", "pass1", roles=["ROLE_TEST"])

basic = tt.config.create_basic_authentication(
    [user_test], realm="Configuration Tutorial"
)
```

The error is encountered on the app. I have raised a separate issue on the Jupyter lab.

**Comment by HuifangYeo** [comment]
I just upgraded to atoti+ 4.4 and pointing to the db of atoti+4.3, the "create dashboard" encounters 404.
[atoti_cs_404_error.log](https://github.com/atoti/atoti/files/5595476/atoti_cs_404_error.log)

Switching to a new db works.

**Comment by tibdex** [comment]
Hi Hui Fang, the error will be fixed in the next release. However, to see in the enterprise edition widgets and dashboards saved  with the community edition, you need to connect as a user with `ROLE_ADMIN`.
