### ISSUE TITLE
querying tutorial: add an example with a condition

### ISSUE THREAD

**Issue by chamb** [atoti/atoti#191]
In the [data querying tutorial](https://docs.atoti.io/0.5.0/tutorial/04-Data-Querying.html), add an example using a condition.

**Comment by fabiencelier** [comment]
There is already this: https://docs.atoti.io/0.5.0/tutorial/04-Data-Querying.html#Condition-in-queries

**Comment by chamb** [comment]
Great! thanks for adding it. I was actually looking at the previous doc that did not have it.
