### ISSUE TITLE
Layout issue with the app when using Safari

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#193]
Please see a screenshot of the atoti 0.5.0's app in Safari

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/37184538/102043661-e531eb80-3d89-11eb-9af3-b5ca7330a263.png">

**Comment by tibdex** [comment]
Hi Anastasia, thanks for reporting this. It's tracked in this [internal ticket](https://support.activeviam.com/jira/browse/UI-5030).
