### ISSUE TITLE
Visualization: The result exceeded the size limit

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#195]
## Steps to reproduce
while upgrading existing notebook, I encountered the error for visualization in both notebook and web application: 

```
The result exceeded the size limit [points size before contribution = 0, contribution size = 100096, max limit = 100000]
```
I only have 4 distinct competitors across 235144 records.

![image](https://user-images.githubusercontent.com/35210495/102059895-79ed2580-3e2c-11eb-8726-9cc8ce5c64cf.png)

## Environment

- atoti: 0.5.0
- Python: 3.7.9
- Operating System: win32

**Comment by fabiencelier** [comment]
This is a change that has been introduce in the latest version of AcxtivePivot that we did not notice. We will fix it in the next bugfix release.

## Details
This is a limit on the size of intermediate results in a query. For instance if you do a measure with a scope origin on a large level, atoti will create an intermediate result with one line per member of the level. This can take a lot of the machine memory which is bad for a production environment where several users use the application at the same time.
It has been added recently in ActivePivot with a default value to 100K.
You can read the internal issue [PIVOT-4191](https://support.activeviam.com/jira/browse/PIVOT-4191) or [ActivePivot related documentation](https://www.activeviam.com/activepivot/5.10-next/docs/monitoring/monitoring_query_execution.html#configurable-limits-on-query-results) for more details 

## Workaround:
The workaround until we fix it is to set the context values `queriesResultLimit.intermediateSize` et `queriesResultLimit.transientSize` to bigger limits (default is 100K and 1M).
There is no UI for context values in 0.5.0 but you put them directly in the state:
  - in JupyterLab you can see it in the "Property inspector" > "Advanced tools" > "Cell metadata" as I said.
  - you can go to `{session.url}/content` to access the Content Manager

**Comment by fabiencelier** [comment]
This will be fixed in the next release and next continuous build.
The value will now default to -1 (no limit) in community and to 1 million in Atoti+.
It will be configurable via `cube.shared_context["queriesResultLimit.intermediateSize"] = 1000000`

**Comment by fabiencelier** [comment]
Read the [shared context documentation](https://docs.atoti.io/latest/lib/atoti.html#atoti.cube.Cube.shared_context) for more details
