### ISSUE TITLE
atoti.value() or atoti.agg._single_value() error

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#196]
## Steps to reproduce

```
import atoti as tt
import pandas as pd
session = tt.create_session()
df1 = pd.DataFrame({
    "l1": ["a", "b"]
})

df2 = pd.DataFrame({
    "l2": ["a", "b"],
    "m2": [2,3]
})
store_1 = session.read_pandas(df1, store_name="1")
store_2 = session.read_pandas(df2, keys =["l2"], store_name="2")
store_1.join(store_2, mapping={"l1": "l2"})
cube = session.create_cube(store_1)
cube.measures["fail"] = tt.value(store_2["m2"])
```

If you remove the keys of store_2 it is working, else the single value generate an error when you try to create it.
It does not work neither with the atoti.agg._single_value().

It was working on 0.4.3 with the atoti.agg.single_value().

## Environment

- atoti: 0.5.0.20201208125600
- Python: 3.9.1
- Operating System: win32

**Comment by alexis-bvq** [comment]
If l1 has the same name as l2 it solves the issue too.
```
import atoti as tt
import pandas as pd
session = tt.create_session()
df1 = pd.DataFrame({
    "l1": ["a", "b"]
})

df2 = pd.DataFrame({
    "l1": ["a", "b"],
    "m2": [2,3]
})
store_1 = session.read_pandas(df1, store_name="1")
store_2 = session.read_pandas(df2, keys =["l1"], store_name="2")
store_1.join(store_2, mapping={"l1": "l1"})
cube = session.create_cube(store_1)
cube.measures["fail"] = tt.value(store_2["m2"])
```

**Comment by a-manai** [comment]
Hi,

There have indeed been some changes with the `value` operations. They always create a measure which has empty values above the levels of its key fields (unless specified otherwise) now. The bug you found is related to atoti not being able to understand that `l1` and `l2` are linked to the same cube level.

Thanks for reporting this bug, it is currently under investigation.

**Comment by a-manai** [comment]
Hello,

This issue has been fixed and the fix will be part of the next released version.
