### ISSUE TITLE
atoti.date_diff does not take level as argument anymore

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#197]
## Steps to reproduce
On 0.4.3 you could pass level as from_date and to_date arguments to the atoti.date_shift method, on 0.5.0 we can't and have to create a measure of the level and pass it as argument.

## Environment

- atoti:
- Python:
- Operating System:

**Comment by fabiencelier** [comment]
Do you mean date_diff ?

It should be solved by https://github.com/activeviam/atoti/pull/1877

**Comment by alexis-bvq** [comment]
yes sorry date_diff

**Comment by fabiencelier** [comment]
If you want more details about this:
We have not changed the code but we have added a stricter type checker that forces the user to pass arguments of the expected type. Level was not an expected type but I have added it activeviam/atoti#1877
