### ISSUE TITLE
Windows error when importing atoti with Python v3.7.9  and Numpy v1.19.4  

### ISSUE THREAD

**Issue by AlexVernet** [atoti/atoti#198]
A Windows error occurs when importing atoti with Python v3.7.9 and Numpy v1.19.4 :

## Steps to reproduce

Install Python 3.7.9 and Numpy 1.19.4 (I used pip  here)

- `pip install numpy==1.19.4`

- `jupyter lab`

- And in the notebook cell: `import atoti as tt`

## Actual Result

The atoti import fails with a stacktrace: `import atoti as tt`

&rarr; `RuntimeError: The current Numpy installation (<local_path>\\programs\\python\\python37\\lib\\site-packages\\numpy\\__init__.py) fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86`

## Expected Result

The atoti import should work and it should be possible to create a new atoti session.

## Environment

- atoti: 0.5.0 (2020-12-08)
- Python: 3.7.9
- Pip: 20.3.2
- Numpy: 1.19.4
- Operating System: Windows 10 Pro version 20H2

## Logs (stacktrace)

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-327892d4f69e> in <module>
----> 1 import atoti as tt
      2 
      3 
      4 

\python\python37\lib\site-packages\atoti\__init__.py in <module>
      2 
      3 from . import _compatibility  # Import first to fail fast
----> 4 from . import _functions, agg, array, comparator, config, math, query, scope, types
      5 from ._functions import *  # pylint: disable=redefined-builtin
      6 from ._java_utils import retrieve_info_from_jar

\python\python37\lib\site-packages\atoti\agg.py in <module>
     29 from .scope._utils import LeafLevels, Window
     30 from .scope.scope import Scope
---> 31 from .store import Column
     32 
     33 MeasureOrMeasureConvertible = Union[Measure, MeasureConvertible]

\python\python37\lib\site-packages\atoti\store.py in <module>
      5 from typing import TYPE_CHECKING, Any, Dict, Mapping, Optional, Sequence, Tuple, Union
      6 
----> 7 import pandas as pd
      8 
      9 from ._docs_utils import (

\python\python37\lib\site-packages\pandas\__init__.py in <module>
      9 for dependency in hard_dependencies:
     10     try:
---> 11         __import__(dependency)
     12     except ImportError as e:
     13         missing_dependencies.append(f"{dependency}: {e}")

\python\python37\lib\site-packages\numpy\__init__.py in <module>
    303 
    304     if sys.platform == "win32" and sys.maxsize > 2**32:
--> 305         _win_os_check()
    306 
    307     del _win_os_check

\python\python37\lib\site-packages\numpy\__init__.py in _win_os_check()
    300                    "See this issue for more information: "
    301                    "https://tinyurl.com/y3dm3h86")
--> 302             raise RuntimeError(msg.format(__file__)) from None
    303 
    304     if sys.platform == "win32" and sys.maxsize > 2**32:

RuntimeError: The current Numpy installation ('python\\python37\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

## Hot fix

This issue does not occur anymore with Numpy v1.19.3 :

- `pip install numpy==1.19.3`

**Comment by fabiencelier** [comment]
Hello,

This is a known issue of Numpy v1.19.4 on windows not related to atoti. I'm pretty sure you would have the same error by running `import numpy`.

In atoti we have already added as requirements a numpy version different to 1.19.4. (You can see that on [libraries.io](https://libraries.io/pypi/atoti) for instance or if you download the [wheel](https://pypi.org/project/atoti/0.5.0/#files))

I think you have got around this check because you have manually forced numpy to another version after installing atoti

**Comment by fabiencelier** [comment]
I don't see what additional step atoti can take about numpy 1.19.4 on Windows so I am closing this issue.

Feel free to comment and reopen if you disagree or if you have more questions about it
