### ISSUE TITLE
Discrepancy in defining a new measure

### ISSUE THREAD

**Issue by rvs36** [atoti/atoti#199]
```python
data = {'id':[1,2,3,4,5,6,7,8,9], 
        'response':[0,1,1,0,1,0,1,0,1],
       'prediction': [0,0,1,1,1,0,1,1,0]} 
  
# Create DataFrame 
df = pd.DataFrame(data) 

df['response'] = df['response'].astype(int)
df['prediction'] = df['prediction'].astype(int)
```
Creating a store:

```python
customer_store = session.read_pandas(
    df,
    store_name="customer_store",
)
customer_store.head()
```
Then I define a measure called true positive, a true positive occurs when the response = 1 and prediction = 1.

```python
m["true positive"] = tt.agg.sum(
    tt.filter(
        tt.where(l["response"] == 1, 1, 0), l["prediction"] == 1
    ),
    scope=tt.scope.origin(l["id"]),
)

```
I get the correct value as shown:

![image](https://user-images.githubusercontent.com/57663462/102979973-230bde00-4507-11eb-9846-7cfffaca1596.png)

But then, when I remove the filter and use the below code:

```python
m["true positive 2"] = tt.agg.sum(
        tt.where(((l["prediction"] == 1) and (l["response"] == 1)), 1, 0),
    scope=tt.scope.origin(l["id"]),
)
```
I get the values as shown below, which should not have been the case.

![image](https://user-images.githubusercontent.com/57663462/102979930-12f3fe80-4507-11eb-8543-d134ebb64a1b.png)

In my opinion, the latter should have also worked but it did not. Is this a bug, or I misunderstood something?

**Comment by rcolle** [comment]
I believe you need to use the bitwise `&` operator instead of `and` in your second définition.

@bloussou could you check if we can forbid the usage of `and` and `&&` by implementing some dunder methods?

**Comment by tibdex** [comment]
You could define your measure like this:

```python
m["true positive"] = tt.agg.sum(
    tt.where((l["response"] == 1) & (l["prediction"] == 1), 1, 0),
    scope=tt.scope.origin(l["id"]),
)
```
