### ISSUE TITLE
Typo in the "Rebuild JupyterLab" command line for Windows

### ISSUE THREAD

**Issue by mattiss** [atoti/atoti#20]
## Description

In
https://docs.atoti.io/0.3.1/installation.html
6. Rebuild JupyterLab
The Windows command line should be
`set NODE_OPTIONS=--max-old-space-size=4096 & jupyter lab build --dev-build=False --minimize=True`
instead of
`set NODE_OPTIONS=--max-old-space-size=4096 & jupyter lab build --dev-build False --minimize True`

## Context

- Atoti version: 0.3.1
- Python version: All
- Operating System: Windows

## Logs (if relevant)

**Comment by rcolle** [comment]
Hi @mattiss ,
I'm going to close this because the command seems to work with all people that tried it on Windows. 
Please comment again with the encountered message if you can and I'll check again. 
Thanks!
