### ISSUE TITLE
Not able to see the sub-total in the pivot table.

### ISSUE THREAD

**Issue by rvs36** [atoti/atoti#200]
When I create a data frame with the response and prediction columns:

```python
data = {'id':[1,2,3,4,5,6,7,8,9], 
        'response':[0,1,1,0,1,0,1,0,1],
       'prediction': [0,0,1,1,1,0,1,1,0]} 
  
# Create DataFrame 
df = pd.DataFrame(data) 

df['response'] = df['response'].astype(int)
df['prediction'] = df['prediction'].astype(int)
```
Creating a store:

```python
customer_store = session.read_pandas(
    df,
    store_name="customer_store",
)
customer_store.head()
```
Then I define a measure called true positive

```python
m["true positive"] = tt.agg.sum(
    tt.filter(
        tt.where(l["response"] == 1, 1, 0), l["prediction"] == 1
    ),
    scope=tt.scope.origin(l["id"]),
)
```
Trying to visualize it in a pivot table I could not see the total for the breakup of rows and columns:

![image](https://user-images.githubusercontent.com/57663462/102980243-90b80a00-4507-11eb-8fe0-8aeed5a07bf2.png)

I am trying to use `m["true positive"]` in a formula further and need to see if the value correctly calculated or not.

**Comment by tibdex** [comment]
Hi Raghav, you can use:

```python
m["true positive"] = tt.agg.sum(
    tt.where((l["response"] == 1) & (l["prediction"] == 1), 1, 0),
    scope=tt.scope.origin(l["id"], l["response"], l["prediction"])
)
```

to get the totals right.

**Comment by rvs36** [comment]
Thanks for your message, I used the code as suggested above. 
But I am still not able to see the total in the pivot table.
![image](https://user-images.githubusercontent.com/57663462/103083634-28d3f300-45dd-11eb-9bca-afd25bb24bf8.png)

Also, my end goal is to be able to use this value (3) in defining another measure later:
`# m["precision"] = m["true positive"] / (m["true positive"] + m["false positive"]) `

**Comment by bloussou** [comment]
This will be addressed in the next release.
