### ISSUE TITLE
LocalDate unrecognized as a date type in the UI

### ISSUE THREAD

**Issue by astroungu** [atoti/atoti#203]
## Steps to reproduce

Create a data store and cube with at least one field e.g., "Date"of type local_date("yyyyMMdd") and load data. 

## Actual Result

The field "Date" is represented in the UI filters and fields section as an ordinary textual field and none of the date-specific options appear in the filter UI.

## Environment

atoti 0.5.0 community edition + python 3.9 + Chrome on Windows 10

You may run the following Python code:

**Comment by xpilasav** [comment]
I tried the following code on 0.5 and indeed I can't see 'Day' being treated as a date in the UI even by forcing the type
Is it a change in the UI behavior or an issue?
`import atoti as tt
import pandas as pd
data = [
    ['A', "2020-12-13", 1],
    ['C', "2020-12-14", 3],
    ['B', "2020-12-15", 8],
]
session = tt.create_session("DateIssue")
data_df = pd.DataFrame(data, columns = ['Name' , 'Day', 'Val'])
data_store = session.read_pandas(data_df, "Data", types={'Day':tt.type.local_date('yyyy-MM-dd')})
cube = session.create_cube(data_store, 'Data')
session.visualize()`

**Comment by fabiencelier** [comment]
Hello,

The date field is recognized as a date in the store and in the cube.

You can confirm that by checking the type in the store

![store type](https://user-images.githubusercontent.com/17087544/103637587-fe265a80-4f4b-11eb-8b8b-34f7e9905ee3.png)

and in the level:

![level type](https://user-images.githubusercontent.com/17087544/103637603-05e5ff00-4f4c-11eb-92cf-128128060ce0.png)

Also it is displayed with a time axis in the chart:

![date graph](https://user-images.githubusercontent.com/17087544/103637666-16967500-4f4c-11eb-9b5a-b56c8ca2b879.png)

I think what is missing are the filters specific to dates (date picker, date ranges...) that used to be in 0.4.3
In 0.5.0 we have switch to the new version of the UI where this feature is missing. I have opened an internal issue [UI-5071](https://support.activeviam.com/jira/browse/UI-5071) so the UI team can work on adding it back to the product.

I will keep you updated.

**Comment by bloussou** [comment]
Hello, here is the new related ticket https://support.activeviam.com/jira/browse/UI-5289

**Comment by bloussou** [comment]
This is fixed since `0.6.5`
