### ISSUE TITLE
Chart doesn't display multiple measures

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#204]
## Steps to reproduce

I tried to add a second measure to the chart and it starts to behave weirdly, either not appearing or disappear after quick flash.

![multiple_measures_chart](https://user-images.githubusercontent.com/35210495/103644898-191bbd80-4f92-11eb-8b90-c8fe50700fd2.gif)

## Environment

- atoti: 0.5.0
- Operating System: win32

**Comment by rcolle** [comment]
Hi @HuifangYeo,
Does the same issue happen with the standalone AUI application?

**Comment by HuifangYeo** [comment]
Hi @rcolle, 

it's weird. I'm able to create it in other notebook. It could be MDX related.

**Comment by tibdex** [comment]
Hui Fang can you try with atoti 0.5.1 and, if you still have the issue, share a notebook with which it can be reproduced?

**Comment by HuifangYeo** [comment]
Hi @tibdex,

sorry for the late reply. In 0.5.1, I don't have the issue. However, the charts showed the same color for the split measures, hence it is misleading.

I opened a different ticket https://github.com/atoti/atoti/issues/231 for it and close this one.
