### ISSUE TITLE
Data Members not shown using session.query_mdx with DataMember MDX function

### ISSUE THREAD

**Issue by mwebborn-av** [atoti/atoti#205]
Hello, I believe there is a discrepancy in the behaviour of MDX using ActiveUI through session.visualize() and session.query_mdx when data members are found in the results.

## Steps to reproduce

1. Configure datastore in ActivePivot instance with IAxisMember.DATA_MEMBER_DISCRIMINATOR as the default value.
```   
 return new StoreDescriptionBuilder().withStoreName(StoreAndFieldConstants.TRADES_STORE_NAME)
                .withField(StoreAndFieldConstants.TRADES__TRADEID, STRING).asKeyField()
                .withField("Desk", STRING).asKeyField()
                .withField("Book", STRING).asKeyField()
                .withField("Entity", STRING, IAxisMember.DATA_MEMBER_DISCRIMINATOR)
                .build();
```
2. Add all these fields to one multi-level hierarchy.
```
return builder
                .withDimension("TestingEmpties")
                .withHierarchyOfSameName()
                    .withLevel("TradeID")
                    .withLevel("Desk")
                    .withLevel("Book")
                    .withLevel("Entity");
```
3. Create dataset with some empty values for last field "Entity"
```
TradeId,Desk,Book,Entity
Trade1,Desk1,Book1,Entity1
Trade1,Desk1,Book2,Entity2
Trade1,Desk2,Book3,Entity3
Trade1,Desk2,Book1,
Trade2,Desk1,Book2,
Trade2,Desk1,Book3,
Trade2,Desk2,Book2,
Trade2,Desk5,Book5,
```
4. Start AP instance.
5. Connect Atoti to remote query session using 
```
existing_session = tt.open_query_session(url="http://localhost:9090", name="Server 1", auth=tt.query.create_basic_authentication("admin", "admin"))
existing_cube= existing_session.cubes["Cube"]
```
6. Run `existing_session.visualize()`
7. Create pivot table, add a measure and include "Entity" on rows. See that we still show a value for "Count" on rows that have no value for Entity.
![image](https://user-images.githubusercontent.com/67701881/103649969-3d0ddd80-4f57-11eb-925e-6a775c19e923.png)
8. Open Property Inspector -> Advanced Tools and copy the value for `mdx`
![image](https://user-images.githubusercontent.com/67701881/103650180-8bbb7780-4f57-11eb-8e82-4bea4fdcbb99.png)
9. Paste MDX string into `session.query_mdx` method: 
```
existing_session.query_mdx("SELECT NON EMPTY {[Measures].[contributors.COUNT]} ON COLUMNS, NON EMPTY Hierarchize(Descendants({[TestingEmpties].[TestingEmpties].[AllMember]}, 4, SELF_AND_BEFORE)) ON ROWS FROM [Cube]")
```

## Actual Result

Cellset returned does not include "Count" for rows where Entity is blank.
![image](https://user-images.githubusercontent.com/67701881/103650551-22883400-4f58-11eb-8a86-8cd5e40f35a5.png)

## Expected Result
Same MDX query should return the same cellset for pivot table and using `session.query_mdx`. 

## Further Notes
I have tested this MDX query in AUI 4 as well, it returns values for the data members as well.

The following query:
```
WITH
 Member measures.DataMemberCount AS (
  [TestingEmpties].[TestingEmpties].currentmember.datamember,
  [Measures].[contributors.COUNT]
) 
SELECT
  [Measures].DataMemberCount ON COLUMNS,
  [TestingEmpties].[TestingEmpties].MEMBERS ON ROWS
  FROM [Cube]
```
Which uses the MDX `datamember` function, should show the count for all members at Entity level. In AUI 4 and 5 this returns the full cellset including data members as expected: 
![image](https://user-images.githubusercontent.com/67701881/103651658-dc33d480-4f59-11eb-9a22-7f456aad7981.png)

Yet when running this query using session.query_mdx, this returns the same reduced cellset:
![image](https://user-images.githubusercontent.com/67701881/103651757-f79edf80-4f59-11eb-8710-cdb18d25f599.png)

This is the reason I believe this is an issue with atoti.query.session.QuerySession.query_mdx and not the MDX layer in AP. If that is not the case and / or this is the intended behaviour then please let me know and I'll move this issue to the appropriate forum.

## Environment

- atoti: 0.5.0
- Python: 3.8.5
- Operating System: win32

**Comment by mwebborn-av** [comment]
Hi Fabien,

Thanks for your response & sorry for not getting back to this sooner. Is it at all possible to retain DataMember functionality in the returned cell set? If not, are there any plans to support this? I have a use case where users in the remote session prefer the flattened tables for UX reasons, but users querying with Atoti would like to return all values for further analysis.

**Comment by fabiencelier** [comment]
What pandas dataframe do you expect exactly ?

atoti does not display the subtotals and I don't think there is a way to know if it is your usecase with DataMember or a generic subtotal based on the received cellset

A workaround would be to query the cube twice: with and without the last level. You will will get 2 pandas dataframe, you can complete the second one by setting null on the "Entity" column then union the 2 dataframes.

Here is an example with a multilevel date hierarchy where I query at both the day level and month level then concat the results. It's not with DataMember but it shows how to add subtotals on higher level.

```python
df_full = cube.query(m["v.SUM"], levels=[lvl["day"]])
df_subtotal = cube.query(m["v.SUM"], levels=[lvl["month"]])

# Adding the empty column
df_subtotal["day"] = None
# Putting the new column in the index
df_subtotal = df_subtotal.set_index(['day'], append=True)

pd.concat([df_full, df_subtotal]).sort_index()
```


year | month | day|  v.SUM
--|--|--|--
2020 |  Feb |  2 | 242500.0
| | | 4 | 247500.0
| | | 6 |  252500.0
| | | 8 |  257500.0
| | | NaN | 1000000.0
| | Jan | 1 | 240000.0
| | |3 | 245000.0
| | |5 | 250000.0
| | |7 | 255000.0
| | | NaN | 990000.0

**Comment by mwebborn-av** [comment]
Your example is more or less what I was looking for, where we still include the NaN values with their associated measure. Thanks for the suggestion.

Do we receive different cellsets when using session.query_mdx() vs a pivot table using session.visualize()? Or are they the same until flattened for the pandas dataframe?

In my original example, how does the pivot table identify data members & display a Count for Books w/out Entity in Trade2?

**Comment by tibdex** [comment]
> Do we receive different cellsets when using session.query_mdx() vs a pivot table using session.visualize()? Or are they the same until flattened for the pandas dataframe?

The cellset is the same and we flatten it to return a typical DataFrame.

**Comment by tibdex** [comment]
You can use the new [`query_mdx()`'s `keep_totals` parameter](https://docs.atoti.io/0.5.2/lib/atoti.session.html#atoti.session.Session.query_mdx).
