### ISSUE TITLE
Fields cannot be widened in pivot table UI

### ISSUE THREAD

**Issue by astroungu** [atoti/atoti#206]
## Steps to reproduce

Create a text column and populate with a long string so that the string is longer that the column name e.g., "A" : "this is a very long piece of data". Display the data with a pivot table widget.

## Actual Result

The column cannot be resized to display the full string. It cannot be resized at all. The cursor never changes from a spreadsheet cross to a a resize-arrow cursor.

## Expected Result

Should be able to resize.

## Environment

atoti 0.5.0
Win10 + Chrome

**Comment by fabiencelier** [comment]
Related internal issue: [UI-5084](https://support.activeviam.com/jira/browse/UI-5084)
