### ISSUE TITLE
UX - Simulation widgets not accessible from dashboards

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#208]
## Steps to reproduce

This simulation widgets are only accessible on the landing page:
![image](https://user-images.githubusercontent.com/35210495/103880494-28c30f80-5114-11eb-9964-32ced7d1564f.png)

I focused more on the left panel to create new dashboard or access the latest dashboard (access related features), and overlooked these simulation functions (actual functional features). 

These functions are more applicable when we are working with a dashboard, it would be nice if we can also see these links on top instead.
![image](https://user-images.githubusercontent.com/35210495/103880571-45f7de00-5114-11eb-9eb4-0f33634bb719.png)
![image](https://user-images.githubusercontent.com/35210495/103881196-15647400-5115-11eb-8780-7814d42aa807.png)

## Environment
- atoti: 0.5.0
- Operating System: linux

**Comment by tibdex** [comment]
Hi Hui Fang, this is done on purpose:
- Now that the app has a home page, it's the natural place to put links to other pages such as the simulation ones.
- The elements in the header when looking at a dashboard e.g. "File" and "Edit" provide controls specific to this dashboard. Links to simulation editors are not specific to the current dashboard.
- By not putting the links to the simulation editors in the dashboard page header you don't risk losing your unsaved dashboard changes when clicking on one of these links.
