### ISSUE TITLE
Saved calculated measure not shown when I print measures in notebook

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#21]
## Description
I created a calculated measure and saved it.
(1) when I print the measure, it doesn't show. However in the Atoti Editor, it is available for selection.
Doesn't `cube.measures` contain all measures?
![image](https://user-images.githubusercontent.com/35210495/79972079-f743de80-84c7-11ea-8f93-bd2a1e353c84.png)

(2) On restart of the kernel, the saved measure is gone. Hence the cube.visualize that was built before failed with MdxException: unknown measure error.
On point 2, it is understandable since I didn't persist the db. Just thinking that users have to be aware of how the save works here.

## Reproduce
![savedCalculatedMeasure](https://user-images.githubusercontent.com/35210495/79971227-9e277b00-84c6-11ea-93aa-388311a23538.gif)

## Context
- Atoti version: Atoti 0.3.1
- Python version: 3.7.6
- Operating System: Windows 10 pro

## Logs (if relevant)
[atoti_saved_measure.log](https://github.com/atoti/atoti/files/4515505/atoti_saved_measure.log)

**Comment by tibdex** [comment]
Hi Hui Fang, indeed calculated measures are stored in the metadata DB so:
- They aren't accessible from `cube.measures` like the other measures defined in Python.
- If you don't persist the metadata DB, they are lost when the session closes.
The fix would be to not show this calculated measure editor in the extension and even in the app when we detect that the metadata DB isn't persisted. However, this is not supported in the current version of ActiveUI SDK.

**Comment by fabiencelier** [comment]
@tibdex the internal ticket has been resolved by https://github.com/activeviam/activeui/pull/4378#
