### ISSUE TITLE
Saved dashboard not available under list of dashboards

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#210]
## Steps to reproduce
I have saved a dashboard and refreshed the page. The dashboard doesn't show up under the dashboard list and can only be accessed from the Recently opened.
Is this the expected behavior?

![image](https://user-images.githubusercontent.com/35210495/104539960-89dd6c80-5659-11eb-8851-f6ee9b63bebc.png)

## Environment
- atoti: 0.5.1
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang,

The "Dashboards" section displays a list of folders when expanded. To see the list of dashboards in the root folder, you need to click on this "Dashboards" item.

**Comment by mtadams007** [comment]
Tracking this internally in this [ticket](https://support.activeviam.com/jira/browse/UI-5151).

**Comment by bloussou** [comment]
Closing this since the layout has changed in the latest release : 
![image](https://user-images.githubusercontent.com/32448554/128531731-4c250636-76e3-4bb0-9625-1cb8fd183a80.png)
