### ISSUE TITLE
Exception translating numeric string declared as int type

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#212]
## Steps to reproduce

I have a column that is passed in as a text string "1969.0" which we know is an integer.
By declaring the type as integer with `types={"birthYear": tt.type.INT}`, shouldn't it be able to cast the data? Unless the data is cannot be casted, then an exception is thrown?

Otherwise, won't it be very troublesome that users have to use Pandas or other interim object to read and cast the data before loading into datastore?

## Environment
- atoti: 0.5.1
- Python: 3.9.1
- Operating System: win32

## Logs (if relevant)

```
Jan 18, 2021 9:19:58 AM com.activeviam.health.monitor.impl.LoggingCsvHealthEventHandler onCsvLineParsingFailure
WARNING: [source, parsing, line, csv] WARNING 2021-01-18T01:19:57.064Z uptime=156487ms com.qfs.msg.csv.impl.Parser.onTranslationFailure:493 thread=csv-worker-CSVSource-1 thread_id=55 event_type=CsvLineParsingFailure CSV line parsing failed file=C:\Users\Yeo Hui Fang\AppData\Local\Temp\atoti-r33po402\playerswfkgqlf1.pdcvs file_line_number=19637 file_line=[zuberjo01, 1969.0, Jon, Zuber, Jon Zuber, Jon Edward, L, L, 1996-04-19, 1998-09-27, 1996]
com.activeviam.fwk.ActiveViamRuntimeException: Exception while translating column birthYear with parser Plugin Value (key=int, class com.quartetfs.fwk.format.impl.IntParser) in file FileSystemFileInfo [fullName=C:\Users\Yeo Hui Fang\AppData\Local\Temp\atoti-r33po402\playerswfkgqlf1.pdcvs, lastModifiedTime=Mon Jan 18 09:17:28 SGT 2021]. Parsed text was "1969.0"
```

**Comment by rcolle** [comment]
Hi Huifang,

A couple answers:
- ActivePivot parses a CSV column with the same type it's defined in its store
- "1969.0" is technically not an integer and cannot be parsed as such.

Given the amount of work required to change these points, I don't think that's something we're looking to support at the moment.
