### ISSUE TITLE
Unable to add more than 1 filter on the same level

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#213]
## Steps to reproduce
I needed to add in 2 conditions on the same level:
- players whose career is more than 10 years
- players whose HR is greater than 200

However, I'm unable to add the second condition using the editor. The same applies to the web application.

![multiple_filters](https://user-images.githubusercontent.com/35210495/104880539-b3203480-599a-11eb-8668-23657e15df63.gif)

## Environment

- atoti: 0.5.1
- Operating System: win32

**Comment by mtadams007** [comment]
Tracking this issue in this [ticket](https://support.activeviam.com/jira/browse/UI-5150)
