### ISSUE TITLE
Unable to search on multi-level hierarchy

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#214]
## Steps to reproduce
I have a hierarchy called Player which has 2 levels:
- playerID
- fullName

I have 19,646 players. You can see from the GIF:
1. the loading of the search values is slow
2. expanding the first level (playerID) is also slow
3. I cannot search by the fullName

Point 3 was my main objective and if I don't have the player ID, I do not know how I can filter by the player in this case.
![multilevel_search](https://user-images.githubusercontent.com/35210495/104883355-9fc39800-599f-11eb-9ec5-2dc1bee84c57.gif)

## Environment

- atoti: 0.5.1
- Operating System: win32

**Comment by mtadams007** [comment]
Tracking internally in this [ticket](https://support.activeviam.com/jira/browse/UI-4960)
