### ISSUE TITLE
Configurable environment variable to switch off Jupyter token authentication in atoti docker image

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#218]
## Description

Token-based authentication is on by default for notebook 4.3. 
When we run atoti on a docker image, the web application is served via a proxy.

When we try to share the dashboard that is created, the other party will be requested to enter the Jupyter token as well. So then sharing becomes complicated.

Would it be possible to provide a variable to configure the docker image (similar to the port and base_url) such that we can [disable Jupyter's authentication](https://jupyter-notebook.readthedocs.io/en/stable/security.html#alternatives-to-token-authentication)? Users can manage the security separately at different layer of the web application.

**Comment by fabiencelier** [comment]
Atoti docker image rely on the jupyterbase-notebook image
According to the [doc](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#notebook-options) it is possible to pass some jupyter command line options to the script starting the container.

You can leverage this to disable or change the authentication:

```
 docker run -p 8888:8888 atoti/atoti start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
```

Note that I would never recommend exposing Jupyter lab without security as it gives access to the underlying machine.

Another solution is to keep the token on Jupyter lab and expose the atoti application on an other public port.

**Comment by tibdex** [comment]
I would prefer not adding an official option to our Docker image to enable something that is considered a bad practice. You can follow Fabien's advice or extend our Docker image to suit your needs.
