### ISSUE TITLE
Impossible to put constants as output measure in filters 

### ISSUE THREAD

**Issue by rackhaml** [atoti/atoti#22]
## Description

It is currently impossible to create a measure with `atoti.filter` using a constant as the output. I instead have to create a constant measure, and then filter on it : 
`m["example"] = tt.filter(1.0, condition)` 
will raise a ValueError
While :
`m["one"] = 1.0`
`m["example"] = tt.filter(m["one"], condition)` 
will produce the desired output correctly. 

## Context

I'm trying to create a measure that can take values according to different (4) formulas depending on conditions on other levels. Therefore, I created 4 filtered measures, one for each formula and added them to create the desired measure. Two of these formulas are just constants (1.0 and -1.0 ).

## Other information (if relevant)

Constants can be used in `atoti.where`, so I could also use several layered `atoti.where` to get the desired measure.

**Comment by bloussou** [comment]
This will be supported in the next release.
