### ISSUE TITLE
cube querying without measures

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#220]
## Steps to reproduce

Is it right that the whole datastore is returned if I query only levels, without any measures?

![image](https://user-images.githubusercontent.com/35210495/105123815-bc80dc80-5b13-11eb-859a-b1d7af5b763a.png)

## Environment
- atoti: 0.5.1
- Python: 3.9.1
- Operating System: win32

**Comment by tibdex** [comment]
This is probably not the "entire datastore" and it's also [the documented behavior](https://docs.atoti.io/0.5.1/lib/atoti.html#atoti.cube.Cube.query):

> measures: The measures to query. If None, all the measures are queried.

I agree that this is probably not the most sensible default but changing it would be a breaking change so it will have to wait a bit.
