### ISSUE TITLE
Column header is not showing for pivot tables without measures

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#221]
## Steps to reproduce

Column header does not appear for the pivot table without measures.

![pivot table without measures](https://user-images.githubusercontent.com/35210495/105124397-0a4a1480-5b15-11eb-882f-896a156a3bac.gif)

## Environment
atoti: 0.5.1
Operating System: win32

**Comment by DavidLangva** [comment]
Hello, UI is now tracking this with the following ticket https://support.activeviam.com/jira/browse/UI-5195?filter=-3
