### ISSUE TITLE
Can't start any notebook with atoti 0.5.2 continuous build

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#222]
1. Using https://docs.atoti.io/latest/install_conda.html, I ran "conda install atoti atoti-jupyterlab python" today
2. When I start jupyter lab and I open a notebook (any notebook), the kernel can't start and I have an error message
3. I tried with "conda install atoti atoti-jupyterlab" and same error

## Actual Result
![image](https://user-images.githubusercontent.com/42935528/105469136-c13fbf00-5cd2-11eb-88aa-5058646c6878.png)

## Environment
Can't run that !

- atoti: 0.5.2.20210120182813-5a1ea20
- Python:
- Operating System: Windows 10

## Logs (if relevant)

[log_atoti_0_5_2_start.txt](https://github.com/atoti/atoti/files/5854589/log_atoti_0_5_2_start.txt)

**Comment by tibdex** [comment]
Hi Xavier, first please note that this is not "atoti 0.5.2", it's the current latest internal build on the road to the 0.5.2.

I just tried the commands you ran and I couldn't reproduce the issues even though I had the same versions of `atoti`, `atoti-jupyterlab`, `jupyterlab-server`, `jupyter-server`, and `jdk4py`.

- Did you change something on your set up between the last successful conda env and this one?
- In the logs you shared you can see a stack-trace that has nothing to do with atoti. Can you try just doing `conda install jupyterlab python` and see if you still have the issue (in which case it's not an atoti issue)?

**Comment by xpilasav** [comment]
Indeed it's not related to atoti: same error with just jupyterlab and python
I checked with Harold, it is not only on my environment but his too then it's something with the current set of dependencies. All my previous install of atoti works, only the latest one has this issue.
Closing the ticket

**Comment by xpilasav** [comment]
Found the reason of the problem:
https://github.com/jupyter/notebook/issues/3556
Fix the file <conda env>\share\jupyter\kernels\python3\kernel.json to update with the correct path for Python bin
