### ISSUE TITLE
folder structure looks funny when using open_query session and inline viz

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#224]
Hello!

The folder structure does not show as in the Atoti+ app I'm connecting from a Jupyter Notebook. It is flat and names contain paths:

In atoti inline dataviz:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/37184538/105760713-09dfbe00-5f07-11eb-9b47-57c727f7c244.png">

In the source app:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/37184538/105760788-1c59f780-5f07-11eb-99bc-390f49eb6d7f.png">

## Steps to reproduce

```
# import atoti
import atoti as tt

# connect to FRTB

existing_session = tt.open_query_session(
    'http://{url}:{port}/frtb-starter',
    auth=tt.query.create_basic_authentication("login", "password")
)
```

## Environment

- atoti: 0.5.0.1824.20201208171122
- Operating System: darwin

**Comment by tibdex** [comment]
Hi Anastasia, I can't reproduce with a simple example. When I change the `.folder` attribute of a measure in Python, I get the right display in the JupyterLab extension sidebar.

Can you share a small notebook from which I can reproduce the issue?

Thanks

**Comment by tibdex** [comment]
Closing this since we still cannot reproduce the problem.
