### ISSUE TITLE
cube.schema malfunction with real-time datasource

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#225]
## Steps to reproduce
Referring to the notebook gallery use case - [Real-time Risk](https://github.com/atoti/notebooks/blob/master/notebooks/real-time-risk/main.ipynb), the `cube.schema` changes with the real-time data feed.

![cube_schema](https://user-images.githubusercontent.com/35210495/105788263-1a517080-5fbb-11eb-83d2-81c8342a16ca.gif)

## Environment

atoti: 0.5.1
Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, this is not an atoti issue. Regardless of the content of the cell, be it `cube.schema` or `True`, you'll get the output of your threads appear in that cell.
