### ISSUE TITLE
Add map charts

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#226]
## Description

It would be nice to have the point map or [other nice plotly maps](https://plotly.com/javascript/scatter-plots-on-maps/) added to atoti v0.5.

We used it for the [geoPricing notebook](https://github.com/atoti/notebooks/blob/master/notebooks/geopricing/main.ipynb) in notebook gallery.
![image](https://user-images.githubusercontent.com/35210495/105795530-f8aab600-5fc7-11eb-91da-3d228eb1fb9a.png)

**Comment by tibdex** [comment]
Hi Hui Fang, I agree there are useful but adding map charts is not planned for now.
