### ISSUE TITLE
einsum implementation

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#228]
## Description

Could you implement this function?
https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
https://mathworld.wolfram.com/EinsteinSummation.html

## Context

This is used in a Credit Risk context.
I am still waiting for more specifications from the user.

**Comment by tibdex** [comment]
Hi Harold, this function seems a bit too generic for a multidimensional analysis tool like atoti. You can reopen another issue once you have more specific requirements in mind.
