### ISSUE TITLE
Dashboard onboarding instructions

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#229]
## Description

We used to have the text widget in atoti web application. We use it to provide instructions on how to interact with the dashboards.
Would there be plans to bring back the text widget or have something equivalent to display the onboarding instructions?

**Comment by DavidLangva** [comment]
UI team is now tracking this request with the following internal ticket https://support.activeviam.com/jira/browse/UI-5219

**Comment by bloussou** [comment]
Hi, we are not sure this is something needed in atoti. If the user is coming from a notebook we think the notebook is the place for explanation not the dashboard. Explicit title and dashboard names should be enough to get the goal of a dashboard. If this one is really complicated maybe a GIF can explain how to use it better than a text. AUI team is thinking of a better way to handle this need, maybe with comments.

**Comment by HuifangYeo** [comment]
Notes within the notebook are meant for users with coding capabilities whereas this request is intended toward end-users of the UI, i.e. non-coding users who probably didn't know the existence of the notebook. This being said, it is indeed more of a UI ticket than atoti ticket. And indeed, a text widget may not be the best way to manage these. Perhaps annotation on widgets or something else.
