### ISSUE TITLE
Not clear how to load multiple csv files with a pattern

### ISSUE THREAD

**Issue by SBrown52** [atoti/atoti#230]
## Description

Hi, I have the following project structure:

-> main.py
-> data
-> data/trades1.csv
--> data/trades2.csv
--> data/trades3.csv etc etc

I want to load all of the trades*.csv files into atoti. There may be other files in the directory which need to be loaded into separate stores.

I read the [doc](https://docs.atoti.io/latest/lib/atoti.html#atoti.store.Store.load_csv) but it is not clear on how to do this.

I have tried the following:
```
import atoti as tt

session = tt.create_session();
store = session.read_csv("data/**/trades*.csv")

print(store.head(5))
```
which errors with 
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'data\\**\\trades*.csv'`

I have also tried the following combinations and always get an error message.

```
session.read_csv("/**/data/trades*.csv")
session.read_csv("data/trades*.csv")
session.read_csv("**/data/trades*.csv")
```

Could you consider updating the doc or tutorial to cover this use case.

Thanks

**Comment by bloussou** [comment]
Hi @SBrown52,
Thanks for your issue. This will be fixed in the next release thanks to https://github.com/activeviam/atoti/pull/1977.
