### ISSUE TITLE
Clustered Column Charts: same color for split measures

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#231]
## Steps to reproduce

When multiple charts are added to the Clustered Columns chart, there's no color differentiator for the 2.

![multi_measure_chart](https://user-images.githubusercontent.com/35210495/106833196-19f95980-66ce-11eb-8bfe-ffa198ac5f6c.gif)

## Environment
- atoti: 0.5.1
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, there should be a `Measures` tile in the _Split by_ section. Can you take a look at [this gitter thread](https://gitter.im/atoti/atoti?at=6012a77084e66b7f7eb6e494) and see if it's the same root cause?

**Comment by HuifangYeo** [comment]
Hi Thibault, yes I think it's the same issue. As you can see in the GIF, there's no `Measures` tile.
