### ISSUE TITLE
cube.visualize() or session.visualize()??

### ISSUE THREAD

**Issue by SBrown52** [atoti/atoti#235]
The doc is wrong and includes both (in 0.5.1 doc). I think the method changed to session.visualize() and has not been properly updated. 

![image](https://user-images.githubusercontent.com/9969195/106910735-6c9c3b00-66f9-11eb-9c62-24f93b91db2a.png)

**Comment by tibdex** [comment]
Thanks Sam, this will be fixed in the next release.
