### ISSUE TITLE
Cannot access legacy app

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#236]
## Steps to reproduce

1) Create a new conda environment with conda install atoti-plus=0.5.1 atoti-jupyterlab=0.5.1 python
2) Due to a kernel issue, update "C:/Users/<user>/.conda/envs/miscellaneous/bin/python" to "C:/Users/<user>/.conda/envs/miscellaneous/python"
3) Start jupyter lab
4) Via a terminal (inside the lab), run pip install atoti-legacy-app
5) Run the notebook
6) Try to access http://localhost:xxxx/legacy/

```python
import atoti as tt
import pandas as pd

data = [
    ['Trade A', 10.0],
    ['Trade B', 20.5]
]
df = pd.DataFrame(data, columns=['Trade', 'Delta'])

session = tt.create_session()
store = session.read_pandas(df, store_name='BaseStore', keys=['Trade'])
cube = session.create_cube(store, name='Cube')

session.url
```

![condaList](https://user-images.githubusercontent.com/7359377/107495172-03507800-6b90-11eb-92e8-b0bd149faf0b.PNG)

## Actual Result
HTTP 404

## Expected Result
Legacy App

## Environment
- atoti: 0.5.1
- Python: 3.9.1
- Operating System: win32

**Comment by Skyscimitar** [comment]
It's possible the error is due to the fact you installed atoti with `conda` and the plugin with `pip`, could you try uninstalling the plugin installed with `pip` and then `conda install atoti-legacy-app`

**Comment by rcolle** [comment]
The problem could also come from the fact that you're installing it from within the terminal.
For instance: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

It'd be better to install it via conda in the conda terminal.

**Comment by fabiencelier** [comment]
The issue can also be that you did not restart the kernel after the install.

If the package is correctly installed you should be able to import it with `import atoti_legacy_app`

**Comment by Harold7665** [comment]
Hello,

Thank you for your answers.
I have tested this `conda install atoti-plus=0.5.1 atoti-jupyterlab=0.5.1 atoti-legacy-app python` without success.

![legacy](https://user-images.githubusercontent.com/7359377/107498349-f766b500-6b93-11eb-9d55-617963ebfb43.PNG)

**Comment by tibdex** [comment]
It's http://localhost:xxxx/legacy/ (the trailing `/` is important) as documented:

<img width="887" alt="Screen Shot 2021-02-10 at 11 43 20" src="https://user-images.githubusercontent.com/6574550/107499448-44975680-6b95-11eb-8ec2-524fcab8f1b5.png">

**Comment by Harold7665** [comment]
Oh in fact, it works! Thank you!
