### ISSUE TITLE
Provide an API for querying directly from the datastore of an existing ActivePivot instance.

### ISSUE THREAD

**Issue by rupesh001** [atoti/atoti#24]
## Description
Provide an API for querying directly from the datastore of an existing ActivePivot instance.

## Context
I want to use the data from existing data stores in my notebook, for doing some analysis.

## Other information (if relevant)
use case is to get data from a datastore and update the mdx based on that data, before querying the cube.

**Comment by SBrown52** [comment]
ActiveViam used to provide a python library (think it was from an intern), which allowed you to connect to a remote AP datastore, query it, and return a pandas dataframe. It was useful to query the datastore like this

**Comment by tibdex** [comment]
Hi Rupesh, this is not planned.

**Comment by tibdex** [comment]
We plan to do #23 which could allow to get back datastore facts too. If you really need direct access to the datastore you can also use the existing REST API.
