### ISSUE TITLE
How to set ATOTI_HIDE_EULA_MESSAGE

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#240]
## Description
Hello, I did not find a better way to set this ATOTI_HIDE_EULA_MESSAGE variable, is there one?

![ticket_ATOTI_1](https://user-images.githubusercontent.com/7359377/107777443-20797800-6d43-11eb-9474-ee0a60301052.PNG)

**Comment by tibdex** [comment]
Since it looks like you're on Windows, you could use [the dedicated Control Panel UI](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/) for that.

**Comment by Harold7665** [comment]
Oh thanks! In fact this is a good way. I did not understand that the variable was related to the OS environment instead of the conda environment.

**Comment by Harold7665** [comment]
Looking at the message, this is still ambiguous on my opinion: **You can hide this message by setting the ATOTI_HIDE_EULA_MESSAGE environment variable to True**.

Because there are conda enrivonment variables:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#:~:text=Setting%20environment%20variables,-If%20you%20want&text=To%20list%20any%20variables%20you,%3A%20conda%20activate%20test%2Denv%20.

**Comment by tibdex** [comment]
The link to the Conda docs you shared is to interact with environment variables that are only visible inside the current Conda environment. They are still environment variables. If you use them correctly, it would have worked as expected:

```bash
~ 
❯ echo $FOO

~ 
❯ conda activate my-env

~ via 🅒 my-env 
❯ echo $FOO

~ via 🅒 my-env 
❯ conda env config vars set FOO=bar
To make your changes take effect please reactivate your environment

~ via 🅒 my-env 
❯ echo $FOO

~ via 🅒 my-env 
❯ conda activate my-env

~ via 🅒 my-env 
❯ echo $FOO
bar

~ via 🅒 my-env 
❯ python
>>> import os
>>> os.environ["FOO"]
'bar'

~ via 🅒 my-env took 11s 
❯ conda deactivate

~ 
❯ echo $FOO

~ 
❯ 
```

Do you still think the message is ambiguous?

**Comment by Harold7665** [comment]
No, not anymore, thank you for the clarification!
