### ISSUE TITLE
Sort action is missing in JupyterLab

### ISSUE THREAD

**Issue by veonua** [atoti/atoti#244]
## Description

Sort table columns feature is absent in JupyterLab,
In the app, it is present via context menu for _some_ cases.

Please add a triangle sign to the end of column name.

## Context

A pretty common feature available for decades, but I don't see any way to do it in atoti.

## Other information (if relevant)

Please add the triangle to the column titles everywhere.

**Comment by tibdex** [comment]
Indeed, this should be fixed in the next release.

**Comment by HuifangYeo** [comment]
Hi @tibdex, do we have any rough idea when the next version will be released?

**Comment by tibdex** [comment]
Hi @HuifangYeo, probably this week.
