### ISSUE TITLE
Disable global context menu items when some cells are selected

### ISSUE THREAD

**Issue by veonua** [atoti/atoti#245]
## Description

![image](https://user-images.githubusercontent.com/1540142/108203319-a2dab100-7122-11eb-90d3-503694734b26.png)

+ Copy value
+ Copy row

Also, it would be nice to allow text selection to be able to copy parts of long values

## Other information (if relevant)

"Copy query to the clipboard", Refresh and Export may be moved to the global menu, 
as it does not belong to the selected cell context

As it will export the whole dataset not only selected rows.

**Comment by tibdex** [comment]
If've created an [internal ticket](https://support.activeviam.com/jira/browse/UI-5357) about that. We'll keep you posted ;).

**Comment by tibdex** [comment]
Closing this as the internal ticket has been postponed.
