### ISSUE TITLE
Deferred Updates have been cancelled warning

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#25]
## Description
I created a pivot table with "Deferred update" selected. 
I created a new measure and added to the pivot table. The "Deferred update" checkbox got removed and when I tried to adjust the column width, a lot of warnings on the "Deferred updates have been cancelled" are displayed.

![image](https://user-images.githubusercontent.com/35210495/80338457-f1b31380-888e-11ea-93f6-a2159b9e518e.png)

Refer to 
[localhost-1587967183971.log](https://github.com/atoti/atoti/files/4537747/localhost-1587967183971.log)

## Context
- Atoti version: v0.3.1
- Browser: Chrome
- Operating System: Windows 10 Pro

**Comment by tibdex** [comment]
Hi Hui Fang, the state of deferred updates is kept by the editor component in the sidebar so if you close the sidebar or your widget loses focus, that state is gone. That's what happen when you go back to a Python cell to create new measures.

The same behavior can be seen in the app if you go, for instance, from the "Content Editor" to the "Dashboards" sidebars and back.

Until this is changed in ActiveUI SDK, you'll have to finish your updates and submit them before leaving the Content Editor.

**Comment by tibdex** [comment]
Since atoti 0.5.0, deferred updates are implemented differently in the app so the issue doesn't happen anymore there.

In the next release, you'll get back a "Defer updates" checkbox in the JupyterLab sidebar and it won't suffer the problem detailed here.
