### ISSUE TITLE
Documentation Enhancement for Links

### ISSUE THREAD

**Issue by isobelbyrne** [atoti/atoti#250]
## Description

Open links on separate tab.

## Context

Currently when a link is provided, usually pointing towards documentation, the link will open automatically on your current window/tab. It would be more convenient for the user if the link automatically opened in a separate tab preventing the page you were previously working on from being lost.

## Example

![image](https://user-images.githubusercontent.com/79532890/109482615-2034e880-7a76-11eb-9392-b34ae2fbcb61.png)
 When you click on the link it will override your current window.

**Comment by tibdex** [comment]
Hi, indeed this is similar to #194 for which we made the move of making the link open in a new tab automatically. We should be consistent and do it here too. Have you seen other links in the app that open in the current tab?

**Comment by isobelbyrne** [comment]
Not off the top of my head - I will keep an eye out and update on here if I do.

**Comment by tibdex** [comment]
This has been fixed in 0.5.2.
