### ISSUE TITLE
https dashboard connexion

### ISSUE THREAD

**Issue by annegruz** [atoti/atoti#256]
Hello,
I would like to test atoti on an Iliade Scaleway server through a secure connection.
We managed to configure HTTPS on the cloud server by following [this guide](https://ernie55ernie.github.io/python/2019/03/24/setup-a-jupyter-notebook-server-with-https.html).
However, https://163.172.152.118:40750/#/ doesn't work.
Thanks for your help.

**Comment by tibdex** [comment]
Hi,
In your first version of this issue you said you were getting the message:

> This CA Root certificate is not trusted because it is not in the Trusted Root Certification Authorities store

This sounds like a [self-signed certificate problem](https://webmasters.stackexchange.com/questions/130287/where-is-the-trusted-root-certification-authorities-store-located) not related to atoti.

If you try to deploy a basic Flask or FastAPI app on this server with HTTPS configured too do you have the same error?

**Comment by annegruz** [comment]
Hello,

The certificate issue is fixed: I can access JupyterLab via a secured https:// request using encrypted communication. 
Atoti's session url built using the same domain does not work though.

Is this supported?
Thank you for your help.

Anne

**Comment by tibdex** [comment]
atoti runs it own server on a port different than the one from Jupyter Server. To access the atoti session through HTTPS you can either:

- Use [Jupyter Server Proxy](https://github.com/jupyterhub/jupyter-server-proxy) to access the atoti session through Jupyter Server (you can then update the `url_pattern` part of the config accordingly).
- Configure HTTPS directly on the atoti session: look at the [`https` parameter of `create_config`](https://docs.atoti.io/0.5.2/lib/atoti.config.html#atoti.config.create_config).

**Comment by annegruz** [comment]
Thank you. Do these solutions require Atoti+?

**Comment by tibdex** [comment]
The second one yes.
