### ISSUE TITLE
Data Querying Documentation

### ISSUE THREAD

**Issue by TasneemAhmed** [atoti/atoti#258]
import atoti as tt
the problem is : ModuleNotFoundError: No module named 'atoti'

I installed atoti through python and conda package and this error still there.

**Comment by tibdex** [comment]
Hello, this issue is not clear enough. Can you provide more details and update the title to make it match the description?

> I installed atoti through python and conda package

You need to pick one of the installation ways: either Python package or Conda package, not bot.
