### ISSUE TITLE
Have a color scheme for all widgets on the same page or the same dashboard

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#262]
## Steps to reproduce

In atoti 0.4.3, we have access to the state editor and we can use plotly config to setup colors
In atoti 0.5.2, we don't have the state editor and nothing else is provided to setup a color scheme

## Actual Result

N/A

## Environment

- atoti: 0.5.2
- Operating System:
- Browser:

**Comment by tibdex** [comment]
Indeed there are currently no built-in state editor in ActiveUI 5.

However, the state of the widget can be accessed:
- In JupyterLab: in the metadata of the corresponding notebook cell.
- In `f"{session.url}/content"`.

**Comment by xpilasav** [comment]
Thank you, good idea but in this particular user case, it really has to be done on the UI.
Can we expect the state editor in the next atoti version?

**Comment by tibdex** [comment]
> Can we expect the state editor in the next atoti version?

Probably not as it's not a high priority for the UI team.

**Comment by bloussou** [comment]
Hello,
Isn't this solved with an `app_extension` adding the [drawerStateEditor](https://activeviam.com/activeui/documentation/5.0.7/docs/api/variables#drawerstateeditor) or [drawerStyleEditor](https://activeviam.com/activeui/documentation/5.0.7/docs/api/variables#drawerstyleeditor) ?

**Comment by bloussou** [comment]
You can refer to this internal ticket https://github.com/activeviam/atoti/issues/3148 top use the bd template

**Comment by xpilasav** [comment]
Yes, all good
