### ISSUE TITLE
[Remote Cluster Ressources] - Dask

### ISSUE THREAD

**Issue by NickFillot** [atoti/atoti#264]
## Description

Not essential feature since the actual framework seems to be complete, but a bonus

Create Stores based on dask dataframes (https://dask.org/) or delayed dask functions

## Context

Communicate with remote cluster like YARN, or CUDA (dataframes stored on GPUs) to adapt to more big data infrastructures through dask or other frame work (faster than spark which takes time to create session)

**Comment by tibdex** [comment]
Indeed, at the moment we don't have specific `read_dask()`/`load_dask()` methods. We might add some in the future but in the meantime you can [write the Dask DataFrame in a Parquet file](https://docs.dask.org/en/latest/dataframe-best-practices.html#store-data-in-apache-parquet-format) and use `session.read_parquet()`.

**Comment by NickFillot** [comment]
Yes it works indeed, but I see good application opportunities considering atoti as a cluster scheduler too which could lift up this tool
