### ISSUE TITLE
[Data Loading] Thread safe ?

### ISSUE THREAD

**Issue by NickFillot** [atoti/atoti#267]
## Description

I would like to know if you would recommend parallel read to load a cube I don't see any Lock in python part, didn't check Java

Regards
Nicolas

**Comment by tibdex** [comment]
Hello, we don't recommend calling `load_*` methods in multiple Python treads. Each call will try to acquire a lock on the stores so it wouldn't help to call them concurrently.

What motivates you to try to do that? Are you facing performance issues?

**Comment by NickFillot** [comment]
There are no problem, I'm trying to distribute data over a cluster to reduce memory consumption but need synchronise data before ingesting it in a cube
