### ISSUE TITLE
Broken endpoints when combining 0.5.2 CS with 0.5.3 atoti

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#268]
## Steps to reproduce
- Download the attached ZIP: [environment.zip](https://github.com/atoti/atoti/files/6366643/environment.zip).
- Run create_0_5_2.bat.
- Run start.bat
- Run the notebook 0_5_2 (it creates the CS).
- Go to http://localhost:40750/legacy/.
- Create and save an empty dashboard.
- Kill the process created by start.bat.
- Run update_0_5_3.bat.
- Run start.bat.
- Run the notebook 0_5_3, all the endpoints are available until you run the cell session.create_cube.

## Actual Result
Server is broken, can not access it from ActiveUI or session.visualize. After several tests, this only happens if atoti-legacy-app is installed in 0.5.2 then updated in 0.5.3 ; and only if in 0.5.2, you have created a dashboard from ActiveUI 4.

## Expected Result
Access to all endpoints and ActiveUI 4 and 5.

**Comment by bloussou** [comment]
Hello,
Can we close this as there were no updates for a while and these versions are long outdated ?

**Comment by Harold7665** [comment]
Hello,
Yes we can. The legacy app has no usage anymore, and even an external custom UI may be useless thanks to the customizing way you have added.
Thanks.
