### ISSUE TITLE
Will atoti work with Jupyter R Kernel in the future ? 

### ISSUE THREAD

**Issue by philibe** [atoti/atoti#272]
Hello. 

I didn't know atoti until I've seen it today on LinkedIn. I know very well R, I use also Jupyter, and for years I've worked in the BI. Therefore I thought about the feature request below. 

Will atoti work with Jupyter R Kernel in the future ? 

- in a R standalone distribution  for Jupyter R Kernel ?  
- via reticulate in Jupyter R Kernel?

**Comment by tibdex** [comment]
Hello,

atoti is a Python library and for now there is no plan to port it to R. I never tried R's `reticulate` so I can't say if that would work with atoti.

Just out of curiosity what do you like in R that you find missing from the Python ecosystem?

**Comment by philibe** [comment]
Thanks for you answer.

All Python datas can be in theory read via `reticulate`. But it seems more complex for atoti because it is for a part a front web project, isn't it ?

To answer to "why R ?" : I work in a laboratory of a food supplier which already had an R ecosystem for years.

**Comment by rcolle** [comment]
Hi,
Thank you for all the details. There is currently no plans to integrate atoti with a R kernel, as there is already a lot to do to support the Python ecosytem!
Cheers,
Romain
