### ISSUE TITLE
TypeError when importing atoti with Python 3.8.10 and 3.9.5

### ISSUE THREAD

**Issue by adamxyzxyz** [atoti/atoti#274]
When I run import atoti, I get the following error:

TypeError: cannot inherit frozen dataclass from a non-frozen one

**Comment by tibdex** [comment]
Hi, so that we can help you, please share:
- your version of Python
- which OS you are using
- the version of atoti you tried to install
- the traceback of the `TypeError` you're getting

**Comment by adamxyzxyz** [comment]
Hello,

-Python 3.9 (64 bit)
-Windows 10
-version 
traceback:

TypeError                                 Traceback (most recent call last)
<ipython-input-1-ca53cc2997b2> in <module>
----> 1 import atoti

~\desktop\mechenv\lib\site-packages\atoti\__init__.py in <module>
      5     _compatibility,  # pylint: disable=redefined-builtin; Import first to fail fast
      6 )
----> 7 from . import (
      8     _functions,
      9     agg,

~\desktop\mechenv\lib\site-packages\atoti\_functions\__init__.py in <module>
      1 # pylint: disable=redefined-builtin
      2 
----> 3 from .date import date_diff
      4 from .measure import filter, rank, value, where
      5 from .multidimensional import _first, _last, at, date_shift, parent_value, shift, total

~\desktop\mechenv\lib\site-packages\atoti\_functions\date.py in <module>
      6 from typing_extensions import Literal
      7 
----> 8 from .._measures.calculated_measure import CalculatedMeasure, Operator
      9 from ..measure import Measure, MeasureConvertible, _convert_to_measure
     10 

~\desktop\mechenv\lib\site-packages\atoti\_measures\calculated_measure.py in <module>
      5 
      6 from ..measure import Measure
----> 7 from ..scope._utils import LeafLevels
      8 from .utils import convert_measure_args
      9 

~\desktop\mechenv\lib\site-packages\atoti\scope\__init__.py in <module>
      1 from typing import Optional, Tuple, Union
      2 
----> 3 from atoti.hierarchy import Hierarchy
      4 from atoti.level import Level
      5 

~\desktop\mechenv\lib\site-packages\atoti\hierarchy.py in <module>
      5 from typing import TYPE_CHECKING, Any, Callable, Mapping
      6 
----> 7 from ._base._base_hierarchy import BaseHierarchy
      8 from .level import Level
      9 

~\desktop\mechenv\lib\site-packages\atoti\_base\_base_hierarchy.py in <module>
      5 from .._bitwise_operators_only import BitwiseOperatorsOnly, IdentityElement
      6 from .._docs_utils import HIERARCHY_ISIN_DOC, doc
----> 7 from .._hierarchy_isin_conditions import (
      8     HierarchyIsInCondition,
      9     create_condition_from_member_paths,

~\desktop\mechenv\lib\site-packages\atoti\_hierarchy_isin_conditions.py in <module>
     14 
     15 @dataclass(frozen=True)
---> 16 class HierarchyIsInCondition(Condition, MeasureConvertible):
     17     """Class for isin condition on cube hierarchies."""
     18 

C:\Program Files\Python39\lib\dataclasses.py in wrap(cls)
   1011 
   1012     def wrap(cls):
-> 1013         return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
   1014 
   1015     # See if we're being called as @dataclass or @dataclass().

C:\Program Files\Python39\lib\dataclasses.py in _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
    896         # Raise an exception if we're frozen, but none of our bases are.
    897         if not any_frozen_base and frozen:
--> 898             raise TypeError('cannot inherit frozen dataclass from a '
    899                             'non-frozen one')
    900 

TypeError: cannot inherit frozen dataclass from a non-frozen one

**Comment by tibdex** [comment]
I have the same issue with Python 3.8.10 that was released the 2021-05-03 (same day as atoti 0.5.4). [This is new CPython code](https://github.com/python/cpython/pull/24484/files) leading to an error being raised.

While we look for a solution, you can try with Python < 3.8.10.

**Comment by adamxyzxyz** [comment]
So use an older version of python for now for it to work?

**Comment by tibdex** [comment]
atoti [0.5.5](https://docs.atoti.io/0.5.5/releases/0.5.5.html) has just been released to fix this issue. You can try again with Python 3.8.10.
