### ISSUE TITLE
Branding is not working with ActiveUI 5

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#275]
## Steps to reproduce
```python
import atoti as tt
import pandas as pd

session = tt.create_session(
    name='Main session',
    config=tt.config.create_config(
        branding=tt.config.create_branding(
            accent_color='rgb(0,128,0)',
            favicon='./grwa_logo.ico',
            frame_color='rgb(0,128,0)',
            title='Test - #####'
        )
    )
)

data = [
    ['Trade 1', 20]
]
df = pd.DataFrame(data, columns=['Trade ID', 'Delta'])

store = session.read_pandas(df, keys=['Trade ID'], store_name='Store')
cube = session.create_cube(store)

session.url
```

## Actual Result
Only the favicon is modified according to the branding configuration.

## Expected Result
I should also see the new title and the new accent and frame colors.

## Environment
- atoti: 0.5.4
- Operating System: win32
- Browser: GoogleChrome

**Comment by tibdex** [comment]
Thanks for the clear issue Harold. On my side the colors are indeed not being picked up but the favicon and titles are working.

**Comment by Harold7665** [comment]
In fact the favicon is working well.
Maybe I don't look at the right place to find the title, could you indicate me where it is displayed?
