### ISSUE TITLE
Support JDBC databases for `metadata_db`

### ISSUE THREAD

**Issue by bloussou** [atoti/atoti#277]
Hi,
To easily deploy atoti using stateless cloud services in would be nice that `metadata_db` supports JDBC. (see [gitter message](https://gitter.im/atoti/atoti?at=609e46b701edef5b5044341e)).

**Comment by rcolle** [comment]
I'd say we're actually not far from supporting it (given that we use a jdbc connection string to setup the h2 database).

The only thing that we probably need to do is to include the necessary drivers, but they are already provided by `atoti-sql`. So maybe simply removing the check and making sure that `atoti-sql` is installed might be enough. To be tested.

**Comment by tibdex** [comment]
[Available in atoti 0.6.0](https://docs.atoti.io/0.6.0/lib/atoti.config.user_content_storage.html#atoti.config.user_content_storage.UserContentStorageConfig).
