### ISSUE TITLE
First trace of horizontal plot with measure simulation displayed on the wrong chart

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#278]
## Steps to reproduce
![image](https://user-images.githubusercontent.com/35210495/118936680-53a15800-b97f-11eb-90c1-1d62248df830.png)

I'm missing the 2021 trace on the Covid plot. It's appearing in the base plot.

Please see attached notebook.
[world-population.zip](https://github.com/atoti/atoti/files/6513768/world-population.zip)

## Environment
- atoti: 0.5.5
- Operating System: win32

**Comment by HuifangYeo** [comment]
Hi Thibault, I'm using Chrome too. Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by bloussou** [comment]
Closing this as there has been no updates for more than 6months and the issue cannot be reproduced with the latest `world population` notebook.
