### ISSUE TITLE
Aggregation done on the wrong origin

### ISSUE THREAD

**Issue by rackhaml** [atoti/atoti#28]
## Description

This bug happened when I tried to use several aggregations on different levels of origin consecutively. A first aggregation is used to sum my measure on a certain level. I then use a filter in order to get their cross product on the next level. Then I try to sum the crossed products on the top level, but instead get the sum on the bottom level, which is innacurate. 

## Reproduce

Here I reproduced the bug:
[bug_agg_origin.zip](https://github.com/atoti/atoti/files/4550204/bug_agg_origin.zip)

![bug_origin](https://user-images.githubusercontent.com/60781982/80569972-44f5a500-89fa-11ea-81b1-0bb550e0c9d6.png)

## Context

- Atoti version: 0.3.1
- Python version: 3.7.6
- Operating System: Windows 10 , 64 bits

**Comment by fabiencelier** [comment]
This is a similar issue to what happens in #17 in this comment: https://github.com/atoti/atoti/issues/17#issuecomment-615317343

The issue is that the `filter` adds an additional "required level" (the level filtered on) that is then added to your origin scope when aggregating.

**Comment by fabiencelier** [comment]
This issue will be solved in the next release
