### ISSUE TITLE
AttributeError: 'Cube' object has no attribute 'visualize'

### ISSUE THREAD

**Issue by ManiKumarB** [atoti/atoti#280]
AttributeError: 'Cube' object has no attribute 'visualize' in atoti
I am facing issue on the latest version(i.e. 0.5.5)
Could you please help me to solve this..

**Comment by bloussou** [comment]
Hi,
Indeed `visualize` is available on `Session` instance not `Cube`. You can use `session.visualize()`

**Comment by ManiKumarB** [comment]
Got it thank you
