### ISSUE TITLE
Error reading csv from folder pattern when there is a parenthesis in the path

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#285]
## Steps to reproduce

Here is the code to reproduce.

```
import atoti as tt
import pandas as pd
import os

os.mkdir("error_folder(1)")
os.mkdir("working_folder")

df = pd.DataFrame(
    {
        "l1": ["a", "b", "c", "d"],
        "m1": [1,2,3,4]
    }
)
df.to_csv("error_folder(1)/test.csv", index=False)
df.to_csv("working_folder/test.csv", index=False)
session = tt.create_session()
store_csv_folder_working = session.read_csv("working_folder/", store_name = "folder_working")
store_csv_file_working = session.read_csv("error_folder(1)/test.csv", store_name = "file_working")
# If there is a parenthesis on the folder name it creates an error
store_csv_folder_error = session.read_csv("error_folder(1)/", store_name = "folder_error")
```
The last store will throw an error because it is not finding any csv files inside it because there is a parenthesis on the folder pattern.

## Environment

- atoti: 0.5.5
- Python: 3.8.10
- Operating System: win32

**Comment by bloussou** [comment]
Hello,
It will be fixed in the next release. To prepare the next breaking release I advice you to use explicit glob path (folders won't be supported anymore for CSVs):
`session.read_csv("working_folder/**.csv", store_name = "folder_working")`

**Comment by alexis-bvq** [comment]
ok thanks for the teasing ;)
