### ISSUE TITLE
Performance of atoti's JupyterLab extension search feature

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#286]
## Steps to reproduce

I have about 100k rows in my dataset. When trying to search for a player, it takes a while for the search to return.
Selecting the checkbox also takes a while for it to appear selected. The button to submit the search also takes a while to get submitted.

![performance](https://user-images.githubusercontent.com/35210495/119921195-2b79b080-bfa0-11eb-871e-7d1daa95e5d8.gif)

## Environment
atoti: 0.5.5
Operating System: win32

**Comment by bloussou** [comment]
@HuifangYeo is it still an issue ? It looks ok on my computer with the latest version.

**Comment by bloussou** [comment]
I'm closing this since it was not reproduce for 6months
