### ISSUE TITLE
Manual mode - aggregation of store column returns wrong value

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#287]
## Steps to reproduce

The cube is in manual mode and I have to create some measures from the base store.

![image](https://user-images.githubusercontent.com/35210495/119922717-f91d8280-bfa2-11eb-8996-8a5c88418c70.png)

There is a difference in results returned by the measures between embedding `tt.value(batting_store["At Bats"])`  and embedding a computed measure in the `tt.agg.sum`.

No observable exception in logs. Please see the attached notebook.

[main2.zip](https://github.com/atoti/atoti/files/6557865/main2.zip)

## Environment

- atoti: 0.5.5
- Python: 3.9.2
- Operating System: win32

**Comment by HuifangYeo** [comment]
I just realized that I can also just do `tt.agg.sum(batting_store["At Bats"])` without `tt.value(batting_store["At Bats"])`.
The below snippet will work:
```
m["Player Season At Bats"] = tt.where(
    l["playerID"] != None,
    tt.agg.sum(batting_store["At Bats"]),
    None,
)
```

**Comment by bloussou** [comment]
Hi,
It is similar to https://github.com/atoti/atoti/issues/281, it will be fixed in the next release.
