### ISSUE TITLE
Way to quickly access partially selected filter members

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#288]
## Description
![image](https://user-images.githubusercontent.com/35210495/119937656-bcab5000-bfbd-11eb-866a-1a5cbc5aea95.png)

I had some members selected from a very long list. But I would like to remove one of the members from the filter list.
I had to do another search for the member before I can remove it, which is not very friendly.

**Comment by mtadams007** [comment]
Tracking internally in this [ticket](https://support.activeviam.com/jira/browse/UI-5941).

**Comment by bloussou** [comment]
Hello, this will be available in the next release
