### ISSUE TITLE
Selected member disappeared after expanding member in filter popup

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#289]
## Steps to reproduce

I have a Player hierarchy that is two level:
1. PlayerID
2. FullName

I had selected a member previously and would like to add more members to the filter. On expanding the levels to check the name of the player, the list somehow got reset. The previously selected members are all lost.

![filter_selection_mixed_up](https://user-images.githubusercontent.com/35210495/119938664-558e9b00-bfbf-11eb-86bd-83fa691e57a5.gif)

## Environment

- atoti: 0.5.5
- Operating System: win32

**Comment by mtadams007** [comment]
Tracking internally in this [ticket](https://support.activeviam.com/jira/browse/UI-5940).

**Comment by bloussou** [comment]
This is solved in atoti `0.6.4`
