### ISSUE TITLE
Aggregating with and without `tt.value`

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#290]
## Steps to reproduce
I have the below data:
![image](https://user-images.githubusercontent.com/35210495/119941489-3f82d980-bfc3-11eb-9fc6-3a7524af38ad.png)

I created 2 measures to compute the `Player Season at Bats`: 
- one aggregating `tt.value(battling_store["At Bats"])` at the scope of `l["playerID"]`
- another aggregating from the `battling_store["At Bats"]` directly:
![image](https://user-images.githubusercontent.com/35210495/119941568-5d503e80-bfc3-11eb-8df5-8f86d254f046.png)

The measure returned by `tt.value(battling_store["At Bats"])` missed out the 2019 value of 418.
The second one reflects the correct result.

When should we use `atoti.value` and what is the correct way to formulate the formula here?
Please see attached notebook for `session.visualize("Player Season at bat computation")`.

[main.zip](https://github.com/atoti/atoti/files/6558868/main.zip)

## Environment
- atoti: 0.5.5
- Python: 3.9.2
- Operating System: win32

**Comment by HuifangYeo** [comment]
I think the below explains the difference. Correct me if I'm wrong.

`atoti.value` only returns if the value is unique. So for encared01, there are 2 records for 2019.
Hence, it returns null. In such cases, we should just aggregate the store column directly.

However, in the case when I want to compute the age from the birth year, I should use `atoti.value` so that I get the unique year value (`m["birthYear"]`) instead of an aggregated sum of the birth year (`m["birthYear2"]`).

![image](https://user-images.githubusercontent.com/35210495/119944842-59beb680-bfc7-11eb-86d7-553881d15f7e.png)

**Comment by bloussou** [comment]
Closing this at is solved and a solution has been given
