### ISSUE TITLE
How does apply_filter for atoti.total works?

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#291]
## Steps to reproduce
How does the `apply_filter` parameter of `atoti.total` works?
It seems no matter if I set it to `True` or `False`, the query is still affected by the filter.

![total_apply_filter](https://user-images.githubusercontent.com/35210495/120167407-47938100-c230-11eb-98d2-cfc2c5a0013c.gif)

## Environment
- atoti: 0.5.5
- Python: 3.9.2
- Operating System: win32

**Comment by bloussou** [comment]
Hello,

The documentation is not great I will improve it. `apply_filters` is not exactly this **Whether to apply the query filters when computing the value at the parent member.** but this **Whether to apply the query filters defined on the hierarchies parent_value is taken on when computing the value at the parent member.**. Meaning it is filters on `h["CustomerID"]` that are impacted by this parameter in your case.

Do you need something that clear filters for all hierarchies ? If yes what is the use case for this ?

**Comment by bloussou** [comment]
Documentation has been improved with an example so I'm closing this.
