### ISSUE TITLE
A section consolidating all the available connectors

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#292]
## Description

It will be great if we could have a section that summarizes the type of connectors atoti has.
It will be more convenient us to refer to when answering queries such as [this](https://www.linkedin.com/feed/update/urn:li:activity:6805485136117940224?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6805485136117940224%2C6805485193126920192%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6805485136117940224%2C6805510451624058880%29) and also for new users to know what are the options they have.

**Comment by bloussou** [comment]
It may be included in the `how to` showing that multiple data sources can be used in the same `store`. @tibdex what do you think ?

**Comment by fabiencelier** [comment]
There is the feature map displaying all the available sources: https://www.atoti.io/features/

**Comment by HuifangYeo** [comment]
Sadly, there's no link from the atoti landing to the features (I may have missed it). The feature map also doesn't indicate that where they can find the API for the connectors.
