### ISSUE TITLE
How to display different source simulation in a pivot table

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#296]
## Steps to reproduce

I have 2 source simulations. With the 0.4.x version, I was able to display the following:
![image](https://user-images.githubusercontent.com/35210495/120957408-31357a00-c788-11eb-8466-4fffaa1c612b.png)

With the latest version, how do I display both simulations?
![image](https://user-images.githubusercontent.com/35210495/120957287-faf7fa80-c787-11eb-852f-f341502ba89f.png)

## Environment

- atoti: 0.5.5
- Operating System: win32
- Browser: Chrome

**Comment by tibdex** [comment]
**New Customer budget simulation** is not a source simulation: it's a measure simulation. If **90% NRR** and **95% NRR** are also scenarios of another measure simulation you can crossjoin the two simulation hierarchies. If they are the scenarios of your source simulation, you can crossjoin the hierarchy of **New Customer budget simulation** with the **Source simulation** one like shown in [the tutorial](https://docs.atoti.io/0.5.5/tutorial/tutorial.html#Simulations).

**Comment by HuifangYeo** [comment]
Yes, you are right. Sorry I got confused.

Thanks for pointing that out.
