### ISSUE TITLE
Accessing Google cloud storage 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#298]
## Description

I have set my Google storage bucket to public and I was able to access the file via the public URL. 
![image](https://user-images.githubusercontent.com/35210495/121316053-81087280-c93b-11eb-8b83-48aa860b6e07.png)

However, if I try to access the gsutil URI, it throws the below exception.
```
AtotiJavaException: 401 Unauthorized
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Anonymous caller does not have storage.buckets.get access to the Google Cloud Storage bucket.",
    "reason" : "required"
  } ],
  "message" : "Anonymous caller does not have storage.buckets.get access to the Google Cloud Storage bucket."
}
```
Can you advise how I can access gsutil URI without having to configure authentication?
For Azure and AWS, I was able to access the document without authentications.

Also, is it possible to support the public URL ("https") instead of just gsutil URI?

## Environment
- atoti: 0.5.5
- Python: 3.9.2
- Operating System: win32

**Comment by HuifangYeo** [comment]
I've created the `GOOGLE_APPLICATION_CREDENTIALS` env variable as suggested by https://cloud.google.com/docs/authentication/production#automatically. I still wasn't able to access the file.

**Comment by fabiencelier** [comment]
I have just tested it and I had to give these three roles to `allUsers` on my bucket:
<pre>
Storage Legacy Bucket Reader
Storage Legacy Object Reader
Storage Object Viewer
</pre>

You can do that from the "Permissions" tab of your bucket:

![GCP permissions tab](https://user-images.githubusercontent.com/17087544/122535573-fce17980-d023-11eb-9bea-4ee1f3b3e41c.png)

**Comment by tibdex** [comment]
Hi @HuifangYeo, can you please try Fabien's suggestion and close the issue if it fixes your problem?
