### ISSUE TITLE
Undefined caption from the UI in the notebook

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#30]
## Description

```
vendors~main.e36f9ec557b7cc383dbd.js:2 TypeError: Cannot read property 'caption' of undefined
    at vendors~main.e36f9ec557b7cc383dbd.js:2
    at Array.forEach (<anonymous>)
    at e (vendors~main.e36f9ec557b7cc383dbd.js:2)
    at e (vendors~main.e36f9ec557b7cc383dbd.js:2)
    at Function.eh.fromCellSet (vendors~main.e36f9ec557b7cc383dbd.js:2)
    at t.e (vendors~main.e36f9ec557b7cc383dbd.js:2)
    at t.e (vendors~main.e36f9ec557b7cc383dbd.js:2)
    at vendors~main.e36f9ec557b7cc383dbd.js:2
    at vendors~main.e36f9ec557b7cc383dbd.js:2
    at Object.e [as cb] (vendors~main.e36f9ec557b7cc383dbd.js:2)
```

## Reproduce

Check out this [notebook](https://github.com/atoti/notebooks/blob/master/finance/collateral-shortfall-monitoring/main.ipynb), run all cells until `h["Date"].slicing = True`

![screenshot-localhost_8888-2020 05 07-09_44_11](https://user-images.githubusercontent.com/4415696/81268004-a3003900-9047-11ea-8af0-8caa96b30fc8.png)

Only tested against 0.3.1 since I was not able to run the notebook in latest because [I'm facing an other issue](https://github.com/atoti/atoti/issues/31) preventing me from executing the notebook.

## Context

- Atoti version: 0.3.1
- Browser: Version 81.0.4044.113 (Official Build) Arch Linux (64-bit)
- Operating System: linux

**Comment by tibdex** [comment]
Hi, I can still reproduce in 0.4.0, I've created an [internal ticket](https://support.activeviam.com/jira/browse/UI-4145) for it.

**Comment by fabiencelier** [comment]
Similar error when changing a dimension or deleting a hierarchy used:

![Screenshot from 2020-06-15 10-52-22](https://user-images.githubusercontent.com/17087544/84640013-6999d380-aef9-11ea-8c1e-56b906452321.png)
