### ISSUE TITLE
Unable to filter on date

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#300]
## Steps to reproduce
I have the selected date member but I encountered `Empty list of fields to retrieve from the store.` when I try to filter on the selected date:

![filter_on_date](https://user-images.githubusercontent.com/35210495/122497029-51cec100-d01f-11eb-91f3-888386f3e501.gif)

## Environment

- atoti: 0.5.5
- Operating System: win32
- Browser: Chrome

**Comment by HuifangYeo** [comment]
btw, the date hierarchy is a parameter hierarchy created with `create_static_parameter_hierarchy`.

**Comment by bloussou** [comment]
This is fixed in atoti `0.6.4` :
![image](https://user-images.githubusercontent.com/32448554/151372162-72eb3cbd-8dff-4fea-86dc-7e21a22e59c6.png)
