### ISSUE TITLE
Inconsistent behaviour in scenario

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#301]
## Steps to reproduce

The Dates hierarchy is a parameter hierarchy. I have created a weight datastore where it is empty in the base scenario.
![image](https://user-images.githubusercontent.com/35210495/122498876-75473b00-d022-11eb-85ad-f53d3a2d3bc5.png)

Weights are loaded into the weight store as scenarios (i.e. only base has no data).

![image](https://user-images.githubusercontent.com/35210495/122498815-59439980-d022-11eb-99ac-96349f7e43f3.png)

From the visualization, we can see some weird behaviours:
- In red: `m[p sliding 2]` is the mean of a sliding window. It is available at the stock level for all scenarios (including base) except for the first scenario `weight 0`. I expect the value for this to be the same for all scenarios.
- In blue:  I have some weights for scenario `weight 0` and `weight 1`. Hence I'm expecting some values for `p sliding` of the `weight 0` scenario. The `p sliding` values for the stock level doesn't show but there is a value at the Date level in scenario `weight 0`. In scenario `weight 1`, the `p sliding` column doesn't even show up.

Please see the sample notebook (before Computing mu section).
[weights.zip](https://github.com/atoti/atoti/files/6674300/weights.zip)

## Environment

- atoti: 0.5.5
- Python: 3.9.2
- Operating System: win32

**Comment by bloussou** [comment]
I'm closing this because after upgrading the notebook to `0.6.4` it looks like the bug is resolved :
![image](https://user-images.githubusercontent.com/32448554/151371725-82d37373-9f50-4b90-ad03-5e91d2ec3e21.png)
