### ISSUE TITLE
jupyter widget fails to run in atoti docker image

### ISSUE THREAD

**Issue by blair-anson** [atoti/atoti#304]
## Steps to reproduce

1. `docker pull atoti/atoti`
2. `docker volume create atoti-volume`
3. `docker run --publish 8888:8888 --volume atoti-volume:/[a host folder] atoti/atoti`
4. Open the jupyter url
5. Open the tutorial.ipynb file and run the cells
6. Open the atoti widget panel

## Actual Result

Cell and widget panel shows "Waiting for connection"
![image](https://user-images.githubusercontent.com/5399102/122675751-d7b45d00-d215-11eb-9788-5674926fe143.png)

## Expected Result

Widget connects and displays as per tutorial images.

## Environment

- atoti: docker image

"""
Using default tag: latest
latest: Pulling from atoti/atoti
Digest: sha256:69cf20ce6c915d3e0ca3ce6d5e3afdeee7f8c08efeffcec71dfb16430a005104
Status: Image is up to date for atoti/atoti:latest
docker.io/atoti/atoti:latest
"""

- Python:
- Operating System: Host is Ubuntu 18.04

**Comment by tibdex** [comment]
Can you share:
- your version of atoti
- the version of JupyterLab
- the lines in the browser console
?

**Comment by blair-anson** [comment]
@tibdex It is the atoti/atoti docker image that atoti provides. So the version of atoti & jupyter are whatever atoti built into that image. 
To be clear I am not installing atoti or jupyter, all I am doing is running the atoti docker image and following the tutorial instructions.
https://docs.atoti.io/latest/tutorial/tutorial.html

The line that is not working, is the very first `session.visualize()` call.

**Comment by blair-anson** [comment]
From the docker image definition it looks like atoti 0.5.5, and I can't see the Jupyter version (probably the one packaged with MiniForge 4.9.2)
https://hub.docker.com/layers/atoti/atoti/latest/images/sha256-69cf20ce6c915d3e0ca3ce6d5e3afdeee7f8c08efeffcec71dfb16430a005104?context=explore


I also tried installing it directly on an Ubuntu 20 server with the same result.

- atoti 0.5.5
- JupyterHub 1.4.1 running JupyterLab 3.0.14
- python 3.8.10
- Chrome web browser

**Comment by blair-anson** [comment]
Root cause of this is a redirect to localhost when jupyter is running on a remote server.
I was runing the atoti docker container on a remote server. Jupyter runs with localhost in the token url, like so 
`http://localhost:8888/lab?token=xxxxxxxxxxxxx`
However I was accessing Jupyter using the full server domain. Normally this is ok, but when the atoti.visualize() cell is run it fails with a 404 Not Found for this url 
`http://someserver.com:8888/proxy/42439/proxy/42439/versions/rest`

and then attempts a redirect to
`http://localhost:8888/proxy/42439/versions/rest`

A temporary workaround was to setup an ssh proxy so accessing localhost:8888 on my local machine proxied up to the server. 
To resolve the issue I tried setting these two items in the jupyter configuration but it did not resolve the issue. It would be great is someone could provide some instructions for getting atoti running on a remote server.

```
c.NotebookApp.ip = 'xx.xx.xx.xx'
c.JupyterHub.bind_url = 'http://someserver.com:8888'

```

**Comment by Skyscimitar** [comment]
Hello! 
If you're running the docker container from a remote server you can specify the `BASE_URL` and `PORT`  environment variables when running the container. In your case `docker run --env BASE_URL=http://someserver.com --publish 8888:8888 atoti/atoti` should work. You don't need to manually set the jupyter lab config when doing this, the docker image handles that for you.

**Comment by blair-anson** [comment]
@Skyscimitar thanks, that solves my problem. 
May I suggest updating https://docs.atoti.io/latest/installation.html#docker-image to mention the `BASE_URL` env variable.

**Comment by Skyscimitar** [comment]
The `BASE_URL` environment variable won't be necessary with the next version of atoti which is coming soon!

**Comment by alexleach** [comment]
Hi, has this actually been fixed yet? I'm going through the atoti tutorial and am experiencing the exact same behaviour as the OP. I haven't yet tried re-spawning my container with the BASE_URL env. var, but will try that next.

My set up is slightly different, I'm using atoti and atoti-jupyterlab versions 0.6.0 (released since this issue was closed), but my jupyterlab instance is managed by jupyterhub. Should that make a difference? I can open a new Issue if required...

**Comment by Skyscimitar** [comment]
Hello, could you check and see if the [`session.link()`](https://docs.atoti.io/latest/lib/atoti.session.html#atoti.session.Session.link) method is working correctly? The `session.visualize` uses the URL generated by `session.link` in order to access the session.
You may need to install the [Jupyter Server Proxy](https://jupyter-server-proxy.readthedocs.io/en/latest/) in order for `session.visualize()` to work properly in your environment.

**Comment by alexleach** [comment]
Thanks for the tip! I've installed Jupyter Server Proxy and that seems to do the trick, although the `create_session` function seems to take a lot longer now than it did before.

Previously, `session.link` showed an http url with a random port number, but after installing Jupyter Server Proxy, it now produces a URL using the same server base url and port as I use to access my notebook server. My JupyterHub server only proxies a single port (https, port 443) to my notebook server, so any other port won't reach the notebook server of course.

Many thanks 😄
