### ISSUE TITLE
Ability to use current and prev member on KPI

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#309]
## Steps to reproduce
I would like the comparison on KPI for the latest date values. We used to be able to manipulate the MDX by creating a calculated member as follows:

```
WITH
 Member [Measures].[DIFF] AS IIF(
  [assets_prices_store].[Date].CurrentMember.PrevMember IS NULL,
  NULL,
  [Measures].[Market Value] - (
    [Measures].[Market Value],
    [assets_prices_store].[Date].CurrentMember.PrevMember
  )
), FORMAT = "#,###.00"  
```
However, it always gets reset to a hardcoded date:

```
WITH Member [assets_prices_store].[Date].[__comparison_member__] AS [assets_prices_store].[Date].[2019-03-17] - [assets_prices_store].[Date].[2019-03-18], CAPTION = "2019-03-17 - 2019-03-18" 
SELECT
  NON EMPTY {
    [Measures].[Market Value]
  } ON COLUMNS,
  {
    [assets_prices_store].[Date].[2019-03-18],
    [assets_prices_store].[Date].[2019-03-17],
    [assets_prices_store].[Date].[__comparison_member__]
  } ON PAGES
  FROM [Collateral_Management]

```

## Environment

- atoti: 0.5.5
- Operating System: win32

**Comment by rcolle** [comment]
I'm not sure I understand the issue. How do you get from the first MDX statement to the second.
Who / what "resets" it?

**Comment by HuifangYeo** [comment]
Sorry, my bad. I was too lazy to go and dig out the old way of MDX.
In v0.4.x, we can modify the MDX to use the nextMember:
![image](https://user-images.githubusercontent.com/35210495/123379961-6aac1900-d5c1-11eb-9632-43de865d7058.png)


```
SELECT
  {
    [Time].[HistoricalDates].CurrentMember,
    [Time].[HistoricalDates].CurrentMember.NextMember
  } ON PAGES,
  NON EMPTY Hierarchize(
    DrilldownLevel(
      [Booking].[Desk].[ALL].[AllMember]
    )
  ) ON ROWS,
  NON EMPTY [Measures].[pnl.SUM] ON COLUMNS
  FROM [EquityDerivativesCube]
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
```
However, I am unable to find the right way to modify the MDX for v0.5.x, especially since the MDX gets "reverted back" to use hardcoded dates upon submission.

![KPI_mdx](https://user-images.githubusercontent.com/35210495/123380059-8e6f5f00-d5c1-11eb-8ff2-6d0330e2a7e9.gif)

Hope this is clearer.

**Comment by HuifangYeo** [comment]
Just found the ticket [UI-6099](https://support.activeviam.com/jira/browse/UI-6099) related to editing MDX for KPI.

**Comment by rcolle** [comment]
Hi @piyuw ,
This feature has not yet been implemented as of the latest release.
Can you please remind me of your use case? Are you trying to do a day-to-day comparison of a KPI?
Thanks


PS: For atoti reference here is the internal ticket: [UI-6131](https://support.activeviam.com/jira/browse/UI-6131)

**Comment by tibdex** [comment]
Closing this because the internal ticket has been closed with the following comment:

> Postponing for now as we cannot introduce this feature without breaking changes.
