### ISSUE TITLE
Open the notebook in JupyterLab with the atoti extension installed and enabled to start editing this widget.

### ISSUE THREAD

**Issue by nithinreddyy** [atoti/atoti#310]
Unable to view the chart in jupyter lab.

When i tried
` session.visualize()`

![lab](https://user-images.githubusercontent.com/56256685/123386142-f6b74400-d5b3-11eb-9124-a37539b7d93c.PNG)

The actual chart expected was

![expected](https://user-images.githubusercontent.com/56256685/123386197-046cc980-d5b4-11eb-889e-dd8512c4f720.PNG)

**Comment by Skyscimitar** [comment]
Closing after discussion on gitter

**Comment by lorenzo1285** [comment]
cant run .url and visualize() methods 
![imagen_2021-12-18_172302](https://user-images.githubusercontent.com/86883691/146658067-fd0bcfbf-5a8f-4844-b5b1-4f2fb6d8eccc.png)

**Comment by tibdex** [comment]
> cant run .url and visualize() methods

See https://docs.atoti.io/0.6.0/releases/0.6.0.html#id5.

**Comment by lorenzo1285** [comment]
thanks atoti it´s running now. Regards
