### ISSUE TITLE
Mismatching between CE vs EE comparing Confluence and ActiveViam websites

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#311]
## Description
Hello, please compare the following screenshots.
![ce_vs_ee_2](https://user-images.githubusercontent.com/7359377/124089960-b264f180-da54-11eb-84da-e5a7baede3e2.PNG)
![ce_vs_ee_1](https://user-images.githubusercontent.com/7359377/124089975-b4c74b80-da54-11eb-8a6d-0605c7e80de8.PNG)

**Comment by rcolle** [comment]
As much as I love fun games, why should we do this?

**Comment by Harold7665** [comment]
The answer may be somewhere on the title :o

**Comment by rcolle** [comment]
Closing this for lack of info.
