### ISSUE TITLE
session.query fails when 2 levels with same name in `raw` mode

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#315]
Hello,

On the last version of atoti, querying a cube having 2 levels with the same name (and different paths) throws an error when building the dataframe because 2 columns have the same name.
Tested with a customer on a MarketRisk use case with:
[Underlyings].[Underlyings].[Underlying] and [Risk Factors].[Risk Factor].[Underlying].

Is there a way (as a label) to modify this in MDX, or a fix you could add in the next release?

**Comment by bloussou** [comment]
I'm not reproducing your issue in `0.6.0` or `0.5.5`, can you share the code creating this issue ?

**Comment by Harold7665** [comment]
Hello,
Unfortunately I am not able to reproduce the customer usecase. I keep you in touch if they still have the issue, and I will ask for more information.
