### ISSUE TITLE
NPE on datastore query with wrong store name

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#316]
## Steps to reproduce
```python
session = tt.create_session()
gain_store = session.read_csv('./data/', keys=['ISO3', 'Date'], store_name='Gain')
cube = session.create_cube(gain_store, name='cube', mode='no_measures')
session.url
response = requests.get('http://localhost:61745/pivot/rest/v5/datastore/data/stores/gain_store')
```

## Actual Result
NPE.

## Expected Result
Caught exception.

## Environment
- atoti: 0.5.5
- Python: 3.9.6
- Operating System: win32

## Logs
[logs.txt](https://github.com/atoti/atoti/files/6824134/logs.txt)

**Comment by bloussou** [comment]
This is handled since `0.6.0`
