### ISSUE TITLE
Join issue with partitioning

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#317]
## Steps to reproduce
```python
import atoti as tt
session = tt.create_session()
table_1 = session.create_table(
    types={
        "l1": tt.type.STRING
    }, 
    name="t1", 
    keys=["l1"], 
    partitioning="hash2(l1)"
)
table_2 = session.create_table(
    types={
        "l1": tt.type.STRING
    }, 
    name="t2",
    keys=["l1"], 
    partitioning="hash2(l1)"
)
table_1.join(table_2, mapping={"l1": "l1"})
cube = session.create_cube(table_1)
```

I obtain this error message:
```The current operation leads to the re-dictionarization of field FieldKey(store=t2, name=l1) used by the partitioning```

On 0.5.5 this type of join with this partitionning was not creating issues.

## Environment

- atoti: 0.6.0.20210719111116
- Python: 3.9.6
- Operating System: win32

**Comment by Harold7665** [comment]
Hello, I have the same in 0.6.0.

**Comment by alexis-bvq** [comment]
Hello, do you have an ETA for this bug ? It is quit annoying as we can't develop proper project in 0.6 as we are not able to have partitionning...

**Comment by Skyscimitar** [comment]
Hello, we won't be able to fix it in atoti until this core issue is addressed https://support.activeviam.com/jira/browse/PIVOT-4741.

In the mean time, you can use the `columns_with_shared_dictionary` argument when creating tables.

```python
    table_1 = session.create_table(
        "table_1",
        types={"key1": tt.type.STRING},
        keys=["key1"],
        partitioning="hash2(key1)",
    )
    table_2 = session.create_table(
        "table_2",
        types={"key2": tt.type.STRING},
        keys=join_table_keys,
        partitioning="hash2(key2)",
        columns_with_shared_dictionary={"key2": table_1["key1"]},
    )
    table_1.join(table_2, mapping={"key1": "key2"})
```

**Comment by alexis-bvq** [comment]
Is it available on 0.6.1 or on the nightly ?

**Comment by alexis-bvq** [comment]
Looks like it is only available on the nightly and I will need to pass this code to a client so I will move back the application to 0.5.5 .

**Comment by Skyscimitar** [comment]
It's available in 0.6.1, it's just not in the public documentation

**Comment by alexis-bvq** [comment]
Last question then, if you have three stores : 
```python
    table_1 = session.create_table(
        "table_1",
        types={"key1": tt.type.STRING},
        keys=["key1"],
        partitioning="hash2(key1)",
    )
    table_2 = session.create_table(
        "table_2",
        types={"key2": tt.type.STRING},
        keys=join_table_keys,
        partitioning="hash2(key2)",
        columns_with_shared_dictionary={"key2": table_1["key1"]},
    )
    table_3 = session.create_table(
        "table_3",
        types={"key3": tt.type.STRING},
        keys=join_table_keys,
        partitioning="hash2(key3)",
    )
    table_2.join(table_3, mapping={"key3": "key"})
    table_1.join(table_2, mapping={"key1": "key2"})
```

Should it be 
```python
        columns_with_shared_dictionary={"key3": table_2["key2"]}
```
or 
```python
        columns_with_shared_dictionary={"key3": table_1["key1"]}
```
 ?

**Comment by Skyscimitar** [comment]
It shouldn't make any difference. Since when creating `table2`, the column `key2` shares its dictionary with `key1` if another column shares its dictionary with `key2` it also shares its dictionary with `key1`.  
As long as you use a column which already shares its dictionary with at least one of the columns being mapped together it should be fine.
