### ISSUE TITLE
Error on update to 0.6.0

### ISSUE THREAD

**Issue by ncosgrov58** [atoti/atoti#318]
Just update my atoti installation to 0.6.0.  No error messages on upgrade.  When I go to open a notebook I get the following error

_ No module named 'atoti._bitwise_operators_only_

**Comment by Skyscimitar** [comment]
Can you attach a notebook for which you get this issue please?

Also could you please provide more information about your environment (operating system, Python version, and the versions of other packages installed in your Python environment).

**Comment by ncosgrov** [comment]
I resolved the problem over the weekend by specifically updating the atoti Jupyter lab plugin again.  For the record, Operating System was WIndows, python 3.7.10

**Comment by bloussou** [comment]
I am closing this issue since it has been resolved. You can open a new one or reopen it if you are facing other issues when updating to `0.6.0`.
