### ISSUE TITLE
Warning message for subplots

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#320]
## Steps to reproduce

Please see the placeholders in the warning message:
![image](https://user-images.githubusercontent.com/35210495/126751438-375443a2-8379-4c8e-a9ae-ade189927795.png)

## Environment

- atoti: 0.6.0
- Operating System: win32

**Comment by bloussou** [comment]
Related internal ticket : https://support.activeviam.com/jira/browse/UI-5773
