### ISSUE TITLE
Changing the location of temporary files

### ISSUE THREAD

**Issue by MarcusJeitler** [atoti/atoti#326]
## Description

atoti stores temporary files under /tmp. Currently, I have  not found any hint on how to change the location of temporary files from /tmp to another directory.

**Comment by Skyscimitar** [comment]
atoti uses the [tempfile](https://docs.python.org/3/library/tempfile.html) Python library to generate temporary files. You can change the location at which they are created by setting the `TMPDIR` environment variable.

**Comment by MarcusJeitler** [comment]
I tested and verified that setting TMPDIR works. Thank you. This solves our issue.
