### ISSUE TITLE
Inferring data type from csv

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#330]
## Description

Pandas is able to infer the data type more accurately and allows us to cast it anytime. 

However, with atoti, it's only upon table creation then do we realize that the column is of the wrong data type and has to be cast. In such cases, we are unable to re-create the table but had to re-create from the session. 

In the attached notebook, there are quite a few columns with the data type wrongly inferred. We have to cast each column one by one during table creation. It would be nice if we can cast easily like pandas for multiple columns in one go, and post table creation:
```
df[['one', 'two', 'three']] = df[['one', 'two', 'three']].astype(str)
```
[covid.zip](https://github.com/atoti/atoti/files/6922049/covid.zip)

**Comment by bloussou** [comment]
Thanks for reporting this. I not something we want yet since it could produce strange behavior : what will happen to the cube defined on the table you have changed the type of one column ?
You can do something like this when defining the table : `types= { c: STRING for c in ["a", "b", "c"]}`.

**Comment by HuifangYeo** [comment]
Alrighty. I'll try out your suggestion for the casting.
But I think a simpler way would be to use pandas to read the csv before reading into atoti.
That way, I have less columns to cast.

**Comment by rcolle** [comment]
> But I think a simpler way would be to use pandas to read the csv before reading into atoti.
> That way, I have less columns to cast.

That'd be much slower performance-wise.
What is the actual issue with specifying the column types when reading the file? It seems a natural thing to do, and that's what you'll do in all RDBMS / Spark / ... software.

**Comment by HuifangYeo** [comment]
lol laziness to copy 10 column names to cast them. Brieuc's suggestion is totally fine.

**Comment by HuifangYeo** [comment]
Another question on the data type.  I was able to read data into the table as type `INT`.
![image](https://user-images.githubusercontent.com/35210495/128965260-871fa31a-55bc-4fec-b19c-a2301e213ee0.png)

But why is the below exception thrown during cube creation? Shouldn't such error be managed during `read_csv`?
```
com.activeviam.fwk.ActiveViamRuntimeException: Exception while translating column total_vaccinations with parser Plugin Value (key=int, class com.quartetfs.fwk.format.impl.IntParser) in file FileSystemFileInfo [fullName=C:\Users\Yeo Hui Fang\Documents\GitHub\perso-hfy-atoti-covid\owid-covid-data-hfy.csv, lastModifiedTime=Wed Aug 11 11:02:02 SGT 2021]. Parsed text was "4482578359"
```

**Comment by bloussou** [comment]
`4482578359` should be a `long`. We are inferring types by reading the first 1000 lines so that is why it was not throwing at read_csv time
