### ISSUE TITLE
atoti.value is not working as atoti.agg._single_value

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#331]
## Steps to reproduce
Hello
I have this store:
```python
contracts_table = session.read_csv(
    './data/contracts/*.csv',
    keys=['Reporting Date', 'Contract ID', 'Legal Entity'],
    table_name='Contracts'
)
```
And this store:
```python
contracts_static_table = session.read_csv(
    './data/static/contracts.csv',
    keys=['Contract ID', 'Legal Entity'],
    table_name='Contracts (static)'
)
```
With this relation: 
```python
contracts_table.join(contracts_static_table)
```
Then I create this hierarchy:
```python
h['Segments'] = {
    'Segment': contracts_static_table['Segment'],
    'Contract': contracts_table['Contract ID']
}
```
And this measure:
```python
m['Stage'] = tt.value(contracts_table['Stage'])
```

## Actual Result
```python
print(m['Stage']._required_levels)
```
**['Contract ID@Contract ID@Contracts', 'Legal Entity@Legal Entity@Contracts', 'Contract@Segments@Contracts (static)', 'Reporting Date@Reporting Date@Contracts']**

## Expected Result
```python
print(m['Stage']._required_levels)
```
**['Contract ID@Contract ID@Contracts', 'Reporting Date@Reporting Date@Contracts', 'Legal Entity@Legal Entity@Contracts']**

## Environment
This is a migration from 0.5.2 to 0.6.0.

**Comment by rcolle** [comment]
Hi Harold,
Appart from the reported internal required levels, how does this affect your application?

**Comment by Harold7665** [comment]
Hi,
At the moment, it breaks the dashboards using filters on this measure.

**Comment by bloussou** [comment]
I'm closing this since it is a duplication of the same issue as https://github.com/atoti/atoti/issues/312
