### ISSUE TITLE
Not able to collapse second level drill down in the pivot table

### ISSUE THREAD

**Issue by rvs36** [atoti/atoti#332]
Hello team,

I am not able to collapse the drill down in the pivot table while doing a second-level drill down. However, the collapse works for one level drill down.
Here is a gif to show exhibiting the issue:

![drill down fail](https://user-images.githubusercontent.com/57663462/128486699-48d6e7bf-3407-410a-a940-dfcc9765d06f.gif)
 But as shown below the same collapse works for the first level of drill down.
![drill down works](https://user-images.githubusercontent.com/57663462/128486763-c4384454-7d34-49fe-8715-1adc8347874d.gif)

Please look into the above issue. 
Thanks!

**Comment by antoinetissier** [comment]
Will be fixed by https://github.com/activeviam/activeui/pull/1707
