### ISSUE TITLE
Quick filter to work across multiple cubes

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#333]
## Description

This is a make-up use case where I have 2 cubes with some overlapping hierarchies - continent and location.

During table creation, we have to define unique table_names because it is at the session level, i.e. 
```
covid_data = session.read_pandas(covid_variables, table_name="covid_stats")
covid_data2 = session.read_pandas(covid_variables, table_name="covid_stats2")
```

In the web application, we can have widgets from both cubes displayed on the same page.
However, once we add in `Quick filter`, only the widgets from 1 cube will work. The rest will break because of the different table names.

![image](https://user-images.githubusercontent.com/35210495/128803977-68fe32a4-bd2d-41c8-8037-5a7d50170451.png)

If we can have the same table name for different cubes, then the quick filter will still be able to function.
Alternatively, it will be nice if the quick filter can check if the hierarchy/level exists in the cube of the respective widgets and apply it only if it exists, inferring the dimension name from the cube.

I'm not sure how realistic is this use case but it does prevent the Quick Filter from being useful if there are widgets from different cubes on a page.

**Comment by fabiencelier** [comment]
You can make 2 cubes on the same table if you want, you don't need 2 tables

**Comment by HuifangYeo** [comment]
Hi @fabiencelier,

just happened that I'm having 2 different tables of different data structures. Hence, I'm demonstrating 2 cubes instead of 1.
I can also do a join, instead of splitting into 2 cubes. 

But mainly this is just to say that for any dashboarding with multiple cubes, the quick filter will not work.

**Comment by rcolle** [comment]
It seems to me that the problem here is not the table name, but the dimension name.
atoti automatically uses the name of the table as the dimension name.

@HuifangYeo  Isn't your problem solved if you use the same dimension name in the second cube?
```python
cube2.hierarchies["continent"].dimension = "covid_stats"
```

**Comment by HuifangYeo** [comment]
Thanks for the solution proposal. I've modified the notebook since, hence can't really test it out quickly. But I'll keep it in mind for the next use case. I'll proceed to close the issue.
