### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#337]
## Description

Something very handy on excel that we sometime can't handle with a `where` is the `IFERROR` function.
It allows you to put a default value in case you have a mathematical or wrong entries errors.
In atoti this appears to arrive when you work with vectors. If you divide one vector by another one, if one of them contains a 0 then you have an error. This error can't be anticipated with a `where` measure as you can not test each value of the vector.

**Comment by Skyscimitar** [comment]
Would a function like this allow you to complete your use case for vector measures?

```python
m["Array"] = [1.0, 2.0, 2.0, 3.0, 4.0, 0.0, 10.0]
m["Array2"] = [2.0, 4.0, 6.0, 6.0, 8.0, 5.0, 30.0]
m["Array3"] = m["Array2"] / m["Array"]  # [2.0, 2.0, 3.0, 2.0, 2.0, math.inf, 3.0]

tt.array.replace(m["Array"], old=0.0, new=1.) #  [1.0, 2.0, 2.0, 3.0, 4.0, 1.0, 10.0]
tt.array.replace(m["Array3"], old=math.inf, new=-1.)  # [2.0, 2.0, 3.0, 2.0, 2.0, -1.0, 3.0]
```

**Comment by bloussou** [comment]
Hello,
I think this is fixed [`tt.array.replace()`](https://docs.atoti.io/latest/lib/atoti/atoti.array.replace.html#atoti.array.replace) is available.
