### ISSUE TITLE
Unable to see the column headers in pivot table

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#341]
## Steps to reproduce

![image](https://user-images.githubusercontent.com/35210495/130552098-7121fd9a-14ec-4e91-8cdb-9badb1d60aad.png)

## Environment

- atoti: 0.6.1
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, can you help us reproduce this by sharing your notebook or a simplified one where the problem occurs?

**Comment by HuifangYeo** [comment]
Hi @tibdex,

please find a simplified notebook: [main.zip](https://github.com/atoti/atoti/files/7044206/main.zip)

Basically it happens when the overflow happens and scrollbar appears. We can force this to happen by expanding the atoti editor or reduce the visible window size for instance.

![scroll-overflow](https://user-images.githubusercontent.com/35210495/130739044-da24a573-2d35-49e9-ae79-4379ff184102.gif)
