### ISSUE TITLE
Raw mode in QueryCube.query

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#345]
## Description
Hello, a client is using the library to perform exports and get results in 175 seconds in mode pretty, 4 seconds in mode raw. However the mode raw is not available for his usecase where he is not using a cube but a query cube, could you add this?

Already here:
https://docs.atoti.io/latest/lib/atoti.cube.html#atoti.cube.Cube.query

Missing here:
https://docs.atoti.io/latest/lib/atoti.query.cube.html#atoti.query.cube.QueryCube.query

**Comment by tibdex** [comment]
`mode="raw"` is only available on local sessions (non query sessions) because it relies on a custom (i.e. not built into ActivePivot) endpoint that returns query results as a streamable Arrow table.

**Comment by rcolle** [comment]
@tibdex we could detect whether the endpoint exists or not and enable the raw mode for query sessions.

This would effectively only work for applications created by the atoti Python API, but this seems to be the case here.

**Comment by tibdex** [comment]
> this seems to be the case here.

Nope, @Harold7665 told me the query session was connected to a Java server from an accelerator. It will work when we tackle this [internal ticket](https://github.com/activeviam/atoti/issues/2461).

**Comment by bloussou** [comment]
This is available since `0.6.4` for AP server > 5.11.0 : https://docs.atoti.io/latest/releases/0.6.4.html
