### ISSUE TITLE
Failed to parse the row 1 while inferring types of the CSV. The row has (x+1) fields but the header has x fields.

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#348]
## Steps to reproduce

I was able to read the CSV file successfully previously. After upgrading to v0.6.1, I encountered the below exception:

```
AtotiJavaException: Failed to parse the row 1 while inferring types of the CSV. The row [33384689, M, 67, "Sound technician,  broadcasting/film/video", Susanberg, Idaho] has 7 fields but the header [customer_id, sex, age, job, city, state] has 6 fields.
```

It can be fixed by adding `process_quotes=True`:

```
cust_store = session.read_csv(
    "s3://data.atoti.io/notebooks/sales-cube/cust_info.csv",
    keys=["customer_id"],
    table_name="customers",
    process_quotes=True
)
```

Refer to https://github.com/atoti/notebooks/blob/master/notebooks/sales_cube/main.ipynb

## Environment
- atoti: 0.6.1
- Python: 3.9.6
- Operating System: win32

**Comment by bloussou** [comment]
When updating this notebook did you fetch new data ? It looks like I get the same issue in 0.6.0

**Comment by bloussou** [comment]
Hello, this will be fixed in the next release
