### ISSUE TITLE
Understanding table joins and returned results

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#351]
## Steps to reproduce

I have the below schema:
![image](https://user-images.githubusercontent.com/35210495/131093862-8b325c5c-cafa-4be1-bf44-565fa4a8b420.png)

I have checked the source and the `driverRef` "massa" is `driverId` 13.
![image](https://user-images.githubusercontent.com/35210495/131094012-32f32b42-b731-4e3a-9e85-704fc4882306.png)

For `driverId` 13, I have data in the below years:

- 2002
- 2004
- 2005
- 2006
- 2007
- 2008
- 2009
- 2009
- 2010
- 2016
- 2017

When I filter on the `driverRef` "massa", I only get the year 2006 and 2 `driverId` values are returned, of which both are wrong.
If I try to do drillthrough on the web application, I encountered the below error.
![drillthrough_exception](https://user-images.githubusercontent.com/35210495/131095428-a8f40e22-6cdd-4d95-98dd-14eac7a3a3bd.gif)

Source:  [main.zip](https://github.com/atoti/atoti/files/7065307/main.zip)

## Environment

- atoti: 0.6.1
- Python: 3.9.6
- Operating System: win32

## Logs (if relevant)

[server.log](https://github.com/atoti/atoti/files/7065288/server.log)

**Comment by HuifangYeo** [comment]
Since `raceId` is unique, I removed `year` from the keys of **F1 race** table.
![image](https://user-images.githubusercontent.com/35210495/131273457-012d84a4-3859-4ed9-93e0-a3326b6279ce.png)

However, now only 1 or 2 drivers appeared for each race. 

[main.zip](https://github.com/atoti/atoti/files/7073587/main.zip)
![image](https://user-images.githubusercontent.com/35210495/131273572-a24e2f60-0a22-48f7-9a5c-3361ab35dbe2.png)

**Comment by bloussou** [comment]
same issue as #356
