### ISSUE TITLE
Source scenarios disappeared after new table join and slicing is applied on new hierarchy

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#354]
## Steps to reproduce

I created some source simulations with a single table. 
Then I created another table and I get N/A for the new hierarchy resulting from the new table that is joined to the cube:
![image](https://user-images.githubusercontent.com/35210495/131320829-33fa5aea-c3c5-413c-81be-5a146baef168.png)

Then, after applying slicing on the new hierarchy, I get exception on the previous visualization and lost the simulated scenarios:
![image](https://user-images.githubusercontent.com/35210495/131321192-e8f399c8-5682-44e4-99af-57bb14fd2f2b.png)

Sample notebook: [Untitled.zip](https://github.com/atoti/atoti/files/7075820/Untitled.zip)

## Environment

- atoti: 0.6.1
- Python: 3.9.6
- Operating System: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/7075815/server.log)

**Comment by HuifangYeo** [comment]
In fact, I also lost the 2 members x4 and x7

**Comment by bloussou** [comment]
Hi, 
- `x4` and `x7` are not in `table2` so `test_col` has the value `N/A`, this is normal.
- making `test_col` slicing means that you cannot aggregate on this column, if you add `test_col` in your last visualization you will be able to see the scenario, it has not disappeared it is just that null values are not shown in widgets.
-  The fact that visualization broke in previous cell is the same as this issue https://github.com/atoti/atoti/issues/334

**Comment by HuifangYeo** [comment]
Hi @bloussou,

shouldn't the scenario apply to the `x1` that is available?

**Comment by bloussou** [comment]
Indeed in `0.5.5` it was like this : 
![image](https://user-images.githubusercontent.com/32448554/132010839-b57da731-430a-4b2b-acd4-18d6c25b6f08.png)
I'm investigating this bug

**Comment by bloussou** [comment]
Hi, I've understood the issue and it is not one.
Since `0.6.0` :
![image](https://user-images.githubusercontent.com/32448554/132227806-f9f4880f-0db9-4d7d-b5bc-3a676a8cad39.png)

Two ways to fix this:
- Create the `table_2` prior to the scenario creation
- load the data in the scenario if `table_2` is defined after the scenario on `table_1`
```python
table2 = session.read_pandas(df2, table_name="test_table2", keys=["a"])
table2.scenarios["test_scenario"].load_pandas(df2)
```

If it is possible try to define the table before the scenario as it is less code.

I let you close this issue if it is clear for you
