### ISSUE TITLE
Measures and levels disappeared from Jupyter Lab Extension

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#357]
## Steps to reproduce

During the upgrade of the Twitter notebook, the pivot table is rendered and the measures are displayed. However, I am unable to find the measures in the editor: 
![missing_measures](https://user-images.githubusercontent.com/35210495/131430535-9a31e676-b3dd-41de-a84f-78786a58ab74.gif)

The measures can be found in the web application:
![measures_found_in_web_app](https://user-images.githubusercontent.com/35210495/131430644-b4eb7d52-c6d5-4112-b63a-af1ebd8ea0aa.gif)

The same goes for the hierarchies. You can see the difference in the number of hierarchies in the web app vs the Jupyter lab extension:
![image](https://user-images.githubusercontent.com/35210495/131430740-f46d08c1-4e1b-4cbb-94de-032b71157e14.png)

Chrome console log: [localhost-1630376265485.log](https://github.com/atoti/atoti/files/7080616/localhost-1630376265485.log)
Source: [twitter.zip](https://github.com/atoti/atoti/files/7080617/twitter.zip)

## Environment

- atoti: 0.6.1
- Operating System: win32

**Comment by HuifangYeo** [comment]
Restarting the notebook instance seems to fix the problem.

**Comment by tibdex** [comment]
Hi Hui Fang, I'm having trouble running your large notebook and I can't reproduce by doing something similar with the tutorial. Could you please share a minimal reproduction case?

**Comment by HuifangYeo** [comment]
Hi @tibdex, I don't really know which part triggers the issue, therefore I can't replicate it. Especially since it's resolvable by restarting the notebook, I'll just close this ticket for now until I encounter it again.
