### ISSUE TITLE
Jupyter lab extension - allow users to change filter for drillthrough

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#359]
## Description
We can perform drillthrough on the visualizations in the Jupyter notebooks.

![image](https://user-images.githubusercontent.com/35210495/131944650-ac7625b1-e340-4e9c-b8ca-823ac29699e5.png)

However, we are unable to add other members or change the member filter in the drillthrough from the extension:
![image](https://user-images.githubusercontent.com/35210495/131944736-077babe2-a0d7-4aee-8c42-d05ce0d36d33.png)

From the web application, we were at least able to do so from the "Filter" drawer:
![image](https://user-images.githubusercontent.com/35210495/131944885-f1cd50f8-a95a-48e7-9c3a-30cd6013c8ac.png)

**Comment by tibdex** [comment]
Thanks for reporting this, tracking this in an [internal ticket](https://support.activeviam.com/jira/browse/UI-6473).
