### ISSUE TITLE
date_patterns for atoti.create_table

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#360]
## Description

`atoti.read_csv` has a parameter for us to set the date pattern.
https://docs.atoti.io/latest/lib/atoti.session.html#atoti.session.Session.read_csv

In the event I'm creating an empty table and loading data afterwards, I would require similar parameter to configure the `date_pattern` in `atoti.create_table`. Otherwise, I will need to read my csv into a temporary structure to update the date format.

**Comment by Skyscimitar** [comment]
The `date_pattern` parameter is specific to each CSV file not the type on the table. After using `session.create_table` you can use the `date_pattern` argument in the `load_csv` function to parse the dates in your CSV file.
