### ISSUE TITLE
AtotiJavaException: [500] Issue while updating schema

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#363]
## Steps to reproduce
Project available here: https://drive.google.com/drive/u/0/folders/1jGtGDAK_C-zGe_EnER3vMQSZ8XrGKh59

## Actual Result
Sometimes the cells 8 and 11 are working well, sometimes I get the exception on the title. I have no logs.

## Expected Result
Something working all the times or not working at all and in this case, including an error message at least on the ActivePivot logs.

## Environment
- atoti: 0.6.1
- Python: 3.9.7
- Operating System: win32

**Comment by bloussou** [comment]
Hello,
Thanks for the report. I can reproduce with this simple notebook. I'm investigating the issue. It is not happening with the mode `auto` just with the manual mode.
[SimpleReproduction.zip](https://github.com/atoti/atoti/files/7142020/SimpleReproduction.zip)

**Comment by bloussou** [comment]
Here is the internal ticket tracking this core issue : https://support.activeviam.com/jira/browse/PIVOT-5022

**Comment by bloussou** [comment]
Closing this as it is fixed since `0.6.5`
