### ISSUE TITLE
Missing `agg.single_value()`

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#372]
Hello, while updating a demo from atoti 0.5.3 to 0.6.1, I faced an issue.
It was declaring an atoti._udaf_utils.java_function that was placed within a atoti.agg._single_value.
Nevertheless, _single_value has been removed.

I was able to make it work using atoti.agg._agg("NULLABLE_SINGLE_VALUE", ..) but I think it might be a use case you forgot when you removed _single_value.

## Environment

- atoti: 0.6.1
- Python: 3.9.7
- Operating System: win32

**Comment by alexis-bvq** [comment]
Hello, you did not add it back and it is needed for some demos.

**Comment by alexis-bvq** [comment]
I found another way to make it work but I still commented it to remind you to add it back ;)
Cheers team ;)

**Comment by bloussou** [comment]
I'm adding it to the backlog to have a discussion on how we want to handle this

**Comment by bloussou** [comment]
Related to https://github.com/activeviam/atoti/issues/2883#issuecomment-998934346

**Comment by bloussou** [comment]
I'm closing this since `tt.agg.single_value()` is back in [`0.7.0`](https://docs.atoti.io/latest/lib/atoti/atoti.agg.single_value.html#atoti.agg.single_value) :fire:
