### ISSUE TITLE
rename "scope" into "how"

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#376]
Hi this ticket is not a bug, it's a suggestion

It might be just my opinion, but the syntax `scope = tt.scope.origin()` a bit long and also a bit complex. 

Would you consider to rename scope into "how" - as in [pandas join](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html)

how ?
- is to define how to apply aggregation formula?
- how to pivot data before applying the aggregation formula?
- how to organize data before applying the aggregation formula?

for example,
how = "cumulative", along = [lvl['AsOfDate']] or by=lvl[AsOfDate]
how = "simple", along = [lvl['AsOfDate']]
how = "siblings", for_each = lvl[AsOfDate]

**Comment by tibdex** [comment]
Hi Anastasia, we're not planning on making this renaming as it would complexify the signature of all the aggregation functions.
