### ISSUE TITLE
Pivot Table widget column values are hidden by the scrollbar

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#380]
## Steps to reproduce

Any pivot table with Columns containing a lot of values (dates for example) on Chrome
![image](https://user-images.githubusercontent.com/42935528/135994018-8dcc4808-605c-4daf-8ef4-9939f3890d1b.png)

## Expected Result
On Firefox
![image](https://user-images.githubusercontent.com/42935528/135994394-3bbcbb76-17ef-4375-bdc0-6ba7ebdd8da1.png)

## Environment

- atoti: 0.6.2
- Operating System: win32
- Browser: Chrome (Working fine on Firefox)

**Comment by bloussou** [comment]
Hello,
Which version of chrome are you using ? I have just tested on chrome `94.0.4606.71` on windows and it worked as expected : 
![image](https://user-images.githubusercontent.com/32448554/136032348-8ab200ab-0a4f-4e28-ad19-e91e3529392f.png)

**Comment by xpilasav** [comment]
Version 93.0.4577.82 (Official Build) (64-bit)
Let me update my Chrome to check

**Comment by xpilasav** [comment]
Sorry, updated to Version 94.0.4606.71 (Official Build) (64-bit)
And I still have the issue
![image](https://user-images.githubusercontent.com/42935528/136034171-c8cd2817-5168-47a5-a218-039f9c82ca9e.png)

**Comment by xpilasav** [comment]
Forget it, I went to manually clean the cache (not with Chrome but with another tool) and it fixed the issue
Restart, refresh and few other Chrome settings update didn't work until the external cleaning

**Comment by bloussou** [comment]
Can you share your python environment ? (`conda list`, `pip list` or `poetry.lock`)
