### ISSUE TITLE
Table.load_sql hangs

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#382]
When columns in the source sql table have changed, then atoti load_sql hangs indefinitely. 

Expected result: finish execution and create a record in the loading report saying there were issues loading the data.

--
## Steps to reproduce

1. Create a table with a predefined list of columns
2. Attempt to load data from an sql db using table.load_sql(sql statement)

## Actual Result

The cell with table.load_sql never finishes
In the log there is a message saying that number of columns in the source is x versus y in the table.

# Expected result

finish execution and say “127654 records failed loading, check loading report”

**Comment by bloussou** [comment]
Hello,
Thanks for the issue. I did not managed to reproduce this. 
- Which version of atoti are you using ? I'm not able to reproduce this in `0.6.2`. 
- Are all the names in sql and atoti table different ? Can you share the schema of the atoti and sql table ?
- Can your share the logs ?

**Comment by tibdex** [comment]
Closing because we couldn't reproduce. Feel free to reopen if the issue is still there.
