### ISSUE TITLE
Add support for logout in Atoti+

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#386]
## Steps to reproduce
With Atoti+, once you configured the security there is no log out button.

## Environment

- atoti: 0.6.2
- Operating System: win32

**Comment by jnd77** [comment]
For my current project, which is based on OIDC, the client has a set of tests, and it includes logging out. So that would be really helpful to have this function soon, as I'm not sure how difficult it will be to waive this test.

**Comment by tibdex** [comment]
What would the client expect from logging out when using OIDC:
- Remove the Spring session cookie with the limitations described above.
- Revoke the atoti application from the authorized ones in the OIDC provider (like if you were to revoke an authorized OAuth app such as CircleCI in [your GitHub settings](https://github.com/settings/applications)).
- Both.

?

**Comment by jnd77** [comment]
Based on the limitations you mentioned in the first message, then I would expect both.

Test is as follows:
If user logs out and reloads the URL, then he would have to identify again.

**Comment by tibdex** [comment]
We can take the example of CircleCI and its "Log in with GitHub" feature relying on the OAuth2 protocol (OIDC is a layer on top of OAuth2):

The log out button on CircleCI only clears the session on their side, when you go back to CircleCI and click on "log in with GitHub" you're logged in again without being redirected to GitHub's approval page. If you want to truly log out, you need to go to your GitHub settings and remove the integration with CircleCI. CircleCI can't do this for you.

I think we should do the same thing in Atoti+. We should add a "log out" button to the app that would hit (or redirect to) a `/logout` endpoint on the atoti server which would clear the session cookie and respond with a page saying something like "You've been logged out". To truly be logged out, like in the previous example, a user would also need to remove the integration of this atoti session on the OIDC provider. We shouldn't do it for them either.
