### ISSUE TITLE
create_date_hierarchy mapped some dates wrongly

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#388]
## Steps to reproduce
This is raised on behalf of a community user but I have encountered similar issues before.

When creating a date hierarchy, some of the dates are carried over to some other dates incorrectly
```
tt.experimental.create_date_hierarchy(
    "Date parts",
    cube=SalesCube,
    column=Sale_table["InvoiceTxnDate"],
    levels={"Year": "Y", "Month": "MM", "Day": "dd"},
)
```

In the picture below, the Summary_date is the end of the month for a given month. As you can see the date is 2020-12-31, however, the date part function has shifted a few of the records over by 1 year to 2021-12.

![image](https://user-images.githubusercontent.com/35210495/138193784-5cddfeaa-52b8-4d62-b5f6-f0a3bb786472.png)

**Comment by HuifangYeo** [comment]
@bloussou 

I think I know the cause - Level `"Year": "Y"` should be `"Year": "yyyy"` instead.
Please see the attached example below where "Year": "Y"` is used and last few dates of the previous year got carried over to the next year:
![image](https://user-images.githubusercontent.com/35210495/138390746-df51cffe-ddc6-4c06-9cc4-6b19f97759a5.png)


[create_date_hierarchy.zip](https://github.com/atoti/atoti/files/7394141/create_date_hierarchy.zip)

**Comment by HuifangYeo** [comment]
@bloussou may I know if this issue will be fixed when the function becomes official?

**Comment by tibdex** [comment]
Isn't the issue that you used `Y` (capitalized) and thus ended up with a "week-based-year" rather than the "year-of-era" you would have had with `y` (lowercase)?

Note: these definitions come from the "date pattern" link in https://docs.atoti.io/0.6.3/lib/atoti.experimental.html#atoti.experimental.create_date_hierarchy.

**Comment by rcolle** [comment]
> Isn't the issue that you used `Y` (capitalized) and thus ended up with a "week-based-year" rather than the "year-of-era" you would have had with `y` (lowercase)?
The documentation's example uses `Y` (capitalized). It may be worth changing it if it's not the common use-case as many people will just copy the doc and assume it works without seeing the edge case.
