### ISSUE TITLE
`create_date_hierarchy()` raises a `There is already a trigger with requested name` error

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#389]
## Steps to reproduce

It seems that we can create multiple date hierarchies with the same date column using `atoti.experimental.create_date_hierarchy`.
However, occasionally I get the exception similar to `There is already a trigger with requested name Set date fields for store Dates id#0 in the trigger list of store Dates.`.

What are the duplication checks for creating multiple date hierarchies?

Also, supposed we hit the exception and we try to delete the created hierarchies, we are not allowed to re-create the date hierarchy without restarting the kernel. Is this the expected behaviour?

![del_date_hierarchy](https://user-images.githubusercontent.com/35210495/138197260-4716c69e-5a5c-4bce-8a1b-3b0762576ba6.gif)

## Environment

- atoti: 0.6.3.20211011091646
- Python: 3.9.7
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang, are you still facing this issue? Could you share a minimal reproducible example?

**Comment by bloussou** [comment]
Hello,
this is minimal reproducible example:
```python
import atoti as tt
import pandas as pd
from datetime import date

session = tt.Session()
table = session.read_pandas(
    pd.DataFrame({
        "date": [date(1996,1,13)]
    }),
    table_name="Table"
)
cube = session.create_cube(table)
cube.create_date_hierarchy("Date", column=table["date"]) # OK
cube.create_date_hierarchy("Date", column=table["date"]) # THROW
```
