### ISSUE TITLE
java.lang.IllegalStateException: Bad insertion of new node CachedPrimitiveAggregationNode 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#390]
## Steps to reproduce

I have the following schema:
![image](https://user-images.githubusercontent.com/35210495/138253945-f0c399f8-ca83-4ccb-bd57-f6811debc41a.png)

I created the following measure: 
         `m["Total sum insured"] = m["SUM_INSURED.SUM"] + m["Add. sum insured"]`
where 
         `m["SUM_INSURED.SUM"]` is from base table and created automatically during cube creation
         `m["Add. sum insured"] = tt.agg.sum(addons_tbl["ADD_SUM_INSURED"])`

I am able to create the pivot table below:

![image](https://user-images.githubusercontent.com/35210495/138254453-3b6c4d95-9c99-4c1c-acce-d1ff538e3c9f.png)

However, if I switch the sequence of the measures, I get the exception 
```java.lang.IllegalStateException: Bad insertion of new node CachedPrimitiveAggregationNode ```

![cachedprimitiveaggregationnode](https://user-images.githubusercontent.com/35210495/138255046-7a03b8ec-67ce-42ee-832c-27095ba4180f.gif)

Once I get the error message, it keeps coming back even after I remove the measures and put it back to the initial ordering.
I need to use a new cell to recreate the visualization.

## Environment
- atoti: 0.6.3.20211011091646
- Python: 3.9.7
- Operating System: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/7387967/server.log)

**Comment by bloussou** [comment]
Hello,
this will be available in the next release and is already available in continuous build
