### ISSUE TITLE
Unable to get Excel to connect

### ISSUE THREAD

**Issue by ncosgrov58** [atoti/atoti#392]
I am running atoti on an Azure server.  Doing a session.link returns http://**{IP address}**:8888/proxy/63450/ and I can access my dashboard from there with no issue.  I am trying to connect Excel using the xmla endpoint with no success, getting an error  message of  "Forbidden".  The URL I am using is http://**{IP address}**:8888/proxy/63450/xmla

Any help appreciated, been banging my head on this for a while

**Comment by ncosgrov58** [comment]
No joy, tried multiple variations. For reference to the link returned by session link is http://{ip address}:8888/proxy/{Session Port}

**Comment by tibdex** [comment]
Let's keep the discussion in a single place: #254.
