### ISSUE TITLE
Store joined to a intermediate store is not reflected in cube

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#4]
## Description
I have the below 3 stores:
netflix_store [key: "show_id"]
country_store [key: "show_id", "country"]
location_store [key: "country"]

neflix_store has a many-to-many relationship to country_store.
country_store has many-to-one relationship to location_store.

I am unable to see the hierarchy (country_code) and measures (longitude and latitude) from location_store after joining to country_store.

![image](https://user-images.githubusercontent.com/35210495/77529539-c83b4c80-6eca-11ea-8ca8-a157987d4a7b.png)

## Reproduce
Please see attached zip
[00_netflix.zip](https://github.com/atoti/atoti/files/4380428/00_netflix.zip)

## Context
- Atoti version: '0.2.0.20200323192733'
- Python version: 3.7.6
- Operating System: Windows 10 Pro

**Comment by fabiencelier** [comment]
To reproduce:

```python
import atoti as tt
import pandas as pd

session = tt.create_session()
dfa = pd.DataFrame({
    "a": ["a","b", "c"],
    "b": [10.0,20.0,30.0]
})
dfb = pd.DataFrame({
    "a": ["a","b", "c", "a", "b", "c"],
    "c": [1,1,1,2,2,2],
    "d": [100.0,200.0,300.0,400.0,500.0,600.0]
})
dfc = pd.DataFrame({
    "c": [1,2],
    "e": [1000.0,2000.0]
})
storeA = session.read_pandas(dfa, keys=["a"])
storeB = session.read_pandas(dfb, keys=["a", "c"])
storeC = session.read_pandas(dfc, keys=["c"])
storeA.join(storeB)
storeB.join(storeC)

cube = session.create_cube(storeA)
m = cube.measures
m["sumE"] = tt.agg.sum(storeC["e"])
```

**Comment by fabiencelier** [comment]
Hello @HuifangYeo 

This issue with joins will be fixed in the next release.
