### ISSUE TITLE
Custom logo is not working on Google Chrome

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#402]
## Description
Custom logo is not working on Google Chrome. I have tested with Mozilla Firefox from the same machine, it works.

## Actual Result
Private: https://drive.google.com/drive/folders/1wDVahJJF3cXi-jnx_SHMwXUyY5ij89jF?usp=sharing

## Environment
- atoti: 0.6.2
- Operating System: Linux
- Browser: Google Chrome

**Comment by Skyscimitar** [comment]
Could you add the logo file to the drive so we can try and reproduce the issue please

**Comment by Harold7665** [comment]
Done.

**Comment by Skyscimitar** [comment]
The logo needs to be an `svg` file in order to be displayed correctly. Firefox seems to be more tolerant than chrome on image formats.

**Comment by rcolle** [comment]
@Skyscimitar can this be enforced in the code so that it's easier to diagnose on the user side?
