### ISSUE TITLE
Topcount aggregation function

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#41]
## Context

This code sample is only useful to understand the use case of what I wanted to achieve:
```python
import atoti as tt
import numpy as np
import pandas as pd

session = tt.create_session()

drivers_df = pd.read_csv(
    "https://data.atoti.io/notebooks/formula-one/drivers.csv", encoding="latin-1"
)
drivers_df.rename(columns={"url": "driver_url"}, inplace=True)
drivers_df.rename(columns={"nationality": "driver_nationality"}, inplace=True)

drivers_store = session.read_pandas(
    drivers_df, keys=["driverId"], store_name="F1 drivers"
)

races_df = pd.read_csv(
    "https://data.atoti.io/notebooks/formula-one/races.csv", encoding="latin-1"
)
races_df.rename(columns={"url": "race_url"}, inplace=True)
races_df.rename(columns={"name": "race_name"}, inplace=True)

races_store = session.read_pandas(
    races_df, keys=["raceId"], store_name="F1 races"
)

constructors_df = pd.read_csv(
    "https://data.atoti.io/notebooks/formula-one/constructors.csv", encoding="latin-1"
)
constructors_df.rename(columns={"url": "constructor_url"}, inplace=True)
constructors_df.rename(columns={"name": "constructor_name"}, inplace=True)
constructors_df.rename(columns={"nationality": "constructor_nationality"}, inplace=True)

constructors_store = session.read_pandas(
    constructors_df,
    keys=["constructorId"],
    store_name="F1 constructors",
)

resultsTypes = {
    "points": tt.types.DOUBLE,
}

results_store = session.read_csv(
    "s3://data.atoti.io/notebooks/formula-one/results.csv",
    keys=["resultId"],
    store_name="F1 results",
    types=resultsTypes,
)

results_store.join(drivers_store, mapping={"driverId": "driverId"})
results_store.join(races_store, mapping={"raceId": "raceId"})
results_store.join(constructors_store, mapping={"constructorId": "constructorId"})

f1cube = session.create_cube(results_store, "F1Cube")
session.load_all_data()

lvl = f1cube.levels
m = f1cube.measures
h = f1cube.hierarchies
```

## Use Case

The use case is to calculate the [score of a given driver](https://en.wikipedia.org/wiki/List_of_Formula_One_World_Championship_points_scoring_systems) per year:
- Today the rule is simple: aggregate all points. So the score of a driver is given by `points.SUM`
- Before 1991, the score was calculated by taking all driver races over one year, and only count the best N among them.
  i.e. if I scored [8,2,6,3,2,6,2,2,4,2,2] over 11 races and we only count the best 5, the result would be `Score = 8+6+6+4+3 = 27`

Do you know any way to achieve that today?

## Suggestion

It could be solved for example with a topcount aggregation function:
```python
m["Score"] = tt.agg.topcount(m["points.SUM"], lvl["raceId"], 5)
```
Topcount is a common calculation done in MDX.

We also discussed at some point having a `sort`/`rank` function that would sort elements and return their position and then we could aggregate `where rank <= 5`. But I don't know if such a generalization would benefit other use cases. 

## Environment

- Atoti: 0.4.0.20200512194154
- Python: 3.8.2
- Operating System: linux

**Comment by fabiencelier** [comment]
I think top count is very specific, I prefer the idea of rank as it would be more flexible:
 - possible to combined it with other aggregation functions (mean, max, min)
 - more customed filters than only the top (lowest, rank X to Y...)

There is a way to achieve what you want with arrays and [n_greatest](https://docs.atoti.io/0.3.1/lib/atoti.html?highlight=n_greatest#atoti.array.n_greatest). Arrays can be built using the _vector aggregation function.

Here I show an example with 2 drivers and 8 races, taking the 4 best scores.
```python
import pandas as pd
import atoti as tt
df = pd.DataFrame({
    "score": [2.0,4.0,4.0,2.0,5.0,8.0,1.0,0.0, 6.0,0.0,0.0,0.0,2.0,4.0,5.0,7.0],
    "race": ["r1","r2", "r3", "r4", "r5", "r6", "r7", "r8", "r1","r2", "r3", "r4", "r5", "r6", "r7", "r8"],
    "driver": ["a","a","a","a","a","a","a","a","b","b","b","b","b","b","b","b"]
})
session = tt.create_session()
store = session.read_pandas(df)
cube = session.create_cube(store)
m = cube.measures

m["score array"] = tt.agg._vector(store["score"])
cube.query(m["score array"], levels=[cube.levels["driver"]])
m["top 4 races"] = tt.array.n_greatest(m["score array"], 4)
m["top 4 total"] = tt.array.sum(m["top 4 races"])

cube.query(m["score array"], m["top 4 races"], m["top 4 total"] , levels=[cube.levels["driver"]])
```
![driver score](https://user-images.githubusercontent.com/17087544/81957422-d37a4100-960c-11ea-9be3-f6450fe35249.png)

**Comment by a-manai** [comment]
Hello,

We have added the possibility to rank a level's members based on their values for a given measure. The ranking is done as in the following example:
```sql
id	|	value	|	rank
A		10		3
B		15		1
C		5		5
D		15		2
E		8		4
```
When two members have the same value, the one which comes first (in the level order) has highest rank.

Cheers
