### ISSUE TITLE
Unable to load data into scenario when table has no keys

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#410]
## Steps to reproduce

1 - I created a referenced table:
```
prediction_tbl = session.create_table(
    name="prediction",
    types={
        "trans_num": tt.type.STRING,
        "Label": tt.type.STRING,
        "Score": tt.type.FLOAT,
    },
    # keys=["trans_num"], 
)

txn_tbl.join(prediction_tbl, mapping={"trans_num": "trans_num"})
```
![image](https://user-images.githubusercontent.com/35210495/141598741-7278d4f8-a1d2-4ffd-a3ec-44aab5745b46.png)

2 - I load data into the prediction table 
3 - I create a source simulation:
```
prediction_tbl.scenarios["Logistic Regression"].load_pandas(
    lr_prediction[["trans_num", "Label", "Score"]]
)
```

### Problem 1:
I encountered the below exception when I try to run step 3 to load the scenario:
```
AtotiJavaException: Record [321c53a401db804354021fc3d9dfcbd3, 1, 0.9988](RecordView[384170, 3, 0.9988]) could not be inserted into partition 0 of store prediction, it has the same unique index as record [321c53a401db804354021fc3d9dfcbd3, 0, 0.7668](ColumnarRecordSetReader[384170, 2, 0.7668]) because the reference transactions_to_prediction enforces that records with different primary keys (fields:[], values: []) must have different values on the following fields: [trans_num], values: [321c53a401db804354021fc3d9dfcbd3]
```

### Problem 2 (I wasn't able to replicate in the attached example)
If I set `trans_num` as the key to the prediction table, I am able to load the scenario.
However, even though `prediction_tbl.head()` shows data correctly loaded into the table, Label and Score shows N/A when I query the cube.

## Environment
- atoti: 0.6.2
- Python: 3.8.12
- Operating System: win32

**Comment by HuifangYeo** [comment]
[sample program](https://drive.google.com/file/d/1Kgh7IjK3AC4555Kb5CnJa3_WuqKGClmB/view?usp=sharing)

**Comment by bloussou** [comment]
Hello,
I didn't get how you want it to work if `trans_num` is not a key of `prediction table`. How is the join supposed to know which value it is supposed to used for a `trans_num` key that is twice in the prediction table in your scenario ? What is the use case of not having `trans_num` as a key of the table ?

**Comment by HuifangYeo** [comment]
As I mentioned, initially I had wanted to set `trans_num` as key. But somehow, even though the atoti table showed value, when I queried the cube, it's showing N/A for both the label and score (Problem 2). 

But eventually, I figured out that it may be due to duplicated columns in the table (bug on my side). I'll proceed to close the ticket.
