### ISSUE TITLE
at function: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#413]
## Steps to reproduce

I have the following schema:
![image](https://user-images.githubusercontent.com/35210495/142593638-79a4c4cb-9bba-4627-98c4-316c361083d5.png)

When I create a measure using `at`, and I query at the mentioned levels, I encountered: 
```
{'type': 'ArrayIndexOutOfBoundsException', 'message': 'Index 1 out of bounds for length 1'}
```

Source code: [sbm.zip](https://github.com/atoti/atoti/files/7568999/sbm.zip)

## Environment

- atoti: 0.6.3
- Python: 3.8.12
- Operating System: win32

## Logs (if relevant)

[server.log](https://github.com/atoti/atoti/files/7568991/server.log)
<details><pre>
RuntimeError: ('Request failed', {'status': 'error', 'error': {'errorChain': [{'type': 'ArrayIndexOutOfBoundsException', 'message': 'Index 1 out of bounds for length 1'}, {'type': 'PostProcessorEvaluationException', 'message': 'An exception occurred during evaluation of post-processed measure _temp on location AllMember\\[*]|AllMember|AllMember|AllMember|AllMember|AllMember|AllMember\\[*]'}, {'type': 'RuntimeException', 'message': 'com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure _temp on location AllMember\\[*]|AllMember|AllMember|AllMember|AllMember|AllMember|AllMember\\[*]'}, {'type': 'RuntimeException', 'message': 'java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure _temp on location AllMember\\[*]|AllMember|AllMember|AllMember|AllMember|AllMember|AllMember\\[*]'}, {'type': 'QueryException', 'message': 'Could not execute query at epoch 13. : ActivePivotSyncActionQuery: action=MdxAction (mdx=SELECT {[Measures].[_temp]} ON COLUMNS, NON EMPTY Crossjoin([Risks].[Bucket].[Bucket].Members, [eq_delta_corr_outer].[Other Bucket].[Other Bucket].Members) ON ROWS FROM [test_cube]), argument=com.quartetfs.pivot.mdx.impl.BasicSelectExecutor@1e5518db'}, {'type': 'MdxException', 'message': 'Error with the following query: SELECT {[Measures].[_temp]} ON COLUMNS, NON EMPTY Crossjoin([Risks].[Bucket].[Bucket].Members, [eq_delta_corr_outer].[Other Bucket].[Other Bucket].Members) ON ROWS FROM [test_cube]'}, {'type': 'BadArgumentException', 'message': '[400] com.quartetfs.pivot.mdx.MdxException: Error with the following query: SELECT {[Measures].[_temp]} ON COLUMNS, NON EMPTY Crossjoin([Risks].[Bucket].[Bucket].Members, [eq_delta_corr_outer].[Other Bucket].[Other Bucket].Members) ON ROWS FROM [test_cube]'}], 'stackTrace': 'com.qfs.fwk.services.BadArgumentException: [400] com.quartetfs.pivot.mdx.MdxException: Error with the following query: SELECT {[Measures].[_temp]} ON COLUMNS, NON EMPTY Crossjoin([Risks].[Bucket].[Bucket].Members, [eq_delta_corr_outer].[Other Bucket].[Other Bucket].Members) ON ROWS FROM [test_cube]\r\n\tat com.qfs.pivot.rest.query.impl.JsonQueryService.executeQuery(JsonQueryService.java:224)\r\n\tat com.qfs.pivot.rest.query.impl.JsonQueryService.executeMdxQuery(JsonQueryService.java:116)\r\n\tat com.qfs.pivot.rest.query.impl.QueriesRestService.mdxQuery(QueriesRestService.java:65)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)\r\n\tat org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)\r\n\tat org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)\r\n\tat org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)\r\n\tat org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)\r\n\tat org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)\r\n\tat org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)\r\n\tat org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)\r\n\tat org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)\r\n\tat org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)\r\n\tat org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)\r\n\tat org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)\r\n\tat org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)\r\n\tat org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)\r\n\tat org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:665)\r\n\tat org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)\r\n\tat org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:166)\r\n\tat org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)\r\n\tat org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)\r\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)\r\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)\r\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\r\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:665)\r\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:750)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\r\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\r\n\tat com.qfs.pivot.servlet.impl.ContextValueFilter.doFilter(ContextValueFilter.java:67)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\r\n\tat org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)\r\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\r\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)\r\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\r\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\r\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)\r\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)\r\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)\r\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)\r\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)\r\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)\r\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\r\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)\r\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)\r\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)\r\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\r\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)\r\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\r\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\r\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n\tat java.base/java.lang.Thread.run(Unknown Source)\r\nCaused by: com.quartetfs.pivot.mdx.MdxException: Error with the following query: SELECT {[Measures].[_temp]} ON COLUMNS, NON EMPTY Crossjoin([Risks].[Bucket].[Bucket].Members, [eq_delta_corr_outer].[Other Bucket].[Other Bucket].Members) ON ROWS FROM [test_cube]\r\n\tat com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.executeAfterParse(ASelectStatementExecutor.java:444)\r\n\tat com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.executeAfterParse(ASelectStatementExecutor.java:426)\r\n\tat com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.execute(ASelectStatementExecutor.java:415)\r\n\tat com.qfs.pivot.rest.query.impl.JsonQueryService$JsonSelectExecutor.execute(JsonQueryService.java:423)\r\n\tat com.qfs.pivot.rest.query.impl.JsonQueryService$JsonSelectExecutor.execute(JsonQueryService.java:401)\r\n\tat com.qfs.pivot.rest.query.impl.JsonQueryService.executeQuery(JsonQueryService.java:219)\r\n\t... 69 more\r\nCaused by: com.quartetfs.fwk.query.QueryException: Could not execute query at epoch 13. : ActivePivotSyncActionQuery: action=MdxAction (mdx=SELECT {[Measures].[_temp]} ON COLUMNS, NON EMPTY Crossjoin([Risks].[Bucket].[Bucket].Members, [eq_delta_corr_outer].[Other Bucket].[Other Bucket].Members) ON ROWS FROM [test_cube]), argument=com.quartetfs.pivot.mdx.impl.BasicSelectExecutor@1e5518db\r\n\tat com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.getWithQueriesTimeLimit(ActivePivotVersion.java:1515)\r\n\tat com.quartetfs.biz.pivot.impl.ActivePivotVersion.execute(ActivePivotVersion.java:933)\r\n\tat com.quartetfs.biz.pivot.query.impl.ActivePivotSyncUtils.activePivotSyncExec(ActivePivotSyncUtils.java:93)\r\n\tat com.quartetfs.pivot.mdx.impl.ASelectStatementExecutor.executeAfterParse(ASelectStatementExecutor.java:442)\r\n\t... 74 more\r\nCaused by: java.lang.RuntimeException: java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure _temp on location AllMember\\[*]|AllMember|AllMember|AllMember|AllMember|AllMember|AllMember\\[*]\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)\r\n\tat com.quartetfs.biz.pivot.impl.ActivePivotVersion$QueryExecutionTask.getWithQueriesTimeLimit(ActivePivotVersion.java:1486)\r\n\t... 77 more\r\nCaused by: java.lang.RuntimeException: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure _temp on location AllMember\\[*]|AllMember|AllMember|AllMember|AllMember|AllMember|AllMember\\[*]\r\n\tat java.base/java.util.concurrent.ForkJoinTask.completeExceptionally(Unknown Source)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.performExceptionalCompletion(CancellableCountedCompleter.java:313)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:297)\r\n\tat java.base/java.util.concurrent.CountedCompleter.tryComplete(Unknown Source)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterCompute(CancellableCountedCompleter.java:150)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterExec(CancellableCountedCompleter.java:177)\r\n\tat com.quartetfs.biz.pivot.context.impl.ContextualCancellableCountedCompleter.afterExec(ContextualCancellableCountedCompleter.java:123)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.compute(CancellableCountedCompleter.java:200)\r\n\tat java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)\r\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)\r\nCaused by: com.quartetfs.biz.pivot.postprocessing.PostProcessorEvaluationException: An exception occurred during evaluation of post-processed measure _temp on location AllMember\\[*]|AllMember|AllMember|AllMember|AllMember|AllMember|AllMember\\[*]\r\n\tat com.quartetfs.biz.pivot.query.aggregates.plan.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:187)\r\n\tat com.quartetfs.biz.pivot.query.aggregates.plan.impl.PostProcessedAggregatesRetrieval.completeResult(PostProcessedAggregatesRetrieval.java:312)\r\n\tat com.quartetfs.biz.pivot.query.aggregates.plan.impl.AAggregatesRetrieval.onRegularCompletion(AAggregatesRetrieval.java:159)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:282)\r\n\tat com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$ParentsCompleter.tryCompleteParents(MultiCancellableCountedCompleter.java:257)\r\n\tat com.qfs.concurrent.cancellable.impl.MultiCancellableCountedCompleter$ParentsCompleter.onRegularCompletion(MultiCancellableCountedCompleter.java:357)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.onCompletion(CancellableCountedCompleter.java:282)\r\n\tat java.base/java.util.concurrent.CountedCompleter.tryComplete(Unknown Source)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterCompute(CancellableCountedCompleter.java:150)\r\n\tat com.qfs.concurrent.cancellable.impl.CancellableCountedCompleter.afterExec(CancellableCountedCompleter.java:177)\r\n\t... 7 more\r\nCaused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1\r\n\tat com.qfs.column.impl.SparseChunkedColumn.getWritableChunk(SparseChunkedColumn.java:114)\r\n\tat com.qfs.column.impl.AChunkedColumn.writeLong(AChunkedColumn.java:294)\r\n\tat com.activeviam.util.cells.impl.AArrayCursor.writeLong(AArrayCursor.java:100)\r\n\tat com.activeviam.pivot.postprocessing.PostProcessorUtils.lambda$createPrimitiveTypeBiConsumerAtSpecificIndex$f8c3f880$5(PostProcessorUtils.java:86)\r\n\tat com.quartetfs.biz.pivot.postprocessing.impl.ALocationShiftPostProcessor.evaluate(ALocationShiftPostProcessor.java:250)\r\n\tat com.quartetfs.biz.pivot.postprocessing.impl.ALocationShiftPostProcessor$EvaluationProcedure.execute(ALocationShiftPostProcessor.java:419)\r\n\tat com.quartetfs.biz.pivot.cellset.impl.PointListRetrievalResult.forEachPoint(PointListRetrievalResult.java:936)\r\n\tat com.quartetfs.biz.pivot.postprocessing.impl.ALocationShiftPostProcessor.compute(ALocationShiftPostProcessor.java:210)\r\n\tat com.quartetfs.biz.pivot.query.aggregates.plan.impl.PostProcessedAggregatesRetrieval.evaluate(PostProcessedAggregatesRetrieval.java:173)\r\n\t... 16 more\r\n'}})
</pre></details>

**Comment by bloussou** [comment]
Tracked in this internal ticket https://support.activeviam.com/jira/browse/PIVOT-5161

**Comment by Acriss** [comment]
Hello !
The internal fix was merged this afternoon.
Cheers,
Pierre
