### ISSUE TITLE
DB Connection leaks

### ISSUE THREAD

**Issue by chenna-reddy** [atoti/atoti#415]
Atoti isn't releasing DB connections once it loads data from DB.

## Steps to reproduce

```
import atoti as tt


def start():
    session = tt.create_session()
    url = f"...jdbc URL..."
    table = session.create_table("DummyTable", keys=["ID"], types={"ID": tt.type.STRING})
    for x in range(20):
        table.drop()
        table.load_sql("select DUMMY ID from dual", url=url)
    session.wait()
```

## Actual Result

The table contains data but held 20 open connections to DB.

## Expected Result

I would expect the Atoti to close all connections to DB.

**Comment by Skyscimitar** [comment]
Hi, the fix for this issue has been merged and will be available in the next release of atoti.

**Comment by chenna-reddy** [comment]
Any idea on the next release date?
 - Because of this bug, I can't reload the Data
 - Because of [Cube creation times grow exponentially](https://github.com/atoti/atoti/issues/445) restarting the application isn't an option.

Looking forward to one of them being fixed at least.

**Comment by bloussou** [comment]
Hello,
We will release soon (mid January). This one will be fixed and I'm working on the second one at this time.
Sorry for the delay we will do this as soon as possible !
