### ISSUE TITLE
Int type level fallback value: zero vs N/A

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#42]
## Use case

Let's consider the following join:
![image](https://user-images.githubusercontent.com/4415696/81923613-3ef8ea00-95de-11ea-9130-8dbaef16457a.png)

If I have some score for which there is no existing `race_id`, `Year` will default to 0.

Sample code:
```python
import pandas as pd

main_df = pd.DataFrame(
    data={
        "race_id": [1, 5, 0, 2],
        "Name": ["John", "Robert", "Thomas", "Mike"],
        "Score": [10, 8, 5, 12],
    }
)

race_df = pd.DataFrame(
    data={
        "id": [0, 1, 2],
        "Name": ["Alpha", "Beta", "Gamma"],
        "Year": [2017, 2018, 2019],
    }
)

import atoti

session = atoti.create_session()

race_store = session.read_pandas(race_df)
main_store = session.read_pandas(main_df, types={"Score": atoti.types.DOUBLE})
main_store.join(race_store, mapping={"race_id": "id"})

cube = session.create_cube(main_store)
```

![image](https://user-images.githubusercontent.com/4415696/81923951-b9c20500-95de-11ea-9e3e-1b31658205c1.png)

## Enhancement

While I understand why the value is zero (the original type is int, and it would be useful if I decide to aggregate it), in this specific case described above I would like to default it to something more explicit like `2020` or `N/A`. I initially thought the value `0` came from the data source.

The easy fix is to force the type of `Year` to be a string, and then I get `N/A`:
![image](https://user-images.githubusercontent.com/4415696/81931238-0fe87580-95ea-11ea-94e3-70991243f677.png)

I could also alter the data to define the missing `race_id` or remove the data from the main store with an unknown `race_id`.

I might be nitpicking but even when the underlying type is INT, if I use the field in a hierarchy, I think people would prefer to see `N/A` rather than `0`.

**Comment by fabiencelier** [comment]
The type INT forces the values to be an int, if you want values such as "N/A" you have to use strings. If you don't plan to use it as a measure there is no drawback in using Strings.

We could improve our types API to support changing the default value so you could default to another int than 0 but I don't see a huge benefits in this at the moment.

**Comment by jbe456** [comment]
>The type INT forces the values to be an int, if you want values such as "N/A" you have to use strings. If you don't plan to use it as a measure there is no drawback in using Strings.

You just highlighted the (albeit small) improvement you could make: if I use an INT field as a level, it would default to N/A as a member, while if I use it as a measure it would default to 0.

The workaround is easy (change the type to string). So if it's too much of a hassle to do this change with the existing stack you may close it as won't fix/postponed.
