### ISSUE TITLE
Cumulative value for levels below scope

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#422]
## Steps to reproduce

I've pre-computed the cumulative number of transactions with Pandas and I am able to see the cumulative value by date up to the time level. In this case, when I add the `trans_num` , I'm still able to see the number of accumulated transactions up till the transaction itself:
![image](https://user-images.githubusercontent.com/35210495/143852901-b2256d2c-b157-44c6-b052-79325283d2c3.png)

However, I would like to do the cumulative aggregation within atoti, instead of Pandas. 
But by doing so, you can see that I do not have the cumulative value on the `trans_num` level. 
![image](https://user-images.githubusercontent.com/35210495/143853026-4ff7c209-6b9e-402a-b4c6-9ed3ec9434e5.png)

Is there a way for me to achieve the same? I had wanted to export the cumulative value with the `trans_num` as my key for machine learning (and reimporting in to atoti later on).

[cumulative.zip](https://github.com/atoti/atoti/files/7617789/cumulative.zip)

## Environment
atoti: 0.6.3
Python: 3.8.12
Operating System: win32

**Comment by rcolle** [comment]
Hi Huifang,

In the first example, the aggregation doesn't work does it? It's correct at the trans_num/trans_time level but doesn't add up correctly at higher levels.

Regarding the cumulative part, it looks like you want the aggregation to be done at the trans_date/trans_time level, instead of only trans_date. So you likely want to create a multi-level hierarchy. You also need trans_num to be of LocalDateTime / datetime type in this case.

**Comment by HuifangYeo** [comment]
Hi Romain,

you are right on the aggregation for the first example. Therefore, it makes more sense to perform cumulative aggregation in atoti.

`trans_num` can't be translated to datetime type. So I guess it's not possible in this case to get the cumulative value at the transaction level by date. 

I tried apply cumulative on DateTime level, but I can't explain its behaviour: https://github.com/atoti/atoti/issues/396#issuecomment-956100778

**Comment by rcolle** [comment]
> You also need trans_num to be of LocalDateTime / datetime type in this case.

Sorry that's a typo I meant trans_time. 
So that you can build a trans_date/trans_time hierarchy to perform the cumulative sum.
