### ISSUE TITLE
Cumulative aggregation with date window is incorrect when the date level does not use the ASCENDING comparator

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#424]
## Steps to reproduce

I'm working with comparators in descending order for the `trans_date` and I would like to get cumulative values for the current day, past 7 days and past 30 days.  

The cumulative window for "next members" in days is not working correctly once we apply the comparators on the `trans_date`:
![image](https://user-images.githubusercontent.com/35210495/143857223-5a4dea53-f390-414d-8dc0-63489bc5be55.png)

[cumulative.zip](https://github.com/atoti/atoti/files/7617759/cumulative.zip)

## Environment

atoti: 0.6.3
Python: 3.8.12
Operating System: win32

**Comment by tibdex** [comment]
I can reproduce with a simpler case:

```python
m["DateRangeSum"] = tt.agg.sum(
    m["f5.SUM"],
    scope=tt.scope.cumulative(l["f1"], window=("-3M", None)),
)
date_cube.query(m["DateRangeSum"], m["f5.SUM"], levels=[l["f1"]])
```

gives:

```
           DateRangeSum   f5.SUM
f1                              
2000-01-01       100.00   100.00
2000-03-10       300.00   200.00
2000-05-20       500.00   300.00
2000-09-20      -200.00  -200.00
2001-01-02       150.00   150.00
```

but after doing:

```python
l["f1"].comparator = tt.comparator.DESCENDING
```

the same query then returns:

```
           DateRangeSum   f5.SUM
f1                              
2001-01-02       150.00   150.00
2000-09-20       -50.00  -200.00
2000-05-20       250.00   300.00
2000-03-10       450.00   200.00
2000-01-01       550.00   100.00
```

The order of the values of **DateRangeSum** should been reversed but the values should have stayed the same.
The fact that the date level has a descending comparator shouldn't impact date window aggregations.

**Comment by bloussou** [comment]
Bug was here also in `0.6.2`
