### ISSUE TITLE
Wrong result after migration to 0.6.4

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#426]
## Steps to reproduce
Hello, 
If you run the notebook https://github.com/activeviam/python-saccr-demo/tree/upgrade_to_0.6.2 on 0.6.2 or https://github.com/activeviam/python-saccr-demo/tree/master on 0.5.1, you get right calculation results.
You can get the data and maybe additional information here: https://drive.google.com/file/d/1IWy3wvRD2OXksqIKj6h-06mcT9iEXn3I/view?usp=sharing

## Actual Result
Different calculation results on the last 0.6.4 nightly available today.

## Expected Result
Same calculation results.

**Comment by tibdex** [comment]
Hi Harold, can you share more information to save us time? For instance which cell to look at in which notebook to see the different results?

**Comment by Harold7665** [comment]
Hi Thibault, sure. 
You can run the whole 0.6.4 notebook then look at the first ActiveUI dashboard, page 1, and compare with the first page of the 1.Overview.pdf in the attached zip (it contains all the dashboards exported in 0.5.1, results are same in 0.6.2).
[SACCR upgrade.zip](https://github.com/atoti/atoti/files/7633352/SACCR.upgrade.zip)

**Comment by Harold7665** [comment]
Update: the master branch is now on version 0.6.2 (https://github.com/activeviam/python-saccr-demo)
I keep the 0.5.1 on Google Drive https://drive.google.com/file/d/1IWy3wvRD2OXksqIKj6h-06mcT9iEXn3I/view?usp=sharing ig it can help working on this ticket.

**Comment by Acriss** [comment]
Hey Harold,
I'll have a look at it !
Cheers

**Comment by Acriss** [comment]
Hey Harold,
A fix has been found and merged. Next release will contain the fix !
Cheers,
Pierre
