### ISSUE TITLE
Custom Sort order for Levels of the Cube

### ISSUE THREAD

**Issue by chenna-reddy** [atoti/atoti#429]
## Description

As of now, a Cube Level can have one following orders
 - ASCENDING
 - DESCENDING
 - FIRST_MEMBERS

Please add support for 
 - **AS_IS** (Elements are already sorted, Don't sort them)
 - **Lambda-based**. It should be possible to specify a custom Comparator (think Java Comparator implementation). *This is nice to have*

## Context

In a few scenarios, existing comparators are not good enough to sort the values.
For e.g. Time buckets can be 
 1.  1 day, 1 week, 2 weeks, 1month, 3 months, 6 months, 1 year.
 2. 1d, 2d, 3d....10d, 11d,... 365d, 366d

When the element set is smaller (1st example above), FIRST_MEMBERS can work. However, it's very difficult to specify everything for the 2nd example, and it doesn't scale well. 

Imagine there is an **AS_IS** comparator, data can be already sorted using Python code, or get it in sorted order from source and feed to the table.

**Comment by tibdex** [comment]
The thing is that the order of insertion of the rows cannot be retrieved when [tables are partitioned](https://docs.atoti.io/0.6.3/lib/atoti.session.html#atoti.session.Session.create_table). So the `AS_IS` comparator as you described cannot be implemented. You'll have to stick to `first_members()` and be exhaustive.

For the lambda-based comparator, it would indeed offer maximum flexibility but at the cost of performance. Indeed, the aggregation engine of atoti is developed in Java and calling the Python lambda from Java would be much slower than what a declarative comparator such as `ASCENDING`, `DESCENDING`, or `first_members()` can offer (no roundtrips needed).

**Comment by chenna-reddy** [comment]
Thanks, I will stick with `first_members()` for now.

Another idea is to support sorting a field based on another field in the same table.  

For example for the same time bucket problem above, I can have 2 columns in same table:
 - `TimeBucketStartDateInDays` (1, 7, 14, 30, 60,...365...)
 - `TimeBucketLabel` (1d, 1w, 2w, 1m, 2m,.. 1y...)
`TimeBucketLabel` should be sorted based on `TimeBucketStartDateInDays`.

Guess this will work for Partitioned tables and is possible to handle in Java.
