### ISSUE TITLE
Change user access permissions on each dashboard

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#430]
## Steps to reproduce

Opening the homepage of Atoti+, I don't have a way to setup the user or group access on any dashboard.

## Actual Result

No option allowed with Atoti+ to select who can access or edit a dashboard

## Expected Result

Have a UI to choose Edit and Read for a dashboard

## Environment

- atoti: 0.6.3 (Atoti+)
- Operating System: Windows
- Browser: Chrome

**Comment by xpilasav** [comment]
Can we get a date for this feature ?

**Comment by tibdex** [comment]
[Your user need to have the `ROLE_SHARE` role to be able to use this feature](https://activeviam.com/activeui/documentation/5.0.5/docs/user-guides/exporting-and-sharing/#share-popup).

**Comment by xpilasav** [comment]
Thank you
