### ISSUE TITLE
Allow conditional formatting on cells of pivot tables

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#432]
## Description

Users would like to be able to add conditional formatting on cells of pivot tables

## Context

Similar to Excel, being able to color cells based on conditions would be a huge plus

**Comment by mtadams007** [comment]
This looks similar to an internal ticket we have [here](https://support.activeviam.com/jira/browse/UI-6565).

**Comment by xpilasav** [comment]
Yes it does....
Always a challenge to know where to report a ticket for a client using Atoti+. Let me close it

**Comment by xpilasav** [comment]
But still would love to know a date/target on this feature...

**Comment by mtadams007** [comment]
Hi @xpilasav, I believe it's one of the next developments we're working on. It's not currently on the internal [roadmap](https://support.activeviam.com/jira/secure/Dashboard.jspa?selectPageId=17693) but I believe we will be adding it there soon.
