### ISSUE TITLE
CSV parsing issue when cell contain \r

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#437]
## Steps to reproduce
Hello,
I am loading CSV files and a few cells contain a \r. This is well managed by Excel or Pandas but atoti is creating a second row from this character instead.

## Actual Result
1 row is splitted into 2 rows where the \r is, even between double quotes, with or without process_quotes option.

## Expected Result
1 row loaded.

## Environment
- atoti: 0.6.4.2968.20211209112808
- Python: 3.10.0
- Operating System: linux

**Comment by bloussou** [comment]
Hello,
I cannot reproduce this issue :
![image](https://user-images.githubusercontent.com/32448554/147198590-2f8a2c3e-501f-44b3-b125-802ec80fcffc.png)

Can you share a csv sample to reproduce this ?

**Comment by bloussou** [comment]
@Harold7665 did you manage to reproduce this or can I close this issue ?

**Comment by Harold7665** [comment]
Hello,
Please do not close it, have you done your tests with a cell value surrounded by quotes in a CSV file?
Like: "id_1", "first line \r second line", "name_1"

**Comment by bloussou** [comment]
for me it is working with both :
```csv
"id_1","id_2"
"first line \r second line",2
"name_1",3
```
and
```csv
id_1,id_2
first line \r second line,2
name_1,3
```

**Comment by Harold7665** [comment]
Unfortunately I do not find the data anymore... You can close the ticket and I will reopen it f I have an example to provide, thanks!
