### ISSUE TITLE
JVM Memory report logs are missing

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#439]
## Steps to reproduce
I have used a notebook on this atoti version: 0.6.4.2968.20211209112808.

## Actual Result
Not more JVM Memory report logs.

## Expected Result
JVM Memory report logs every 30 seconds.

## Environment
- atoti: 0.6.4.2968.20211209112808
- Python: 3.10.0
- Operating System: linux

**Comment by bloussou** [comment]
Fixed in `0.6.4` by https://github.com/activeviam/atoti/pull/3020

**Comment by dufferzafar** [comment]
@bloussou That link 404s now. Can you pls guide me towards how I can view the jvm memory logs?

**Comment by tibdex** [comment]
They are intertwined with the regular server logs that you can find in `Session.logs_path`. They look like this:

> 2024-03-12T10:22:58.095-04:00  INFO 79020 --- [activepivot-health-event-dispatcher] c.a.h.m.ILoggingHealthEventHandler       : [jvm, memory] INFO 2024-03-12T14:22:58.090Z uptime=32519ms com.activeviam.health.monitor.impl.JvmHealthCheck.createEvent:61 thread=activeviam-health-check-worker thread_id=37 event_type=JvmMemoryReport JVM Memory Usage report: G1 Young Generation[count=20 (+0), time=0s (+0)]  G1 Old Generation[count=0 (+0), time=0s (+0)]  Heap[used=28 MiB 630 KiB (30005248) (+(0)), committed=224 MiB (234881024) (+(0)), max=9 GiB (9663676416) (+(0))]  Direct[used=9 MiB 762 KiB (10218304) (+(0)), count=74 (+0), max=9 GiB (9663676416) (+(0))]  Threads[count=58 (+0), peak=59 (+0)]
