### ISSUE TITLE
Improve copy_tutorial step

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#44]
## Description

Reported by several first time users. When following the tutorial on https://docs.atoti.io/0.3.1/tutorial.html:

![image](https://user-images.githubusercontent.com/4415696/82183690-bb454300-98e6-11ea-9c83-4e53d51e037f.png)

It's not clear what it does and users do not know that a new folder is created. What would be great is:
1. add an additional sentence in the documentation mentioning that this will create a new folder called "tutorial" at the same location you are running the notebook from.
1. add some message feedback from the notebook like : "Tutorial created at `${full_path}`. Check out `${full_path}/01. Getting Started.ipynb`"

Also, should it be `copy_tutorial` or `create_tutorial`?

**Comment by fabiencelier** [comment]
We have realized that running the command in a notebook is confusing as the user wants to keep this notebook and keep copy-pasting. In the next release we have added this command that can be run from command line:
```bash
python -m atoti.copy_tutorial tutorial
```
It then logs where the tutorial has been copied
We have also clarified a bit this part of the documentation
