### ISSUE TITLE
Weird total behaviour on the cumulation scope of vector

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#442]
## Steps to reproduce

```
import atoti as tt
from atoti.agg import sum
from atoti.scope import cumulative
from atoti.array import mean
import pandas as pd
session = tt.create_session()
df= pd.DataFrame({
    "l1": [f"{i}" for i in range(100)],
    "m1": [10.0 for i in range(100)],
    "m2": [[10.0 for i in range(10)] for j in range(100)]
})
table = session.read_pandas(
    df, 
    keys=["l1"],
    table_name="test", 
)
cube = session.create_cube(table, mode="no_measures")
m, l = cube.measures, cube.levels

m["ok_scalar"] = sum(sum(table["m1"]), scope=cumulative(l["l1"]))
m["ok_vector"] = sum(mean(sum(table["m2"])), scope=cumulative(l["l1"]))
m["not_ok_vector"] = mean(sum(sum(table["m2"]), scope=cumulative(l["l1"])))

# How come total of ok_vector and not_ok_vector are not the same ?
# total ok_vector: 1000, total not_ok_vector: 990
cube.query(m["ok_scalar"], m["ok_vector"], m["not_ok_vector"], levels=[l["l1"]], include_totals=True)
```

## Actual Result
![image](https://user-images.githubusercontent.com/47662440/146559922-3f64d760-6d1a-480d-b54c-9e932ddb124c.png)

## Expected Result
1000 for total of not_ok_vector
## Environment

- atoti: 0.6.3
- Python: 3.9.6
- Operating System: win32

**Comment by bloussou** [comment]
I'm investigating this, it is very strange it is false if you have more than 100 elements, total stops at the 99th...

**Comment by bloussou** [comment]
There is an issue we are investigating but something is weird in your example too. If you are not specifying comparators since `l1` is of type string the sorted list of `["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]` is `["1", "10", "2", "3", "4", "5", "6", "7", "8", "9"]`. So it is a bad idea to use String as key or you have to specify a first_members comparator.

**Comment by bloussou** [comment]
Hello,
This will be fixed in the next release.
