### ISSUE TITLE
The Copper level Level matches with more than one cube level when more than one table contain level

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#444]
## Steps to reproduce
I have the below schema:
![image](https://user-images.githubusercontent.com/35210495/146901939-9ae62649-71e3-48d6-a27a-ee003b1226d2.png)

I would like to get the top 5 salespeople with the highest sales per month. However, the option to do so from the atoti editor is only available when I am filtering on a multilevel hierarchy (please suggest if there are alternative ways):
![image](https://user-images.githubusercontent.com/35210495/146902536-7020a32e-a92d-49c2-bf8a-1d10968a5be3.png)

So, if I would like to have the top _n_ showroom per month, I would have to include it in a multilevel hierarchy as well.

```
h["Monthly Sales"] = [
    sales["Year"],
    sales["Month"],
    sales["Showroom_code"],
    salesperson["Salesperson_id"],
]
```

The above code snippets will throw the below exception:
```
AtotiJavaException: The Copper level Level[level=Showroom_code] matches with more than one cube level: [Level(Sales, Monthly Sales, Showroom_code), Level(Sales, Showroom_code, Showroom_code)]
```

**Questions:**
1. The error is thrown when we are creating the hierarchy `Monthly Sales`. Then the `Level(Sales, Monthly Sales, Showroom_code)` shouldn't have existed yet, isn't it?

2. How can I create the hierarchy then? `Level(Sales, Monthly Sales, Showroom_code)` nor `cube.levels["Sales", "Monthly Sales", "Showroom_code"]` works in this case.
 
3. Is it possible for me to do top count within categories without having to create multilevel hierarchies?

Source code: [car-commission.zip](https://github.com/atoti/atoti/files/7751102/car-commission.zip)

## Environment
- atoti: 0.6.3
- Python: 3.8.12
- Operating System: win32

**Comment by bloussou** [comment]
Hello @HuifangYeo,
Thanks for reporting this issue, it will be fixed in the next release.
