### ISSUE TITLE
summation of int type returns negative amount

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#447]
## Steps to reproduce

I created an atoti table:
```
car_pricing = session.read_csv(
    "sales_data/showroom_pricelist.csv",
    table_name="Car Prices",
    keys=["year", "month", "showroom_code", "model_id"],
    types={"year": tt.type.STRING, "month": tt.type.STRING},
)
```
`price` and `cost_price` are assumed as `int`.
![image](https://user-images.githubusercontent.com/35210495/147549774-50cbeafc-8d14-4f6f-b33b-83b1264ad42c.png)

I compute the measures as follows:
```
m["car price"] = tt.agg.sum(car_pricing["price"])
m["cost price"] = tt.agg.sum(car_pricing["cost_price"])
m["dealer holdback"] = tt.agg.sum(car_pricing["dealer_holdback"])
```
I've checked that my pricing and cost prices are all positive values but the summation returned negative figures:
![image](https://user-images.githubusercontent.com/35210495/147549990-676610e4-2d9e-493b-9685-360408f4a737.png)

The summation works correctly after casting the `price` and `cost_price` to `Double`:
```
car_pricing = session.read_csv(
    "sales_data/showroom_pricelist.csv",
    table_name="Car Prices",
    keys=["year", "month", "showroom_code", "model_id"],
    types={"year": tt.type.STRING, "month": tt.type.STRING, "price": tt.type.DOUBLE, "cost_price": tt.type.DOUBLE},
)
car_pricing.head()
```
![image](https://user-images.githubusercontent.com/35210495/147549426-74a9e97d-0ac5-40f7-a2ae-6cfdc68ecd37.png)

Source: [main-car-sales-20211228.zip](https://github.com/atoti/atoti/files/7784076/main-car-sales-20211228.zip)

## Environment

- atoti: 0.6.3
- Python: 3.8.12
- Operating System: win32

**Comment by tibdex** [comment]
This looks like integer overflow. Have you tried using `tt.type.LONG` instead of `tt.type.INT`?

**Comment by HuifangYeo** [comment]
Thanks @tibdex.

In any case, I have already declared it to type `tt.type.DOUBLE` before reporting the issue. It's just the process is a bit cumbersome when I'm taking the default deferred data type, only realizing the issue during visualization. Then I have to return to restart the session and recreate the table by casting the type.

I just hope there's an easier way to do so without having to re-create all the tables just to cast the data types.
Feel free to close the ticket.
