### ISSUE TITLE
Explain cube and OLAP concepts

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#45]
## Description

Reported by a first time user: 
> in getting started I had "absolutely no idea what a cube was". Then I immediately went back to the homepage -> docs -> api reference then cube, but all I found was an autogenerated doc. It did not help me understand what a cube was.

It would be great to add in the documentation a page explaining a few OLAP concepts and what value they bring. For example:
- OLAP
- cube
- dimension
- hierarchy
- levels
- measures
- slicing
- MDX

**Comment by fabiencelier** [comment]
Hello Julien,
We know this is missing is the current tutorial. We do have plans to include a explanation about these concepts in the next version of the tutorial
