### ISSUE TITLE
Clearer example on extending UI

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#454]
## Description

Is it possible to give a simple example of how to extend the UI?
https://docs.atoti.io/latest/lib/atoti.config.session_config.html#atoti.config.session_config.SessionConfig.app_extensions

```
config = {
    "app_extensions": {
        "some-extension": "../extensions/some-extension-package-directory/dist"
    }
}
```
After configuring `some-extension`, how do we make use of it in atoti?
Would be nice to have a sample .tsx extension example in the template folder.

**Comment by joohiang** [comment]
Hi, after running `npm run build` on the template project and generating the dist folder, I pointed the config to the dist folder but I am receiving server error 500 when attempting to access the atoti embedded web server. The config I am using is 
```
config = {
    "app_extensions": {
        "random-name": "path-to-dist"
    }
}
```
Are there any steps that I missed? Thanks.

**Comment by tibdex** [comment]
> Is it possible to give a simple example of how to extend the UI?

Isn't the code you pasted exactly that?

> After configuring some-extension, how do we make use of it in atoti?

There is nothing special to do, once the extension is added to the `app_extensions` mapping, it will be enabled automatically when you open the app.

> Would be nice to have a sample .tsx extension example in the template folder.

The app extension template linked just above the code example in the docs has the following contents:

<img width="230" alt="Screen Shot 2022-01-18 at 10 05 10" src="https://user-images.githubusercontent.com/6574550/149905404-cda2eea9-f1e2-48f1-9918-14f49e836cb4.png">

The `.ts` and `.tsx` files show what you would like no?

 ---

> Are there any steps that I missed?

Do you have an Atoti+ license and the `atoti-plus` plugin installed? They are required to use app extensions as indicated in the docs. If yes, can you share your sessions logs (at `session.logs_path`) so we can see the HTTP errors you're getting?

**Comment by joohiang** [comment]
Hi, thanks for pointing me to the location of the logs. I realised that I had the incorrect `"some-extension"` name, I replaced it with the `name` property in package.json and there are no problems now. Thanks for your time.

**Comment by bloussou** [comment]
name and path will be validated and a clear error thrown if necessary to avoid such issues in the next release
