### ISSUE TITLE
load_csv from pattern returning error when there is no files matching.

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#457]
## Steps to reproduce
Hello, if you try to load csv file within a table from a pattern and the matcher does not match anything rather than not loading anything we have this error:

```
atoti.exceptions.AtotiJavaException: AbsolutePathToProjectOnWindows\project\resources\QW5A_EUR_IR_iBoxx is an empty directory. You need at least one file to infer the schema of store Counterparties
```
I would not expect an error as I am declaring my tables via session.create_table, trying to load data for all of my tables and I might not have data ready for all of them.
This could happen in a production mode where some referenced table have no data but it is not that bad as it is only to have more attributes on the cube.
EG you could have a store with country details that you don't care either or not if you loaded data on it.

## Environment

atoti: 0.6.3
Python: 3.9.6
Operating System: win32

**Comment by bloussou** [comment]
Can you share the pattern and folders structure to test this ?

**Comment by bloussou** [comment]
I'm closing this as there is not update, fell free to reopen if you can reproduce the issue
