### ISSUE TITLE
Sorting level by first_member in multilevel hierarchy

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#468]
## Steps to reproduce

I'm trying to sort a level in a multilevel hierarchy by first_member and I encountered the below exception.

![image](https://user-images.githubusercontent.com/35210495/154422757-e0f17b8a-c4d9-44ff-a601-665ab8d0df0d.png)

I did not delete the initial single levels that are used to create the multilevel hierarchy.

## Environment

- atoti: 0.6.4
- Python: 3.8.12
- Operating system: win32

## Logs (if relevant)
<details><pre>---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\YEOHUI~1\AppData\Local\Temp/ipykernel_24552/1504938846.py in <module>
----> 1 l["Budget", "Budget Category", "BUDGET_TYPE"].comparator = tt.comparator.first_members(("Income", "Expenses"))

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\level.py in comparator(self, value)
     65             raise ValueError(f"Missing hierarchy for level {self.name}.")
     66         self._comparator = value
---> 67         self._hierarchy._java_api.update_level_comparator(self)
     68         self._hierarchy._java_api.refresh()
     69 

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\exceptions.py in catch_py4j_exceptions(java_api, *args, **kwargs)
     69     def catch_py4j_exceptions(java_api: JavaApi, *args: Any, **kwargs: Any) -> Any:
     70         try:
---> 71             return method(java_api, *args, **kwargs)
     72         except Py4JJavaError as java_exception:
     73             cause = (

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_java_api.py in update_level_comparator(self, level)
    808         first_members = None
    809         if level.comparator is not None and level.comparator._first_members is not None:
--> 810             first_members = to_java_object_array(
    811                 level.comparator._first_members, gateway=self.gateway
    812             )

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_py4j_utils.py in to_java_object_array(collection, gateway)
     13 ) -> JavaArray:
     14     """Transform the Python collection into a Java array."""
---> 15     return to_typed_java_array(
     16         collection, gateway=gateway, array_type=gateway.jvm.Object
     17     )

C:\Apps\miniconda3\envs\ds\lib\site-packages\atoti\_py4j_utils.py in to_typed_java_array(collection, gateway, array_type)
     73     if collection:
     74         for index, elem in enumerate(collection):
---> 75             array[index] = as_java_object(elem, gateway=gateway)
     76     return array
     77 

C:\Apps\miniconda3\envs\ds\lib\site-packages\py4j\java_collections.py in __setitem__(self, key, value)
    236 
    237         elif isinstance(key, int):
--> 238             return self.__set_item(key, value)
    239         else:
    240             raise TypeError("list indices must be integers, not {0}".format(

C:\Apps\miniconda3\envs\ds\lib\site-packages\py4j\java_collections.py in __set_item(self, key, value)
    216             self._get_object_id() + "\n"
    217         command += get_command_part(new_key)
--> 218         command += get_command_part(value)
    219         command += proto.END_COMMAND_PART
    220         answer = self._gateway_client.send_command(command)

C:\Apps\miniconda3\envs\ds\lib\site-packages\py4j\protocol.py in get_command_part(parameter, python_proxy_pool)
    296             command_part += ";" + interface
    297     else:
--> 298         command_part = REFERENCE_TYPE + parameter._get_object_id()
    299 
    300     command_part += "\n"

AttributeError: 'tuple' object has no attribute '_get_object_id'
</pre></details>

[server.log](https://github.com/atoti/atoti/files/8086408/server.log)

**Comment by bloussou** [comment]
This is an issue in your code:
You have:
```python
tt.comparator.first_members(("Income", "Expenses"))
```
And it must be :
```python
tt.comparator.first_members("Income", "Expenses")
```
