### ISSUE TITLE
Modulo

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#48]
## Description

It would be nice to have the modulo operator between two measures like we have m["m1"] * m["m2"], it could be useful to have m["m1"] % m["m2"]

I know it would be feasible via / and // operators, but it is still making it more complicated.

## Context

A measure needed to divide by the number of days present in the AsOfDate year, therefore either divide by 365 or by 366.

## Other information (if relevant)

Algorithm:
1. If the year is evenly divisible by 4, go to step 2. Otherwise, go to step 5.
2. If the year is evenly divisible by 100, go to step 3. Otherwise, go to step 5.
3. If the year is evenly divisible by 400, go to step 4. Otherwise, go to step 5.
4. The year is a leap year (it has 366 days).
5. The year is not a leap year (it has 365 days).

**Comment by fabiencelier** [comment]
I like the idea of adding the modulo operator and it seems to be [possible to override](https://docs.python.org/3/library/operator.html#operator.mod).

For this usecase of leap year can you add a store with the number of day per year and join it on the year field ?

**Comment by fabiencelier** [comment]
2 notes about modulo:
 - it can be done with number which are decimals or negative
 - it does not returns the same result in Java and Python:

in Java (modulo of absolute values with the sign of the first one):
```java
> 5 % 3
2
> 5 % -3
2
> -5 % -3
-2
> -5 % 3
-2
```

in Python
```python
>>> 5 % 3
2
>>> 5 % -3
-1
>>> -5 % -3
-2
>>> -5 % 3
1
```
I think we should do it the Python way
