### ISSUE TITLE
atoti.agg.quantile - the value of argument "interpolation" must be one of ('linear', 'higher', 'lower', 'nearest', 'midpoint')

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#485]
## Description
For the documentation of [`atoti.agg.quantile`](https://docs.atoti.io/latest/lib/atoti.agg.html#atoti.agg.quantile), there is a discrepancy in the expected value (lower -> lowest / higher -> highest):

![image](https://user-images.githubusercontent.com/35210495/156310378-a1cf0fe1-9005-4280-9b03-6715f3aee224.png)

Error encountered when using `lowest`:

```
TypeError: the value of argument "interpolation" must be one of ('linear', 'higher', 'lower', 'nearest', 'midpoint'); got lowest instead
```

**Comment by bloussou** [comment]
Hello,
This will be fixed in the next release
