### ISSUE TITLE
aggregation of long value incorrect

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#489]
## Steps to reproduce

I have the below measures:

```
m["Overpriced"] = tt.where(
    l["cust dist"] != None,
    tt.agg.long(
        m["Price.SUM"] - m["upper"],
        scope=tt.scope.origin(l["cust dist"]),
    ),
)

m["Overvalued Amount"] = tt.agg.sum(
    m["Overpriced"] * m["Quantity.SUM"], scope=tt.scope.origin(l["cust dist"])
)

```
I was expecting that the value at the `cards` level is a summation of the underlying level but it's not. I'm not sure how the value is derived.

![image](https://user-images.githubusercontent.com/35210495/156520774-7c2e2822-6cc3-40d0-9922-ec0d985d91aa.png)

source: [trade.zip](https://github.com/atoti/atoti/files/8175951/trade.zip)

## Environment

- atoti: 0.6.4
- Python: 3.8.12
- Operating system: win32

**Comment by bloussou** [comment]
is this solving your issue, it looks like a scope definition mistake
[main.zip](https://github.com/atoti/atoti/files/8176666/main.zip)
