### ISSUE TITLE
Cannot reuse measure defined in `Measures.update()` in the same call to `Measures.update()`

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#529]
## Steps to reproduce
Hello,

Within the Measures.update(), you can not reuse a measure that has been created in the previous line of the update.
Meaning:
```python
m.update({
   "PnL.SUM": atoti.agg.sum(table["PnL"]),
   "10 * PnL.SUM": 10 * m["PnL.SUM"]
})
```
Won't work because "PnL.SUM" was not created before and therefore the "10 * PnL.SUM" can't be created.
This behaviour is not explained neither in the documentation by the way.

## Environment

- atoti: 0.6.4
- Python: 3.9.6
- Operating system: win32

**Comment by bloussou** [comment]
Hello,
I can reproduce in latest nightly too. I will look for a fix
