### ISSUE TITLE
Problem When Creating Line Chart

### ISSUE THREAD

**Issue by bloussou** [atoti/atoti#532]
### Discussed in https://github.com/atoti/atoti/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **yerol89** March 23, 2022</sup>
Hello Everyone,

I am trying to create a very basic line chart. I have "PERIOD_STR" in X axis and "YEAR_COUNT" in Y axis. 
When you focus on the pop-up on the shared screen shot, you can notice that the line which has YEAR_COUNT = 3 located at the YEAR_COUNT=1 part. But I expect it to be displayed on the YEAR_COUNT=3 part.

I wanted to share this, because it seemed like a bug that  should be fixed by the developers.
 
![Capture](https://user-images.githubusercontent.com/57112729/159655804-99756941-8e78-44d4-8e55-da3d1cd4d868.PNG)
 </div>

**Comment by bloussou** [comment]
Hello @yerol89,
I cannot reproduce with this example : 
```python
import atoti as tt
import pandas as pd
session = tt.Session()
table = session.read_pandas(
    pd.DataFrame({
        "YEAR_COUNT": ["1","1","1", "2", "2", "2", "3", "3", "3", "4", "4", "4", "5", "5", "5", "5+", "5+", "5+"],
        "Factor": [0.3, 0.5, 0.7, 0.3, 0.5, 0.7, 0.3, 0.5, 0.7, 0.3, 0.5, 0.7, 0.3, 0.5, 0.7, 0.3, 0.5, 0.7],
        "Date": ["2022-01", "2022-02", "2022-03", "2022-01", "2022-02", "2022-03", "2022-01", "2022-02", "2022-03", "2022-01", "2022-02", "2022-03", "2022-01", "2022-02", "2022-03", "2022-01", "2022-02", "2022-03"],
        "Name": ["Joe", "Joe", "Bob", "Joe", "Joe", "Bob", "Joe", "Joe", "Bob", "Joe", "Joe", "Bob", "Joe", "Joe", "Bob", "Joe", "Joe", "Bob", ]
    }),
    table_name="Table",
    keys=["YEAR_COUNT", "Date"]
)
cube = session.create_cube(table)
session.visualize()
```
![image](https://user-images.githubusercontent.com/32448554/159668524-787550da-e649-40ea-a2bf-58e1ad9a4d34.png)
Can you share a sample of data to help reproduce your case ?

**Comment by yerol89** [comment]
Hello again @bloussou ,

I realized that the problem is with our data. The "RENEWED_COUNT" feature is only available  for the samples which have "YEAR_COUNT" = 1. So the problem is not with the ATOTI. Sorry for taking your time.

**Comment by bloussou** [comment]
No worries good to know there is no issue !
