### ISSUE TITLE
Missing required Python version for conda installation 

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#55]
## Description

A first time user went on to install atoti and his first thought was to create an environment (before even reading the installation page).

He then went to the conda cheat sheet available when you google [conda cheat sheet](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf) and copy/pasted the syntax `conda create --name py35 python=3.5` to create its environment with python 3.6 (did not know which one to pick) which resulted in an obscure error: it was not clear at all that it was related to the wrong python version.

While we can't catter for all different ways to install the library, we should try to make sure we loose nobody during the installation phase. It would have helped to have somewhere in the installation page the minimum required version mentionied like we do for pypi:
![image](https://user-images.githubusercontent.com/4415696/82928605-b0dc1680-9f82-11ea-848e-53a8ff2f10a6.png)

Of course the message should be different and more subtle because those are just mentioned "just in case" the installation did not go as expected.

**Comment by fabiencelier** [comment]
The difference between pip and conda is that the conda recipe specifies that Python >= 3.7 is a  requirements so it should be installed along atoti if not already installed. [Surprisingly] conda is actually quite clear for this issue when there is a conflict:

```bash
conda create --name py35 python=3.5
conda activate py35
conda install atoti
```

<pre>
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - atoti -> python[version='>=3.7']

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
</pre>

Do we really need more than that ? If we say that Python >= 3.7 is a requirements I am afraid people will try to install things by themselves when they don't need to if they use a fresh env

**Comment by fabiencelier** [comment]
As a side note, while `conda install atoti` has a clear error message,  `conda install atoti jupyterlab jupyterlab-atoti nodejs openjdk` has a lot of additional logs hiding the clear message:

<pre>
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - atoti -> python[version='>=3.7']
  - jupyterlab -> python[version='>=3.8,<3.9.0a0']

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libxml2 conflicts for:
openjdk -> fontconfig[version='>=2.13.1,<3.0a0'] -> libxml2[version='>=2.9.10,<2.10.0a0|>=2.9.9,<2.10.0a0|>=2.9.8,<2.10.0a0']
atoti -> graphviz -> libxml2[version='>=2.9.8,<2.10.0a0']

Package ca-certificates conflicts for:
nodejs -> openssl[version='>=1.1.1g,<1.1.2a'] -> ca-certificates
python=3.5 -> openssl[version='>=1.0.2o,<1.0.3a'] -> ca-certificates
jupyterlab -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates

Package _libgcc_mutex conflicts for:
nodejs -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
openjdk -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']
python=3.5 -> libgcc-ng[version='>=4.9'] -> _libgcc_mutex[version='*|0.1',build='main|conda_forge']

Package python_abi conflicts for:
atoti -> pandas -> python_abi[version='2.7.*|3.6.*|3.6|3.8.*',build='*_cp27mu|*_cp36m|*_cp38|*_pypy36_pp73']
atoti -> python_abi=3.7[build=*_cp37m]
jupyterlab -> notebook[version='>=4.3.1'] -> python_abi[version='2.7.*|3.6|3.6.*|3.7.*|3.8.*',build='*_cp27mu|*_pypy36_pp73|*_cp38|*_cp36m|*_cp37m']

Package icu conflicts for:
nodejs -> icu[version='>=64.2,<65.0a0|>=67.1,<68.0a0']
openjdk -> fontconfig[version='>=2.13.1,<3.0a0'] -> icu[version='>=58.2,<59.0a0|>=64.2,<65.0a0|>=67.1,<68.0a0']
atoti -> graphviz -> icu[version='>=58.2,<59.0a0']

Package zlib conflicts for:
nodejs -> zlib[version='>=1.2.11,<1.3.0a0']
openjdk -> zlib[version='>=1.2.11,<1.3.0a0']
jupyterlab -> python[version='>=3.5'] -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']
atoti -> graphviz -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
python=3.5 -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0']

Package openssl conflicts for:
nodejs -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1d|>=1.1.1c,<1.1.2a']
jupyterlab -> python[version='>=3.5'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']
atoti -> python[version='>=3.7'] -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a']
python=3.5 -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']

Package libgcc conflicts for:
nodejs -> libgcc
openjdk -> alsa-lib[version='>=1.1.5,<1.1.6.0a0'] -> libgcc
</pre>

**Comment by jbe456** [comment]
You saw like me that a first time user was stuck after having the error above.

Would it make things worse to add next to the install command in the doc: 
> this will install the following version...

and precise the python/node/jvm version? I don't think so. Would it solve the issue mentioned above? that I'm not sure...

If atoti explicitly depends on python 3.7, should we add it to the install command as well?
- Something like: `conda install atoti jupyterlab jupyterlab-atoti nodejs openjdk python`
- Or by forcing the versions: `conda install atoti==0.4.0 "jupyterlab>=2.1" jupyterlab-atoti==0.4.0 "nodejs>=10" "openjdk>=11" "python>=3.7"`

At least with the last line we make sure there are no possible mistakes, and nobody will try to run it without copy/pasting :-)

**Comment by fabiencelier** [comment]
I don' like pinning all the versions in the doc as it is already done and handled by conda so I don't think it adds anything.

Adding `python` to the list to install seems enough to update python to an atoti compliant version.
It's a bit strange to explicitly install dependencies (we don't do it for the other ones like pyyaml, pandas, graphviz) but Python might be specific enough to add it. 

@tibdex what do you think ?

**Comment by tibdex** [comment]
I'm OK for `conda install atoti jupyterlab jupyterlab-atoti nodejs openjdk python` for the reasons you said.
