### ISSUE TITLE
Add cube.visualize in getting started

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#56]
## Description

On https://docs.atoti.io/0.4.0/tutorial/01-Getting-Started.html, for the section "JupyterLab extension", we only provide a picture:

![image](https://user-images.githubusercontent.com/4415696/82928999-48da0000-9f83-11ea-8168-0dd5df53170e.png)

It would make sense to add a line with `cube.visualize()`

**Comment by fabiencelier** [comment]
Related to:
 - https://github.com/activeviam/atoti/issues/796 as the image is a workaround to display a static widget
 - https://github.com/activeviam/atoti/issues/1392: I will add a part about building a widget in the new tutorial version.
