### ISSUE TITLE
Unable to create multi-level hierarchy

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#560]
## Steps to reproduce

I encountered the error `com.activeviam.fwk.ActiveViamRuntimeException: Cannot create hierarchy Candidate-terrority because the fields [Candidate name, Region, Department] cannot be found.` when I tried to create multi-level hierarchy. However, the levels/table columns exist.

![image](https://user-images.githubusercontent.com/35210495/163138986-4c0c8c31-5038-42d2-81ab-ca01ec2087c7.png)

Source: [Untitled.zip](https://github.com/atoti/atoti/files/8479830/Untitled.zip)

## Environment
- atoti: 0.6.5
- Python: 3.9.12
- Operating system: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/8479818/server.log)

**Comment by HuifangYeo** [comment]
My bad. Here it is: [candidates.csv](https://github.com/atoti/atoti/files/8480623/candidates.csv)

Yes, it does look like the same as #182

**Comment by bloussou** [comment]
I havwe checked it is the same as #182, it is a work in progress to support such hierarchies :smiley:
