### ISSUE TITLE
Graphviz - Misleading Error Message when failure generating schema due to incorrect column name

### ISSUE THREAD

**Issue by CDE-AV** [atoti/atoti#567]
## Steps to reproduce

Sample Notebook Code:

```py
import atoti as tt
import pandas as pd

session = tt.Session()

table = session.read_pandas(pd.DataFrame({
    "&": ["a"]
}), table_name="test")

session.tables.schema
```

## Actual Result

The schema generation fails with the following error:

```
Missing Graphviz library which is required to display the graph. It can be installed with Conda: `conda install graphviz` or by following the download instructions at https://www.graphviz.org/download/.
```

This message is misleading as graphviz even if it is properly installed it will throw this error instead of indicating that the generation of the graph has failed...

## Expected Result

A proper error message should be produced to indicate the generation failure

## Environment

- atoti: 0.6.5
- Operating System: WinOS
- Browser: NA

**Comment by Acriss** [comment]
Hi !
You're right, I do reproduce this misleading error message.
It looks like it comes from the use of the ampersand.
