### ISSUE TITLE
Max aggregation on a level

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#57]
## Steps to reproduce

```python
import pandas as pd

main_df = pd.DataFrame(
    data={
        "position": [1, 2, 1, 1, 2, 3, 4, 5],
        "race": ["A", "A", "B", "C", "C", "C", "C", "C"],
    }
)

import atoti

session = atoti.create_session()
main_store = session.read_pandas(main_df, store_name="main")
cube = session.create_cube(main_store)

m = cube.measures
lvl = cube.levels

m["position.Store.MAX"] = atoti.agg.max(main_store["position"])

m["position.Level.MAX"] = atoti.agg.max(lvl["position"])

m["position.Measure"] = lvl["position"]
m["position.Measure.MAX"] = atoti.agg.max(
    m["position.Measure"], scope=atoti.scope.origin(lvl["position"])
)
```

## Actual Result

`position.Level.MAX` returns a value only at the position level:

![image](https://user-images.githubusercontent.com/4415696/82998448-07d7ff00-a008-11ea-9b52-faa72e4e50c9.png)

## Expected Result

I would expect the max aggregation on a level to work directly. The workaround is to use the store field directly or to "cast" the level as a measure and specify the scope.

## Environment

- atoti: 0.4.0
- Python: 3.7.6
- Operating System: linux

**Comment by a-manai** [comment]
Hi Julien,

Thanks for reporting this. It is indeed a bug: expressions of the form `agg(lvl[...])` currently create the same measure as `lvl[...]`, which is why in your example you don't have values where there is no `position`.
The issue has been fixed.
