### ISSUE TITLE
Cumulative measure broken when assigned tuple.

### ISSUE THREAD

**Issue by Wi1iku** [atoti/atoti#571]
The code works when assigned a range to the window.

## Steps to reproduce

```py
#gets data from yahoo finance
dax_components = y.get_components('gdaxi')
#Makes dataframe with yahoo finance data
dax_components_info_df = y.get_components_info(dax_components, 10, '1h')
dax_components_info_df.dtypes
dax_components_info = session.read_pandas(dax_components_info_df, table_name= 'Dax Components Info')
cube = session.create_cube(dax_components_info, "Dax Stock Analytics")
h = cube.hierarchies
m = cube.measures
l = cube.levels

h["Date"] = [
    dax_components_info["year"],
    dax_components_info["month"],
    dax_components_info["day"],
    dax_components_info["hour"],
    dax_components_info["Datetime"]
]
l['Datetime']
m['DPW.DE_open_moving'] = tt.agg.mean(m['DPW.DE_open.MEAN'], scope=tt.scope.cumulative(l['Datetime'], window=('-4D',None)))
```

``Dataframe datatypes:``
year                      int64
month                     int64
day                       int64
hour                      int64
Datetime         datetime64[ns]
                      ...
HFG.DE_close            float64
DHER.DE_open            float64 
DHER.DE_high            float64
DHER.DE_low             float64
DHER.DE_close           float64
Length: 125, dtype: object
``Level datetime info:``
Datetime:
   dimension:"P"
   hierarchy:"Date"
   type:"LocalDateTime"
   order:"NaturalOrder"

## Actual Result

Cube broken, does not make any measure

AtotiJavaException: PostProcessor DPW.DE_open_moving - TimePeriodWindowPP: an exception occurred during initialization with the following properties {traversalHierarchy=Date, outputType=double, underlyingMeasures=DPW.DE_open.MEAN, reverseHierarchyOrder=false, orderedWindow=true, BACK_PERIOD=P4D, reducer=com.activeviam.copper.measure.window.AggregationToWindowTraversal$ReducerSupplier@47c8de38, defaultComparator=true}

## Expected Result

Create a moving measure 

## Environment

    - atoti: 0.6.5
    - Python: 3.10.4
    - Operating system: win32
## Logs (if relevant)
<details><pre>---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
Input In [32], in <cell line: 1>()
----> 1 m['DPW.DE_open_moving'] = tt.agg.mean(m['DPW.DE_open.MEAN'], scope=tt.scope.cumulative(l['Datetime'], window=('-4D',None)))

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\_runtime_type_checking_utils.py:179, in _TypecheckWrapperFactory.create_wrapper.<locals>.typechecked_func_wrapper(*args, **kwargs)
    176 typeguard.check_argument_types(memo)
    178 # Call the actual function.
--> 179 return self._func(*args, **kwargs)

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\measures.py:95, in Measures.__setitem__(self, key, value)
     90 def __setitem__(
     91     self,
     92     key: str,
     93     value: MeasureLike,
     94 ) -> None:
---> 95     self.update({key: value})

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\_telemetry.py:225, in _track_calls.<locals>.function_wrapper(*args, **kwargs)
    222 call_tracker.tracking = True
    224 try:
--> 225     return _track_call(function, call_path, *args, **kwargs)
    226 finally:
    227     call_tracker.tracking = False

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\_telemetry.py:188, in _track_call(function, call_path, *args, **kwargs)
    185     except:  # pylint: disable=bare-except
    186         # Do nothing to let the previous error be the one presented to the user.
    187         ...
--> 188     raise error
    189 finally:
    190     arguments: Dict[str, str] = {}

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\_telemetry.py:181, in _track_call(function, call_path, *args, **kwargs)
    179 call_time = time.perf_counter()
    180 try:
--> 181     return function(*args, **kwargs)
    182 except Exception as error:  # pylint: disable=broad-except
    183     try:

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\_runtime_type_checking_utils.py:179, in _TypecheckWrapperFactory.create_wrapper.<locals>.typechecked_func_wrapper(*args, **kwargs)
    176 typeguard.check_argument_types(memo)
    178 # Call the actual function.
--> 179 return self._func(*args, **kwargs)

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\measures.py:129, in Measures.update(self, _Measures__m, **kwargs)
    127     other.update(__m)
    128 other.update(**kwargs)
--> 129 self._update(other)

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\measures.py:152, in Measures._update(self, other)
    149 except AttributeError as err:
    150     raise ValueError(f"Cannot create a measure from {measure}") from err
--> 152 self._java_api.publish_measures(self._cube_name)

File ~\Miniconda3\envs\atoti\lib\site-packages\atoti\_java_api.py:135, in _enhance_py4j_errors.<locals>.wrapped_method(self, *args, **kwargs)
    129 except Py4JJavaError as java_exception:
    130     cause = (
    131         str(java_exception)
    132         if get_env_flag(_ATOTI_VERBOSE_JAVA_EXCEPTIONS)
    133         else self.get_throwable_root_cause(java_exception.java_exception)
    134     )
--> 135     raise AtotiJavaException(
    136         cause,
    137         java_traceback=str(java_exception),
    138         java_exception=java_exception,
    139     ) from None

AtotiJavaException: PostProcessor DPW.DE_open_moving - TimePeriodWindowPP: an exception occurred during initialization with the following properties {traversalHierarchy=Date, outputType=double, underlyingMeasures=DPW.DE_open.MEAN, reverseHierarchyOrder=false, orderedWindow=true, BACK_PERIOD=P4D, reducer=com.activeviam.copper.measure.window.AggregationToWindowTraversal$ReducerSupplier@47c8de38, defaultComparator=true}</pre></details>

**Comment by tibdex** [comment]
Hi, we've actually already done the work for supporting time period windows in cumulative aggregations on multilevel temporal hierarchies. It will be available in the next release.
