### ISSUE TITLE
Can't create diferents date hierarchy (create_date_hierarchy) with differents columns

### ISSUE THREAD

**Issue by tibdex** [atoti/atoti#572]
### Discussed in https://github.com/atoti/atoti/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **nicoin19** April 20, 2022</sup>
Atoti version: 0.6.5

I have two o more columns with date data (entry_date, delivery_date, etc.). When I use:

```py
cube.create_date_hierarchy("entry", column=table["date_entry"], levels={'entry_year':'y', 'entry_month':'M', 'entry_day':'d'})
```

this works perfectly, I can do querys without any problems:

```py
cube.query(m["price.SUM"], levels=[l["entry_year"], l["entry_month"], l["service_type"]])
```

However, when I try again use "create_date_hierarchy" next line, with other column:

```py
cube.create_date_hierarchy("delivery", column=table["date_delivery"], levels={'delivery_year':'y', 'delivery_month':'M', 'delivery_day':'d'})
```

I get the following exception:

```
_AtotiJavaException: [500] Failed to process update of type MergingStorePartitionUpdate for partition 0 of store `table`. Failed operation summary: added: 0, deleted: 0, updated: 0_
```

Do you have any ideas about that? I don't find any bug reported some like that.

Thanks for your help.</div>

**Comment by tibdex** [comment]
@nicoin19 I can't reproduce the error on my side. Can you share a minimal reproducible example?

**Comment by nicoin19** [comment]
@tibdex I have a connection with postgres database (local), from where I get the data. 

I will put below all the code I use. I am from Paraguay (South America), therefore part of the code is in Spanish, but it is understood.

`import atoti as tt
import pandas as pd

session = tt.Session()

sql = """select DATE(op.fechaingreso) as fecha_ingreso, DATE(op.fechaentrega) as fecha_entrega,
opd.escabecera as es_cabecera, opd.cantidadproductocabecera as cant_producto,
prod.descripcion as producto_desc, prod.espesor as prod_espesor, round(CAST(prod.ancho as numeric),2) as prod_ancho, 
round(CAST(prod.alto as numeric),2) as prod_alto, round(CAST(opd.ancho as numeric),2) as opd_ancho, 
round(CAST(opd.alto as numeric),2) as opd_alto, opd.observacion as opd_observ, 
round(CAST(prod.costoplancha as numeric),2) as prod_costo_plancha,
round(CAST(prod.costom2 as numeric),2) as prod_costo_m2, prod.marca as prod_marca, prod.color as prod_color, 
prod.porcentajedescuento as "prod_%_descuento", prod.porcentajeminimoganancia as "prod_%_min_ganancia", 
round(CAST(prod.valorminimodeventa as numeric),2) as prod_valor_min_venta, tds1.nombrecorto as servicio_producto_1, 
--opd.idservicioproducto1 as serv_prod_1, 
prod1.descripcion as descripcion_prod_or_serv_1,
tds2.nombrecorto as servicio_producto_2, 
--opd.idservicioproducto2 as serv_prod_2,
prod2.descripcion as descripcion_prod_or_serv_2
from ordendepedido as op
inner join ordendepedidodetalle as opd on op.id = opd.idordendepedidodetalle
full outer join producto as prod on opd.idproductocabecera = prod.id
full outer join tipodeservicio as tds1 on opd.idservicioproducto1 = tds1.id
full outer join producto as prod1 on prod1.id = tds1.idproductoservicio
full outer join tipodeservicio as tds2 on opd.idservicioproducto2 = tds2.id
full outer join producto as prod2 on prod2.id = tds2.idproductoservicio
where op.fechaingreso is not null
order by op.fechaingreso desc;"""


ordendepedidodetalle_table = session.read_sql(
    sql,
    url="jdbc:postgresql://localhost:5432/vidrioluz?user=vidrioluz&password=vidrioluz",
    table_name="ordendepedidodetalle",
)


cube = session.create_cube(ordendepedidodetalle_table)
session.tables.schema

h = cube.hierarchies
h

l = cube.levels
l

m = cube.measures
m

cube.create_date_hierarchy("ingreso", column=ordendepedidodetalle_table["fecha_ingreso"], levels={'ingreso_anho':'y', 'ingreso_mes':'M', 'ingreso_dia':'d'})

cube.query(m["prod_costo_m2.SUM"], levels=[l["ingreso_anho"], l["ingreso_mes"], l["descripcion_prod_or_serv_1"]])


# This line throw the error I describe in the first post
cube.create_date_hierarchy("entrega", column=ordendepedidodetalle_table["fecha_entrega"], levels={'entrega_anho':'y', 'entrega_mes':'M', 'entrega_dia':'d'})`

**Comment by tibdex** [comment]
Thanks but that's not a reproducible example as we can't run this code because we don't have access to your postgres DB. Can you try to simplify your code and make it so that we can run it by just copy/pasting it? Thanks.

**Comment by nicoin19** [comment]
Now, I did same test with Pandas, without any problems.
(_I will see the way to share a example reproducible of my case_)

`from datetime import date
df = pd.DataFrame(
    columns=["id", "Date_entry", "Quantity", "Date_delivery"],
    data=[
        (1, date(2020, 1, 10), 150.0, date(2020, 1, 11)),
        (2, date(2020, 1, 20), 240.0, date(2020, 1, 21)),
        (3, date(2019, 3, 17), 270.0, date(2019, 3, 18)),
        (4, date(2019, 12, 12), 200.0, date(2019, 12, 13)),
    ],
)

table = session.read_pandas(
    df, keys=["id"], table_name="create_date_hierarchy example"
)

cube = session.create_cube(table)
l, m = cube.levels, cube.measures

cube.create_date_hierarchy("entry", column=table["Date_entry"], levels={'entry_year':'y', 'entry_month':'M', 'entry_day':'d'})

cube.query(
    m["Quantity.SUM"],
    include_totals=True,
    levels=[l["entry_year"], l["entry_month"], l["entry_day"]],
)

cube.create_date_hierarchy("delivery", column=table["Date_delivery"], levels={'delivery_year':'y', 'delivery_month':'M', 'delivery_day':'d'})

cube.query(
    m["Quantity.MEAN"],
    include_totals=True,
    levels=[l["delivery_year"], l["delivery_month"], l["delivery_day"]],
)`

Thanks for your time and help.

**Comment by nicoin19** [comment]
Hi @tibdex 

I did two little projects to test again this situation or case.

1° - I created two singles tables in Postgresql, named "sales" and "sales_details". Using Jupyter Lab I created a connection, get the data trough inner join. I have two columns about date entry and delivery, and I can run or execute without any problems "create_date_hierarchy" twice in a row.

2° - Is exactly the same situation I describe above, but I use two production tables [tables_in_github.](https://github.com/nicoin19/tables_atoti_errors/blob/5743a0c72b32e442d98390d85c7b847a41f80aeb/tables.zip) Inner join I use is very simple, but I get error that I described in the first post. (_AtotiJavaException: [500] Failed to process update of type MergingStorePartitionUpdate for partition 0 of store `ordendepedido`. Failed operation summary: added: 0, deleted: 0, updated: 1678_)

This is the simple code I use, for this two examples. Only tables name changed.

`import atoti as tt
import pandas as pd

session = tt.Session()

sql = """select fechaingreso, fechaentrega, nombreproducto, cantidadproductocabecera
from ordendepedido
inner join ordendepedidodetalle on ordendepedido.id = ordendepedidodetalle.idordendepedidodetalle"""

table = session.read_sql(
    sql,
    url="jdbc:postgresql://localhost:5432/test?user=test&password=test",
    table_name='ordendepedido',
)

cube = session.create_cube(table)

session.tables.schema

h = cube.hierarchies
h

l = cube.levels
l

m = cube.measures
m

cube.create_date_hierarchy("ingreso", column=table["fechaingreso"], levels={'ingreso_anho':'y', 'ingreso_mes':'M', 'ingreso_dia':'d'})

cube.query(m["cantidadproductocabecera.SUM"], levels=[l["ingreso_anho"], l["ingreso_mes"], l["nombreproducto"]])


cube.create_date_hierarchy("entrega", column=table["fechaentrega"], levels={'entrega_anho':'y', 'entrega_mes':'M', 'entrega_dia':'d'})

cube.query(m["cantidadproductocabecera.MEAN"], levels=[l["entrega_anho"], l["entrega_mes"], l["producto"]])`

Thank you for your help.

**Comment by nicoin19** [comment]
Hi @tibdex 

So sorry. I have a error in my sql sentence. It's my big mistake.

Thanks for your patience.

**Comment by tibdex** [comment]
Hi @nicoin19, do you mean that you don't have an issue with multiple date hierarchies anymore? If yes, you can close the issue ;).

**Comment by nicoin19** [comment]
Hi @tibdex. Exactly. I was getting a date column with null value, it was the cause throwing the error.
Thanks for your help.

**Comment by nicoin19** [comment]
Closed
