### ISSUE TITLE
New scenario does not trigger query update

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#578]
## Steps to reproduce
```python
import atoti as tt
import pandas as pd
session = tt.create_session()
base_table = session.read_pandas(
    pd.DataFrame({
        "l1": ["a", "b"]
    }), 
    table_name="base", 
    keys=["l1"]
)

cube=session.create_cube(base_table)
session.link()
#base_table.scenarios["test"].load_pandas(base_table.head(2))
```

If you run the last cell creating a `test` branch from the `base_table` table, while having a continuous query registered with contributors.count with source simulation as level, the query won't receive the update telling that the `test` branch has been created.

## Environment

- atoti: 0.6.4
- Python: 3.7.9
- Operating System: Windows

**Comment by alexis-bvq** [comment]
If you add a new keys in the base store then the continuous query engine is triggered, if you only update existing keys in order to create the new branch then it is not.

**Comment by bloussou** [comment]
[Internal ticket](https://support.activeviam.com/jira/browse/PIVOT-5510)

**Comment by bloussou** [comment]
This is the expected behavior, the answer from the core team is:
```
After looking at the code, this is the expected behavior. The reason is that the branching mechanism takes place at a higher level than the transactions, hence any empty transaction or update with the same record on a branch will result in an empty update, and consequently no update of the continuous query.

I am closing since there is no simple workaround. A solution could be to create a branch with an actual change especially since having a simulation without update doesn't make any sense.
```
