### ISSUE TITLE
NumberFormatException thrown on server side but not reflected in notebook

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#58]
## Steps to reproduce
I expected Doubles for the `sell_value` and `buy_value`. However, some rows contained NA value instead. On the server log, exception was thrown and the record was dropped. However, working on the notebook, I was totally unaware of the data drop.

```
item_types = {"sell_value": tt.types.DOUBLE, "buy_value": tt.types.DOUBLE}

items_store = session.read_csv(
    "items.csv", keys=["id"], store_name="items_store", types=item_types
)
```

## Expected Result
An exception thrown during store creation to warn users that some data are irregular and have been dropped.

## Environment
- atoti: 0.4.0
- Python: 3.8.2
- Operating System: win32

## Logs (if relevant)
[session.log](https://github.com/atoti/atoti/files/4710383/session.log)

**Comment by fabiencelier** [comment]
Related to https://github.com/activeviam/atoti/issues/266

**Comment by fabiencelier** [comment]
Hello,
In next release a warning will be issued in the notebook when a loading error occur.
A more complete report about the store loading will be available in `store.loading_report`
