### ISSUE TITLE
Create Hierarchy from an empty column breaks the cube

### ISSUE THREAD

**Issue by EricDallAgnol** [atoti/atoti#587]
Hi,
I found that behaviour while playing around with the method `create_parameter_hierarchy_from_members`
It might be a use case that doesn't make sense but I report it anyway

## Steps to reproduce

- Create a table and load it with data
- Create cube
- Check `count` is valid
- Call `create_parameter_hierarchy_from_members`  providing an empty collection
- Check `count` -> no data anymore :(

Please find here the code to reproduce the issue : 
`````python
import atoti as tt
import pandas as pd

session = tt.Session()

df = pd.DataFrame(
    {
        "Seller": ["Seller_1", "Seller_2", "Seller_3"],
        "Prices": [
            [2.5, 49.99, 3.0, 54.99],
            [2.6, 50.99, 2.8, 57.99],
            [2.99, 44.99, 3.6, 59.99],
        ],
    }
)

table = session.read_pandas(df, table_name="Seller prices")
cube = session.create_cube(table)
l, m = cube.levels, cube.measures

# Put only count in a pivot table -> displays '3'
session.visualize()


cube.create_parameter_hierarchy_from_members(
    "EmptyHierarchy",
    [],
    index_measure_name="Custom index",
)

# Put only count in a pivot table -> displays 'No data for your query'
session.visualize()
`````

## Actual Result

There is no error message and my pivot table with only `count` returns : _No data for your query_

## Expected Result
Having a valid _count_ or at least having an error message 

## Environment

- atoti: 0.6.5
- Python: 3.8.3
- Operating system: win32

**Comment by bloussou** [comment]
Hello,
I don't get why you are talking about `create_parameter_hierarchy_from_column` and your example is using `create_parameter_hierarchy_from_members` ? Can you clarify this ?

**Comment by EricDallAgnol** [comment]
Hello,

My bad you're right it's only now I'm realizing this is not the good method 😓 😓 
Really sorry about that.

Though, it might make no sense but if you run my code example, if with `create_parameter_hierarchy_from_members` (yes this one !)
you provide an empty collection then the cube seems to be broken
I've edited the issue in that sense.

But actually I'm wondering if this is not expected in the end because, correct me if I'm wrong, `create_parameter_hierarchy_from_members` creates a slicing hierarchy and given that the collection provided is empty, there is no default member then no data is matching which leads to "No data for your query" right ?

Many thanks !

**Comment by bloussou** [comment]
You are right I think :smile:

**Comment by bloussou** [comment]
I'm closing this as we have understood the behavior and it is the correct one
