### ISSUE TITLE
Page filter and Quick page filter weird behavior with multiple cubes 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#59]
## Steps to reproduce
Please see the attached source and gif:
No issue adding Page filter. However the quick filter and quick page filter will throw error message:
[animal-crossing.zip](https://github.com/atoti/atoti/files/4710429/animal-crossing.zip)

![quick_filter_exception](https://user-images.githubusercontent.com/35210495/83394639-7ca5a180-a42b-11ea-9ed2-0f884cd9e157.gif)

## Actual Result
[ActiveUI_Report_6_1_2020__4_39_34_PM.zip](https://github.com/atoti/atoti/files/4710435/ActiveUI_Report_6_1_2020__4_39_34_PM.zip)

[ActiveUI_Report_6_1_2020__5_08_08_PM.zip](https://github.com/atoti/atoti/files/4710410/ActiveUI_Report_6_1_2020__5_08_08_PM.zip)

## Expected Result
I should be able to add Quick Page Filter for whichever cube available.

## Environment

- atoti: 0.4.0
- Python: 3.8.2
- Operating System: win32

**Comment by tibdex** [comment]
Thanks for reporting the issue, I've created an [internal ticket](https://support.activeviam.com/jira/browse/UI-4208) to track it.
