### ISSUE TITLE
Failed to load DataFrame with Period data types

### ISSUE THREAD

**Issue by tibdex** [atoti/atoti#597]
### Discussed in https://github.com/atoti/atoti/discussions/596

<div type='discussions-op-text'>

<sup>Originally posted by **tht-activeviam** May 30, 2022</sup>
>Atoti version 0.6.4

When loading DataFrame with period datatypes, error occurred. Use [this notebook](https://github.com/tht-activeviam/perso-tht-atoti-playground/blob/main/Period%20Dtype%20Demo.ipynb) to reproduce the issue.

### Creating columns with period type
```python
data_df['Deal Date'] = pd.to_datetime(data_df['Deal Date'], errors='coerce', infer_datetime_format=True)
data_df['Deal Quarter'] = data_df['Deal Date'].dt.to_period('Q')
data_df['Deal Month'] = data_df['Deal Date'].dt.to_period('M')
```

### Error occurred during session.read_pandas()
```
File ~/miniconda3/envs/atoti-plus-0.6.4/lib/python3.10/site-packages/atoti/_arrow_utils.py:72, in <dictcomp>(.0)
     64 def get_data_types_from_arrow(
     65     table: pa.Table,  # type: ignore
     66     *,
     67     keys: Iterable[str],
     68 ) -> Dict[str, DataType]:
     69     arrow_types = table.schema.types
     70     return {
     71         table.column_names[i]: DataType(
---> 72             java_type=_ARROW_TYPES[arrow_type].java_type,
     73             nullable=_ARROW_TYPES[arrow_type].nullable
     74             and (table.column_names[i] not in keys),
     75         )
     76         for i, arrow_type in enumerate(arrow_types)
     77     }

KeyError: ArrowPeriodType(DataType(int64))
```</div>

**Comment by bloussou** [comment]
A smaller reproducible example:
```python
import atoti as tt
import pandas as pd
from datetime import date

df = pd.DataFrame({"Date": [date(2000,3,31), date(2000,5,31), date(2000,8,31)]})
df['Date'] = pd.to_datetime(df['Date'])
df['Quarter'] = df['Date'].dt.to_period('Q')
session = tt.Session()
table = session.read_pandas(df, table_name="Pandas period")
```

**Comment by bloussou** [comment]
I will add support for all types of this list : [basics-dtypes](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes)

**Comment by bloussou** [comment]
Some points to answer before going further:
- [`pd.core.arrays._arrow_utils.ArrowIntervalType`](https://github.com/pandas-dev/pandas/blob/main/pandas/core/arrays/arrow/_arrow_utils.py) has a `storage_type` [`pa.struct`](https://arrow.apache.org/docs/python/generated/pyarrow.struct.html?highlight=struct#pyarrow.struct). I'm not sure we want to support such type and if yes how we want to support it? A possibility could be storing an array [left, right] after we have checked that left and right are of the same type
```python
dataframe = pd.DataFrame(
    {"interval": [pd.Interval(left=0, right=5), pd.Interval(left=7, right=10)]}
)
table = session.read_pandas(dataframe, table_name="Pandas interval")
print(table.head())
```
- [`pd.core.arrays._arrow_utils.ArrowPeriodType`](https://github.com/pandas-dev/pandas/blob/main/pandas/core/arrays/arrow/_arrow_utils.py) has a `storage_type` `int64` but I'm not sure we want to store this int value, shouldn't we stored the string repr of this value ?
- `Sparse[type]` conversion from pandas to arrow is not supported yet so I don't think we should support it atm
-

**Comment by bloussou** [comment]
@tht-activeviam what did you expect in your atoti table for your use case?

**Comment by tht-activeviam** [comment]
@bloussou the users wanted to create new columns for quarter(and)month based on the existing `Date` column. And of course they would expect the sorting to work on those columns.

**Comment by tibdex** [comment]
Let's not add support for a `Period` `DataType` for now as `create_date_hierarchy()` exists and is a different way to answer the need.
