### ISSUE TITLE
Distinct count - MdxException: Incompatible types.

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#6]
## Description
Create a measure with `tt.agg.count_distinct` on a level.
When I try to use the distinct count in filter, I encountered the error:

MdxException: Incompatible types. Cannot compare class java.lang.Long with class java.lang.String

![image](https://user-images.githubusercontent.com/35210495/77639509-d4d7a780-6f93-11ea-9a03-dc7cc0ecdb0d.png)

## Reproduce
Refer to attached
[distinct_count.zip](https://github.com/atoti/atoti/files/4386741/distinct_count.zip)

## Context
- Atoti version: 0.3.0.20200325172102
- Python version: 3.7.6
- Operating System: Windows 10 Pro

**Comment by fabiencelier** [comment]
We are expecting float values at some point in the computation of the median, I am adding the support for integer values too.
