### ISSUE TITLE
Documenting the context of the tutorial procedure

### ISSUE THREAD

**Issue by PierreG-activeviam** [atoti/atoti#611]
## Description

In the atoti tutorial page, when executing the instruction "python -m atoti.copy_tutorial tutorial"
from the Anaconda Powershell Prompt, the Anaconda environment gets corrupted
The following error message is displayed on the Anaconda Prompt
RuntimeWarning: 'atoti.copy_tutorial' found in sys.modules after import of package 'atoti', but prior to execution of 'atoti.copy_tutorial'; this may result in unpredictable behaviour 
And a prompt isn't then made available.

On the tutorial page https://docs.atoti.io/latest/getting_started/tutorial/tutorial.html 
We should explicitly specify from which user interface, which path, and which environment the instructions are to be executed. Especially, it should be highlighted to run it from the Anaconda Prompt, and **NOT the Anaconda Powershell Prompt**

**Comment by CamilleBlanco** [comment]
Hi Pierre, 

Could you please let us know which python and atoti versions you are using ? Is it the complete error message ?
