### ISSUE TITLE
In operator can throw exception on tables & cubes of a session

### ISSUE THREAD

**Issue by shahin-y** [atoti/atoti#614]
Hi,

the `in` operator on `Cubes` and `Tables` instances never evaluates to `False` but throws an exception instead.
It's not a big issue, since `"non-existent" in session.cubes.keys()` yields the expected behavior.

Having taken a quick look at this, it seems that both the the `Tables` and `Cubes` classes override the `DelegateMutableMapping`'s `__getitem__` method which would usually call their implementation of  the `_get_underlying` method.

## Steps to reproduce

```python
import atoti as tt

session = tt.Session()
table = session.create_table(name="some_table", types={"col": tt.type.STRING})

session.create_cube(table, name="some_cube")

print(f"Table found: {'some_table' in session.tables}. Cube found: {'some_cube' in session.cubes}")


try:
    print("non-existent" in session.tables)
except tt.exceptions.AtotiJavaException as e:
    print(f"Exception thrown: {e}")


# same for cubes, with a different exception though
try:
    session.cubes.__contains__("non-existent")
except TypeError as e:
    print(e)
```

## Environment

- atoti: 0.6.6
- Python: 3.8.10
- Operating System: Windows 10

**Comment by CamilleBlanco** [comment]
Hi Shahin 👋 

Thank you for reporting this, nicely explained! We are working on a fix, I will let you know when it's done 😄

**Comment by tibdex** [comment]
Hi, this will be fixed in the next release.
