### ISSUE TITLE
atoti.exceptions.AtotiJavaException: Write timeout

### ISSUE THREAD

**Issue by Ren4uD** [atoti/atoti#615]
Hello,

when applying measures to the cube, sometimes I get a crash with exception "Write timeout".
It's not always at the same location, but seems related to the connection with Java.
Does anyone experience this as well or know how to fix it ?

```
[...]
    measures[m].visible = False
  File "/python3.8/site-packages/atoti/measure.py", line 228, in visible
    self._java_api.publish_measures(self._cube_name)
  File "/python3.8/site-packages/atoti/_java_api.py", line 135, in wrapped_method
    raise AtotiJavaException(
atoti.exceptions.AtotiJavaException: Write timeout

```

- atoti: 0.6.5
- Python: 3.8
- Operating System: Linux

Any help is appreciated. Thank you !

**Comment by mailys-ds** [comment]
Hi,
Could you give more details about your code so that we can reproduce your issue please ?
Thanks.

**Comment by Ren4uD** [comment]
Hello,
After updating to version 0.6.6, the problem disappeared.
Thank you!
