### ISSUE TITLE
Add constants for classic measure formatters

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#62]
MDX formatters are quite ugly and difficult to handle. I think most of the usecases are classic one such as percentages, currency...
We could store some of them as constants somewhere in a module. This should cover most cases and provide examples for the brave ones who want to customize.

```python
m["test"] = tt.formatter.PERCENTAGE
```

I suggest we add the following constants:

```python
PERCENT = "DOUBLE[0.00%]"
NO_DECIMAL = "DOUBLE[#,###]"
currency("$") = "DOUBLE[#,##0.00 $]"
```

**Comment by tibdex** [comment]
These examples will be part of the API reference in the next release.
