### ISSUE TITLE
session_url reference in documentation

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#632]
## Description

Referring to the authentication configuration where there's the parameter [`provider_id`](https://docs.atoti.io/latest/lib/atoti/atoti.config.authentication.oidc_config.html#atoti.OidcConfig.provider_id), there is the following code snippet:

`f"{session_url}/login/oauth2/code/{provider_id}`

Should it be:

`f"{session_link()}/login/oauth2/code/{provider_id}`

**Comment by tht-activeviam** [comment]
`session.link()` ?
https://docs.atoti.io/latest/lib/atoti/atoti.session.html#atoti.Session.link

**Comment by tibdex** [comment]
`Session.link()` only works in a JupyterLab cell.

In this context, `session_url` is a variable representing the value of the URL of the session. There is no API call that we could use to replace it but it's fine: this URL is just for explanation purposes, it doesn't have to be actually built by the user.
