### ISSUE TITLE
Unhelpful error message when trying to agg an existing measure and no scope is provided

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#633]
## Description

When you try to create a new measure from the agg module and forget to pass a scope, the error message is this one:
```
AtotiJavaException: A measure aggregation cannot be performed without leaf levels
```
A developper has no idea of what is a leaf levels, a message indicating that you have to pass a scope (and maybe explaining why) would be more helpfull.

**Comment by CamilleBlanco** [comment]
Hi Alexis, 

I add this ticket to our backlog. Thank you the advice 😃

**Comment by tibdex** [comment]
Looks like a duplicate of #453.
