### ISSUE TITLE
Interpolation of values in vectors

### ISSUE THREAD

**Issue by mingkongwoo** [atoti/atoti#65]
Hi,

There is customer interest in the ability of Atoti to perform complex business calculation, such as interpolating the values in a vector based on time points corresponding to each item in the vector.

Currently, we have an example which relies on python to preprocess the input data and generate the interpolated vector before loading into Atoti. But this would not sell for our target prospect.

Could I request R&D to take a look at the logic and evaluate whether :
1. Can this be implemented in current Atoti version (I might have not found the right solution).
2. If not, can any new feature in future version of Atoti help to support this use-case?
2a. If feasible, how soon can the new feature be made available?

In short, the data contains vectors of PnL. Each value in the vector corresponds to a time point (with a date). The aim is to load these PnL vectors based on a standard set of time points. As the original vector is not aligned to the standard time points, we need to interpolate the PnL value based on the nearest adjacent time points from the standard time points set.

The aforementioned example can be found in github [here](https://github.com/activeviam/perso-mwo-python-activepivot-xva-collateral/tree/what-if). Specifically, the logic for interpolation is in [xvaAccelerator.py](https://github.com/activeviam/perso-mwo-python-activepivot-xva-collateral/blob/what-if/xvaAccelerator.py).

The example was implemented in ActiveViam-ee 0.3.0.

Please let me know how I can assist the team to expedite the evaluation of this request.
Thank you.

Regards,
Ming Kong

**Comment by fabiencelier** [comment]
Hello,
Could you provide an example input value(s), the expected output and an explanation of how to go from one to the other ?

**Comment by mingkongwoo** [comment]
Hi Fabien,

Here's a simplified example:
Input data is defined by PnL for 100 time points, and 1000 scenarios.
The most granular record contains:
[TradeId],[TimePoint],[PnL Vector]
where:
[PnL Vector] is a vector of 1000 PnL for each scenario.
[TimePoint] is an int corresponding to one of the value below.

Another file provides the dates corresponding to each TimePoint:
[TimePoint],[Date]
The TimePoints may not be continuous, example, 1,2,3,5,10,20,50,...
Example TimePoint 10 corresponds to 22-01-2018, TimePoint 20 corresponds to 01-02-2018.

The business requires the PnL for each TimePoint to be shifted earlier by example 5 days.
Let's say after shifting 5 days, the PnL corresponding previously to 01-02-2018 (TimePoint 20) now corresponds to 27-01-2018. So we need to compute the PnL on 27-01-2018 based on the PnL found on 22-01-2018 (TimePoint 10) and 01-02-2018 (TimePoint 20). This is done by linear interpolation (for example).

This is in short, what is implemented to get the interpolated PnL for all TimePoints on the original vectors.

**Comment by fabiencelier** [comment]
You can have a look at [date_shift](https://docs.atoti.io/0.3.1/lib/atoti.html?highlight=date_shift#atoti.date_shift) which lets you shift on a date hierarchy and has a parameter to choose how to interpolate missing values.

**Comment by mingkongwoo** [comment]
Hi Fabien, can the offset parameter for `date_shift` be based on a variable, such as a level in the cube, or another measure? The 5 days in above example is actually based on which some group that the trade belongs to. So, for some trades, it could be 10 days or some other numbers.

**Comment by fabiencelier** [comment]
Hello, you cannot provide a measure for the offset at the moment, I will create a another issue for that ! (note that your measure values will have to be valid offset input, i.e. strings like "1D", "2D", "3M"...)

Otherwise I think interpolating vectors works, have a look at this example where each vector has the value of the day so it is easy to follow:

```python
import atoti  as tt
import pandas as pd
import datetime as dt

df = pd.DataFrame({
    "date": [
        dt.date(2020,1,1),
        dt.date(2020,1,3),
        dt.date(2020,1,5),
        dt.date(2020,1,6),
        dt.date(2020,1,9),
        dt.date(2020,1,10),
    ],
    "v": [[1.,1.],
          [3.,3.],
          [5.,5.],
          [6.,6.],
          [9.,9.],
          [10.,10.]]
})

session = tt.create_session()
cube = session.create_cube(session.read_pandas(df, store_name="test"))
m, h, l = cube.measures, cube.hierarchies, cube.levels

m["shifted"] = tt.date_shift(
    m["v.SUM"],
    on=h["date"],
    offset="1D",
    method="interpolate"
)

cube.query(m["v.SUM"], m["shifted"], levels=l["date"])
```



date| v.SUM  | shifted  
-- | -- | --
2020-01-01|[1.0, 1.0] | [2.0, 2.0]
2020-01-03|[3.0, 3.0] | [4.0, 4.0]
2020-01-05|[5.0, 5.0] | [6.0, 6.0]
2020-01-06|[6.0, 6.0] | [7.0, 7.0]
2020-01-09|[9.0, 9.0] | [10.0, 10.0]
2020-01-10|[10.0, 10.0] | None

**Comment by fabiencelier** [comment]
Hello @mingkongwoo 
Can you try the dateshift intertpolate with the [workaround](https://github.com/atoti/atoti/issues/66#issuecomment-645913895) to shift differently depending on a measure and tell me if that works for you ?

**Comment by mingkongwoo** [comment]
Thanks Fabien for the suggested workaround. I'll have a look if this is possible, but as Romain said, the offset is mostly likely from a hierarchy, so I'll have to see if it can be tweaked as a measure.

**Comment by mingkongwoo** [comment]
Hi Fabien,
I implemented the workaround as suggested and I think it's almost working.
There is an issue downstream of this interpolated measure which gives me unexpected result and I'm not sure what the cause is. 
The notebook **"xva-collateral-atoti.ipynb"** is in github here:
https://github.com/activeviam/perso-mwo-python-activepivot-xva-collateral/tree/full_atoti

The measure after shifting and interpolation is `m["Shifted MtM Details"]`.
After that, it is chained to `m["collateralbalance1"]`, `m["collateralBalance2"]` and finally `m["Collateral Balance"]`.
When I visualise `m["collateralbalance1"]`, I can see the correct values that comes from `m["Shifted MtM Details"]`.
But when I visualise `m["Collateral Balance"]`, it seems the values of `m["collateralbalance1"]` becomes all zeroes.
I am slicing a specific CSA with MPR "-30D" to simplify the check.

Would you be able to have a quick look and see if I missed something? You should be able to run the notebook directly after u checkout the branch.
Please feel free to contact me on Slack to get more details from me if it's not clear from the description here.
Thanks

Regards,
Ming Kong

**Comment by mingkongwoo** [comment]
Just to add to the above: 
1. I use level in the condition of the workaround to shift differently that you suggested instead of measures. Could this be the problem?

2. If I do not use the above workaround, and just assign a native measure `m["MtM.SUM"]` to `m["Shifted MtM Details"]`, then I do not see the downstream measure `m["collateralbalance1"]` become all zeroes.

**Comment by fabiencelier** [comment]
```python
# Calculate collateral balance based on CSA parameters like thresholds and haircuts
m["collateralBalance1"] = tt.where(
    (m["Shifted MtM Details"] != None) & (m["Shifted MtM Details"] > m["CptyMax"]),
    (m["Shifted MtM Details"] - m["CptyThreshold.VALUE"] + m["IndependentAmount.SUM"])
    * m["Haircut.VALUE"],
    tt.where(
        (m["Shifted MtM Details"] != None) & (m["Shifted MtM Details"] < m["BankMax"]),
        (
            m["Shifted MtM Details"]
            + m["BankThreshold.VALUE"]
            - m["IndependentAmount.SUM"]
        )
        * m["Haircut.VALUE"],
        m["IndependentAmount.SUM"],
    ),
)
```

Your where measure has quite a lot of intermediary steps. When debugging it I advise you to define the intermediary steps as measures and display them to see which step fails.

I have added the measures representing the conditions to your pivot table:
```python
m["c1"] = (m["Shifted MtM Details"] != None) & (m["Shifted MtM Details"] > m["CptyMax"])
m["c2"] = (m["Shifted MtM Details"] != None) & (m["Shifted MtM Details"] < m["BankMax"])
```
These are almost always `false` so it returns `m["IndependentAmount.SUM"]` which is 0.0

I have no idea what you expect to be working differently so I let you investigate and tell me which step exactly is not what you expect

**Comment by mingkongwoo** [comment]
I try to define the intermediary steps as measures as such:
```m["c1"] = (m["Shifted MtM Details"] != None) & (m["Shifted MtM Details"] > m["CptyMax"])
m["c2"] = (m["Shifted MtM Details"] != None) & (m["Shifted MtM Details"] < m["BankMax"])

m["collateralBalance When Shifted MtM above CptyMax"] = (
    m["Shifted MtM Details"] - m["CptyThreshold.VALUE"] + m["IndependentAmount.SUM"]
) * m["Haircut.VALUE"]
m["collateralBalance When Shifted MtM below BankMax"] = (
    m["Shifted MtM Details"] + m["BankThreshold.VALUE"] - m["IndependentAmount.SUM"]
) * m["Haircut.VALUE"]

m["collateralBalance1"] = tt.where(
    m["c1"],
    m["collateralBalance When Shifted MtM above CptyMax"],
    tt.where(
        m["c2"],
        m["collateralBalance When Shifted MtM below BankMax"],
        m["IndependentAmount.SUM"]
    ),
)
```

But it's throwing an error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-43-7128e1720a99> in <module>
     10 ) * m["Haircut.VALUE"]
     11 
---> 12 m["collateralBalance1"] = tt.where(
     13     m["c1"],
     14     m["collateralBalance When Shifted MtM above CptyMax"],

~\Anaconda3\envs\atoti-0.4-plus\lib\site-packages\atoti\_functions\measure.py in where(condition, true_measure, false_measure)
    232 
    233     else:
--> 234         raise ValueError(
    235             "Incorrect condition type."
    236             f" Expected {Union[BooleanMeasure, LevelCondition, MultiCondition]}"

ValueError: Incorrect condition type. Expected typing.Union[atoti._measures.boolean_measure.BooleanMeasure, atoti._level_conditions.LevelCondition, atoti._multi_condition.MultiCondition] but got <class 'atoti._measures.named_measure.NamedMeasure'>.
```

**Comment by fabiencelier** [comment]
This is due to the bug #94, named measures cannot be used in the where. Just don't use m["c1"] and m["c2"] in the where

**Comment by mingkongwoo** [comment]
Hi Fabien,
I finally got the expected results after re-arranging the measure chain. I"m not sure if this is the best solution though, so I've abstracted a simplified example for your review and advice.
If you could pull from this [full_atoti_test branch](https://github.com/activeviam/perso-mwo-python-activepivot-xva-collateral/tree/full_atoti_test), you will find a **ShiftExample.ipynb** notebook which reads data from **test_data** folder.

The underlying measure is `Value.SUM`.
It is shifted by different number of days according to the CSAId, into measure `Shifted Value`.
I want the first 3 dates to have fixed value of -1, the remaining dates will have the shifted value, as shown in measure `balance4` in the following screen grab.
![image](https://user-images.githubusercontent.com/30063740/86215977-e55d7680-bbaf-11ea-82f5-4f0c0307374a.png)
I can choose to show the total aggregated across all CSAId, as in the following screen.
![image](https://user-images.githubusercontent.com/30063740/86216413-96fca780-bbb0-11ea-86e4-e028eaac7b27.png)

I did this by a chain of measures where I had to use one measure to check for the first 3 dates and return -1
```
m["TimePoint"] = lvl["TimePoint"]
m["balance1"] = tt.where(
    m["TimePoint"] < 3,
    -1,
)
```
and then chain it below to check if empty value, return the shifted value.
```
m["balance3"] = tt.where(m["balance2"] != None, m["balance2"], m["Shifted Value"])
```
When I try to combine them in one measure, I get partially correct result (only first 3 dates return -1, the rest are empty).
Could you see if this can be done so that the measure chain is simpler? Or generally any areas of improvement in the way the measures are defined?
Thanks.

Regards,
Ming Kong

**Comment by fabiencelier** [comment]
Hello you can simplify a bit your merasures.

First define a timepoint measure with the single value so it is defined for each date without the need to express the timepoint level:
```python
m["TimePoint"] = tt.agg.single_value(data_store["TimePoint"])
```
Then for each CSAId you can take either the shifted value or -1, and finally sum it:

```python
m["balance"] = tt.agg.sum(
    tt.where(
        m["TimePoint"] >= 3,
        m["Shifted Value"],
        -1,
    ),
    scope=tt.scope.origin(
        lvl["CSAId"]
    ),
)
```
If that's OK for you can we close this issue ?

**Comment by mingkongwoo** [comment]
Thanks. Closing this issue.
