### ISSUE TITLE
Java atoti exception, joining tables with similar column names breaks cube

### ISSUE THREAD

**Issue by Wi1iku** [atoti/atoti#655]
## Steps to reproduce

        def create_schema(self):
        strucs0 = self.get_property(GER_BLOCK, 'ger.structure.details').split(',')
        for strucsItem in strucs0:
            strucsItem = strucsItem[2:(len(strucsItem) - 1)]
            strucs = self.get_property(GER_BLOCK, strucsItem).split(',')
            for block in strucs:
                segment = block.split(';')
                nombre = segment[0]
                lista = ['Date', 'CountryCode']

                num = int(segment[1])
                lista.append(nombre)
                aux = 1
                while aux < num - 1:
                    lista.append(nombre + " Level " + str(aux))
                    aux += 1
                lista.append('Portfolio')
                df = pd.DataFrame(columns=lista)
                ###crear tabla
                for column in df.columns:
                    df[column] = df[column].astype('string')

                self.create_table_from_df(df, 'GER_'+nombre,
                                          ['Date', 'Portfolio'],
                                          {})

                # temporal no va aqui
                # #self.join_stores(nombre, PORTFOLIO_STORE, {'Date': 'asOfDate', 'Portfolio': 'portfolio'})

        pass

###Create Join

        strucs0 = self.get_property(GER_BLOCK, 'ger.structure.details').split(',')
        for strucsItem in strucs0:
            strucsItem = strucsItem[2:(len(strucsItem) - 1)]
            strucs = self.get_property(GER_BLOCK, strucsItem).split(',')
            for block in strucs:
                segment = block.split(';')
                nombre = segment[0]
                self.join_stores(PORTFOLIO_STORE, 'GER_' + nombre,
                                 {'asOfDate': 'Date', 'portfolio': 'Portfolio', 'countryCode':'CountryCode'})
`

## Actual Result

atoti.exceptions.AtotiJavaException: These two paths are not reachable from one another and point to the same field: JoinPath(joinNames=[Sensitivities_to_TradeDetails, TradeDetails_to_Portfolio, Portfolio_to_GER_FX ESTRUCTURAL VAR]) and JoinPath(joinNames=[Sensitivities_to_TradeDetails, TradeDetails_to_Portfolio, Portfolio_to_GER_BDE_21_60])

referenced tables change

## Expected Result
Session running without fault
## Environment
- atoti: 0.6.6
- Python: 3.10.0
- Operating system: win32

## Added notes
The problems seems to be related to multiple tables with identically named collumns (Date, CountryCode and Portofolio) joining the same table
The cube works when fields Date, Portfolio and CountryCode have assigned different names between tables.

**Comment by bloussou** [comment]
Hello,
Thanks for reporting this issue. It was a known limitation that will be fixed in the next release!

**Comment by Wi1iku** [comment]
Hi
Thank you for responding so fast!
