### ISSUE TITLE
Support measure as the offset of the date_shift function

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#66]
Related to #65 

At the moment only strings are supported as the "offset" argument of [date_shift](https://docs.atoti.io/0.4.0/lib/atoti.html#atoti.date_shift), we should also support string measures to be able to shift differently on each member

The measure values will have to be strings like currently supported values, i.e. "1D", "2W", "1Y"...

**Comment by rcolle** [comment]
The potential issue here will be that we'll need to parse the offset for every single location to evaluate. We'll have to measure how costly it is compared to the amount of work done for during the shift.

**Comment by fabiencelier** [comment]
I have just realized there is a workaround if there is a limited number of offset values, which is to build all the shifted value then use some tt.where.

for instance with an "offset" measure that can be "1", "2" or "3" one can do:

```python
m["shifted 1D"] = tt.date_shift(m["A"], on=h["date"], offset="1D", method="interpolate")
m["shifted 2D"] = tt.date_shift(m["A"], on=h["date"], offset="2D", method="interpolate")
m["shifted 3D"] = tt.date_shift(m["A"], on=h["date"], offset="3D", method="interpolate")

m["shifted"] = tt.where(
   m["offset"] == "1D",
   m["shifted 1D"],
   tt.where(
     m["offset"] == "2",
     m["shifted 2D"],
     tt.where(
       m["offset"] == "3",
       m["shifted 3D"],
     )
  )
)
```

**Comment by fabiencelier** [comment]
> The potential issue here will be that we'll need to parse the offset for every single location to evaluate. We'll have to measure how costly it is compared to the amount of work done for during the shift.

There is also the issue that with a constant we can easily shift all the dates in one pass while with different offset we will have to do multiple pass.

We will probably need to have 2 versions, one optimized for constant shifting and one slower with variable shift.

**Comment by rcolle** [comment]
Actually, I think that most of the time the shift period will depend on the value of a level.

This is likely the case in #65 where the value is "based on which [some] group [that] the trade belongs to". So for a given group there is a shift amount, and therefore  this "group" level must be a required level of the shift measure so that we can get the value.
I believe we can take advantage of this to keep on using a single pass for the computation.

**Comment by mingkongwoo** [comment]
Just to add, this workaround would not work if this is a source simulation scenario and we want to change the offset to a different number. So being able to support a variable offset based on level and measure for `date_shift` is necessary.

**Comment by tibdex** [comment]
Closing this until we have a real use case requiring it.
