### ISSUE TITLE
403: Saving dashboard with one user is forbidden.

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#676]
## Steps to reproduce

Source: [01-Basic-authentication.ipynb](https://github.com/atoti/notebooks/blob/master/notebooks/security-implementation/01-Basic-authentication.ipynb)

Login as "Restaurant Manager", I tried to perform a "Save As" on the existing dashboard and I encountered the following:
![image](https://user-images.githubusercontent.com/35210495/187407998-904e819a-2148-4490-9edf-c92d942ffaf5.png)

## Environment
- atoti: 0.7.0
- Python: 3.9.12
- Operating system: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/9451825/server.log)

**Comment by bloussou** [comment]
Hello,
In `0.7.0` the rest version of AP endpoint should be `v8zz1`. Are you sure that your installation of atoti is correct ? I don't know if it is possible or not to change the endpoint for this but it is weird to try to access the `v7zz1` endpoint in `0.7.0`

**Comment by HuifangYeo** [comment]
Hi Brieuc,

in terms of permission, theoretically I shouldn't have a problem because I'm trying to do a "Save As" which means it's a new dashboard created by myself, from a dashboard that is granted access to me.

Yes, the version is correct. I have no idea how that happened. But could it be because I upgraded the notebook from 0.6.6 to 0.7.0?

**Comment by EricDallAgnol** [comment]
Hi @HuifangYeo ,
To give also a feedback as another atoti user, I faced this exact same issue.
I had a BasicAuth and I've upgraded from 0.6.6 to 0.7.0.

The issue, in my case, was tied to the content server. If I removed the content.mv.db (my 'user_content'), so basically start from a new CS, the issue vanished.
After having investigated with on AV member, between 0.6.6 and 0.7.0 changes have been made on the CS, especially one permission issue that was wrongly set. And by migrating the CS from 0.6.6 to 0.7.0, this permission issue is not automatically fixed.

## Solution provided by AV :
I've been reliably informed by my colleague that the CS file created by atoti-0.6.6 **didn't set the writer role for the thumbnails directory**. However, this has been resolved in 0.7.0 and this is probably why a new CS db file works fine in 0.7.0.

Now to fix this, you can do one of 2 things here,

Manually edit the JSON file of the content server to have the appropriate permissions.
Open up the content server UI using this [URL](http://localhost:9000/admin/ui/index.html#/content) in the 0.6.6 version and add the appropriate role on there. An example of the content server UI from 0.7.0 looks like,
![image](https://user-images.githubusercontent.com/83015366/194009713-ed629d30-0f37-4c07-8c37-9d947c0caaaf.png)

----

Hope it will help,

Eric

@bloussou If needed, please find here the UKS ticket for that issue : https://support.activeviam.com/jira/browse/UKS-5156?jql=
