### ISSUE TITLE
Duplicate field name on multiple stores issue

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#68]
# Case A: duplicate fields are store keys

## Steps to reproduce

Issue reported by a user
```python
import pandas as pd
import atoti

main_df = pd.DataFrame(
    data={
        "id": [0, 1],
        "store": ["C", "D"],
        "product": ["A", "B"],
    }
)

secondary_df = pd.DataFrame(
    data={"id": [0, 1], "store": ["C", "D"],}
)

session = atoti.create_session()

main_store = session.read_pandas(
    main_df, store_name="main", keys=["id"]
)

secondary_store = session.read_pandas(
    secondary_df, store_name="secondary", keys=["id"]
)

main_store.join(secondary_store, mapping={"store": "store"})

cube = session.create_cube(main_store)
```

## Actual Result

```
AtotiJavaException: The partially joined field id from store secondary is also used as a level in a hierarchy id@Hierarchies
```

## Expected Result

The exception occurs during create cube and it is not necessarily clear that the problem happened at the join. Would it be possible to handle it by creating different dimension for each store for example?

Workaround is easy: rename columns.

Note: the example above is not the best because you would probably want to join on ids directly...

# Case B: duplicate fields are not store keys

## Steps to reproduce

Encountered this problem with a data sets that had a URL field for each store.
```python
import pandas as pd
import atoti

main_df = pd.DataFrame(
    data={
        "url": ["urlA","urlB"],
        "store": ["C", "D"],
        "product": ["A", "B"],
    }
)

secondary_df = pd.DataFrame(
    data={"url": ["urlC", "urlD"], "store": ["C", "D"],}
)

session = atoti.create_session()

main_store = session.read_pandas(
    main_df, store_name="main"
)

secondary_store = session.read_pandas(
    secondary_df, store_name="secondary"
)

main_store.join(secondary_store, mapping={"store": "store"})

cube = session.create_cube(main_store)
```

## Actual Result

No exception is thrown. Cube visualize display only one of the url column: 
![image](https://user-images.githubusercontent.com/4415696/84949673-e097bd80-b0ed-11ea-899c-a24775505409.png)

## Expected Result

I would expect it to be consistent with the case A (i.e. error). But ideally no error would be thrown and we would handle it by creating different dimension for each store. If this is too complex I would expect at least a warning letting me know that one of my field will be ignored. We can't assume users know all of their columns and know if there are duplicates.

Workaround is easy: rename columns.

# Environment

- atoti: 0.4.2.20200617181308
- Python: 3.8.3
- Operating System: linux

**Comment by fabiencelier** [comment]
I agree with you:
 - In an ideal situation this should work. We will be one step closer with https://github.com/activeviam/atoti/issues/1362 when all the auto hierarchies are put in different dimensions by default
 - Until then throwing would be better

**Comment by fabiencelier** [comment]
In 0.5.0 this problem should fixed:

 - Hierarchies will be placed in a dimension which name is the store they are based on
 - Store creation methods will have a `hierarchized_columns` parameter to specifiy which columns must be automatically converted into a hierarchy.
