### ISSUE TITLE
How to create a tabular view?

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#69]
## Description

Reported by a user.

Desired output:
![image](https://user-images.githubusercontent.com/4415696/84950541-5fd9c100-b0ef-11ea-9d3f-3fad7f618129.png)

Tried with pivot table:
![image](https://user-images.githubusercontent.com/4415696/84950583-6b2cec80-b0ef-11ea-83b2-c1eeedbd1750.png)

When I put Currency in columns, I get the following result:
![image](https://user-images.githubusercontent.com/4415696/84950591-6f590a00-b0ef-11ea-9cba-25826231953c.png)

When I put it in rows, I get the following result:
![image](https://user-images.githubusercontent.com/4415696/84950626-7aac3580-b0ef-11ea-8e90-fb950d5f4019.png)

This is much closer to the desired output but still has some stuff in the table I don’t want, i.e. exchange rates for each currency. It's pretty straightforward to create this via python but I’m not sure how to do it with atoti/the UI.

## Context

- atoti 0.4.1

**Comment by fabiencelier** [comment]
On a pivot table widget (either in the app or in the extension) you can right click on the header > Display as... > Table

![pivot table](https://user-images.githubusercontent.com/17087544/86374734-2ffcf280-bc85-11ea-97d6-351205b1dcf2.png)

This switches the view to a table like that:

![table](https://user-images.githubusercontent.com/17087544/86374741-325f4c80-bc85-11ea-8584-44a45d7988e7.png)

**Comment by jbe456** [comment]
What you showcased is a pivot table displayed as a tabular. You'll notice the subtotals and grand total are displayed in your table.

A regular tabular view on the other hand is a "columnar" table with no subtotals/grand totals. I know how to do it with the pivot table:
- display as table
- only use levels when adding elements to the rows

The question raised by the user hints that it's not discoverable. Before, we used to have the tabular view as one of the available widgets. I don't know to which extent people need such type of view and in which use case though so maybe we don't have enough data to decide to put it back.

**Comment by tibdex** [comment]
Pivot tables are the only supported kind of tables for now. You can follow our https://docs.atoti.io/latest/changelog.html to know when more types will be supported.
