### ISSUE TITLE
Fractional exponential for negative values returns nan

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#692]
## Steps to reproduce

Referring to the below, when `Last price.SUM` is negative and the power is a decimal value, the returned value is NaN.
![image](https://user-images.githubusercontent.com/35210495/190989992-36c83d63-d8b7-4106-ba3e-b98f22b33e6a.png)

However `(-0.1747/0.007)**0.33` in Python does returns the value `(1.471727562895751+2.4885554033302424j)`

Please refer to the attached notebook: [Untitled.zip](https://github.com/atoti/atoti/files/9597763/Untitled.zip)

## Environment
- atoti: 0.7.0
- Python: 3.9.13
- Operating system: win32

**Comment by Skyscimitar** [comment]
Hi Huifang,

Indeed a negative number to a fractional exponent returns a complex number and not a real number. (You can see the trailing `j` in the Python result).

AP does not support complex numbers so this is why you get a `NaN` value.
