### ISSUE TITLE
Create date hierarchy for lookup table

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#693]
## Steps to reproduce
Hi,

This is more of an understanding question than an issue. I have the following schema:
![image](https://user-images.githubusercontent.com/35210495/191191587-c706bde8-f3b0-479e-abaf-9e89c47440bd.png)

I would like to create date hierarchies: 
```
cube.create_date_hierarchy(
    "Hierarchical dates",
    column=dates_tbl["Historical Dates"],
    levels={"Year": "yyyy", "Quarter": "Q", "Month": "MM", "Day": "d"},
)
```
But I get the following exception:

```
AtotiJavaException: Cannot build a date hierarchy on field Historical Dates from table Historical Dates, because it cannot be reached from the base table: Portfolios Allocation following full joins.
```

Why can't we build the hierarchies when there is no join?

## Environment

- atoti: 0.7.0
- Python: 3.9.13
- Operating system: win32

**Comment by Skyscimitar** [comment]
Hi Huifang,
This isn't supported at the moment because multi-level hierarchies cannot be created on partially joined tables.
When support for multi-level hierarchies on partially joined tables we will add support for creating date hierarchies on partially joined columns.
