### ISSUE TITLE
session.read_csv to support public file accessible via http(s)

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#7]
## Description
I have data files on AWS S3 and it is accessible via a public url. 
I would like to be able to use atoti session to read the file e.g.:

`asset_positions_store = session.read_csv('http://data.atoti.io/notebooks/collateral-shortfall-monitoring/assets_positions.csv', keys=['Account','Asset_Code'], store_name='asset_positions_store')`

Currently I am unable to do so.

**Comment by rcolle** [comment]
You can read s3 files directly with the s3 naming scheme. 
E.g. `read_csv("s3://bucket/file", ...)`

**Comment by HuifangYeo** [comment]
using s3 naming scheme would require AWS authentication and there's no way I can provide via the function call.

Currently I am using `wget` to download the files to local first before consuming it with read_csv.

**Comment by fabiencelier** [comment]
There a multiple points here:
 - Reading public S3 files should work with the s3:// path without login
 - If we want it as a feature, we need to document how to read private S3 files.
 - Do we want to support public files with http(s):// path ?

**Comment by SamTaz** [comment]
> Currently I am using `wget` to download the files to local first before consuming it with read_csv.

Since pandas supports it, another way is to download the data directly into a pandas dataframe, then you can do some data massaging with pandas and import it in atoti with a `read_pandas`.

**Comment by rcolle** [comment]
@HuifangYeo can you confirm that you can use the s3 addressing scheme on your bucket if it is publicly accessible (I assume so since it's publicly accessible via http)?

**Comment by HuifangYeo** [comment]
Hi @rcolle,

The bucket access is public:
![image](https://user-images.githubusercontent.com/35210495/78628587-1edf5800-78c7-11ea-8e3b-9bc1d7485255.png)

I tried running below:
`x1 = session.read_csv('s3://data.atoti.io/test/assets_positions.csv', keys=['Account','Asset_Code'], store_name='x1')`

I get this exception:
``` 
AtotiJavaException: An error occurred in the JVM:
An error occurred while calling o2.createStoreFromCsv.
: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: DD4990643B87B5AA; S3 Extended Request ID: 3IM1lk2gRgjU97l6POVDXJ4euAbjbVZeF5SvU5DLsN2lZ11NFB3cMHloXZ/BY6gv0SFJVsim27o=), S3 Extended Request ID: 3IM1lk2gRgjU97l6POVDXJ4euAbjbVZeF5SvU5DLsN2lZ11NFB3cMHloXZ/BY6gv0SFJVsim27o=
```

**Comment by rcolle** [comment]
It doesn't look like the public access is correctly set up. 
You can check public access by trying to access it via https://data.atoti.io.s3.amazonaws.com/ in a private session.

Since it's in the activeviam account I went ahead and fixed it for you. This should now work.
![Untitled](https://user-images.githubusercontent.com/26255381/78641629-ce113480-78b1-11ea-8e6f-a8664bfeed23.png)

**Comment by HuifangYeo** [comment]
Hi @rcolle,

I have used wget to download the file locally before consuming it with Atoti. So it is not critical for me to have this feature.

I just thought that it would be useful for users to have it.

Regards

**Comment by rcolle** [comment]
ActivePivot does not support reading directly from http. Moreover you would lose all the performance improvements that come with reading from an object storage (S3, Azure Blob, GCS), and `https` would be especially slow. So we don't plan in supporting it in the near future.

You can nonetheless directly access your data without the need for `wget` with the s3 addressing scheme, which I strongly recommend in that case.
