### ISSUE TITLE
Can't create hierarchies from int columns 

### ISSUE THREAD

**Issue by ollien1** [atoti/atoti#701]
I believe this is a new issue as of 0.7.0, possibly down to the changes made to the default behaviour of int columns when creating cubes in auto mode.

When trying to create hierarchies from an int field the following error is thrown:

> AtotiJavaException: Cannot create hierarchy on column `Bucket` with a null default value, set the column's default value to a non-null value.

This can be easily recreated using the [sbm notebook](https://github.com/atoti/notebooks/blob/main/notebooks/sbm/main.ipynb). Cell 9 should throw the error.

As a workaround you can set the default value of the columns in question when creating the table, however, this is not necessary in the Java API (int columns will automatically default to 0 for instance). Is this is expected behaviour? If so feel free to close this issue.

**Comment by tibdex** [comment]
> Is this is expected behaviour?

Yes this is the expected behavior: hierarchies cannot contain levels corresponding to nullable columns.

> As a workaround you can set the default value of the columns in question when creating the table

If you realize that you need a nullable column to be turned into a level after creating the cube, you don't necessarily have to recreate the cube: [you can change the default value once](https://docs.atoti.io/0.7.0/lib/atoti/atoti.column.html#atoti.Column.default_value).

>  in the Java API (int columns will automatically default to 0 for instance)

Just to let you know: in atoti, the default value for numeric columns is `None` because that's often what you want for measures and numeric columns are mainly used for measures.

**Comment by ollien1** [comment]
Hi Thibault,

Thanks for the response. I did just notice this in the changelog too:

> Ability to create a [Hierarchy](https://docs.atoti.io/latest/lib/atoti/atoti.hierarchy.html#atoti.Hierarchy) on a nullable [Column](https://docs.atoti.io/latest/lib/atoti/atoti.column.html#atoti.Column). Set the column’s [default_value](https://docs.atoti.io/latest/lib/atoti/atoti.column.html#atoti.Column.default_value) to something different than None before creating the [Hierarchy](https://docs.atoti.io/latest/lib/atoti/atoti.hierarchy.html#atoti.Hierarchy) instead.

Regarding your comment:

> Just to let you know: in atoti, the default value for numeric columns is None because that's often what you want for measures and numeric columns are mainly used for measures.

I tend to agree that numeric columns should typically be used for measures, though this is not the cause in a lot of the notebooks in the gallery repo so a lot of them currently have issues (perhaps I should make a ticket in that repo instead).

As an aside it doesn't even seem possible to define a null default value to an in column in Java (in 5.10 at least). When I try I get this log:

> The field IntField from store Orders is nullable. The configuration has been overridden to enforce a non nullable field.

Though maybe this is a core change specific to Python or a change in AP6.

Anyways I'll close this as it's expected behaviour.
