### ISSUE TITLE
Unexepected exception while contributing to BITMAP column

### ISSUE THREAD

**Issue by EricDallAgnol** [atoti/atoti#706]
Hi team 👋 

Here is an issue I've found while using the [aggregate provider](https://docs.atoti.io/latest/lib/atoti/atoti.aggregate_provider.aggregate_provider.html#atoti.AggregateProvider).

Let me know if you need more inputs from me,
Thanks,

## Steps to reproduce

Please find here a small code to reproduce the issue :

````python
import atoti as tt
import pandas as pd
from enum import Enum

class Tables(str, Enum):
    BASE_STORE = "BaseStore"

def _create_base_table(session: tt.session.Session) -> tt.Table:
    return session.create_table(f"{Tables.BASE_STORE}",
    keys=["Id"],
    types={"Id" : tt.type.STRING,"value": tt.type.DOUBLE_ARRAY})

session = tt.Session(name="Issue BITMAP")
_create_base_table(session)

session.create_cube(session.tables[Tables.BASE_STORE], name="hello", mode="no_measures")
cube = session.cubes["hello"]

# Create basic measure
cube.measures["value"] = tt.agg.single_value(session.tables[Tables.BASE_STORE]["value"])

# Aggregate Provider
cube.aggregate_providers.update(
        {
            "Provider": tt.AggregateProvider(
                key="bitmap",
                levels=[
                    cube.levels["Id"],
                ],
                measures=[cube.measures["value"]],
            ),
        }
    )

# Populate a first time my table
df = pd.DataFrame({
        "Id" : ["Trade1", "Trade2",],
        "value" : [[1.0,0.5], [1.2,1.5]]
})
session.tables[Tables.BASE_STORE].load_pandas(df)

# Define a slightly different df to be loaded instead
df = pd.DataFrame({
        "Id" : ["Trade1", "Trade4"],
        "value" : [[2.0,0.5], [1.2,2.0]]
})

# Batch in the same transaction drop and load
with session.start_transaction():
    # By defining criteria on the drop it failed
    session.tables[Tables.BASE_STORE].drop({"Id": "Trade1"})
    # However without criteria it works
    # session.tables[Tables.BASE_STORE].drop()

    # ERROR
    session.tables[Tables.BASE_STORE].load_pandas(df)
```` 

NOTE: 
- It is working if no criteria is set in the drop _(I noticed however that I will work in my example if I set the criteria on "Trade2" instead ie a key that is not loaded again in the same transaction. I've checked the transactions rules - see [here](https://support.activeviam.com/confluence/display/AP5/Datastore+Transactions), but this case is not explicitly set as non-authorized)_

- It is working if no aggregate provider is set

- Also, if I put my drop with the criteria in a separate transaction before the second load, it works as well. _However, putting it in a separate transaction is risky because if for whatever the reason the transaction for the second load failed, the transaction will be rollback but we will have our table with its state after the drop not with the first load, and we want to avoid that so that the table always contains data_

## Actual Result
Here is the stack trace  :

````python
---------------------------------------------------------------------------
AtotiJavaException                        Traceback (most recent call last)
Input In [163], in <cell line: 6>()
      8 session.tables[Tables.BASE_STORE].drop({"Id": "Trade1"})
      9 # However without criteria it works
     10 # session.tables[Tables.BASE_STORE].drop()
---> 11 session.tables[Tables.BASE_STORE].load_pandas(df)

File c:\dev\python64\lib\site-packages\atoti\_transaction.py:65, in Transaction.__exit__(self, exception_type, exception_instance, exception_traceback)
     63 has_succeeded = exception_instance is None
     64 _transaction_id_context.set(None)
---> 65 self._end(has_succeeded=has_succeeded, transaction_id=self._id)

File c:\dev\python64\lib\site-packages\atoti\_java_api.py:158, in _enhance_py4j_errors.<locals>.wrapped_method(self, *args, **kwargs)
    152 except Py4JJavaError as java_exception:
    153     cause = (
    154         str(java_exception)
    155         if get_env_flag(_ATOTI_VERBOSE_JAVA_EXCEPTIONS)
    156         else self.get_throwable_root_cause(java_exception.java_exception)
    157     )
--> 158     raise AtotiJavaException(
    159         cause,
    160         java_traceback=str(java_exception),
    161         java_exception=java_exception,
    162     ) from None

AtotiJavaException: Unexpected exception while contributing to BITMAP column value with value [doubleVector[2]{1.0, ...}] from field [BaseStore.value]

````

## Expected Result

My second transaction is successful and I have in my table : Trade1, Trade2 and Trade4 with Trade1 that has an updated value

## Environment

- atoti: 0.7.0
- Python: 3.8.3
- Operating system: win32

**Comment by mailys-ds** [comment]
Hi Eric,
Thanks for reporting this issue, we'll investigate it and come back to you as soon as we find a fix.

**Comment by mailys-ds** [comment]
Hi Eric, 

Just a small update on your issue: 

The bug is related to the impossibility of dropping values that are used by the `single_value` measure when those values are used by this `single_value` measure of an aggregate provider.
In atoti 0.7.2, an exception will be raised when using a measure in an aggregate provider on which we can't drop data.

In your usecase, removing the `aggregate provider` will fix your code without increasing your query time. Indeed, your measure `m["Value"]` is directly created by reading value from the datastore, with no intermediate aggregation, so using an `aggregate provider` does not spped up your query in this case, as there is no intermediate aggregation stored by the aggregate provider, explained in the documentation: _An aggregate provider uses additional memory to store the intermediate aggregates._

**Comment by EricDallAgnol** [comment]
Hi Mailys,

Thanks for the update and the explaination.
Yes it makes sense indeed. Actually, I was a bit confused also about the behaviour of the `tt.agg.single_value` but I had a chance to clarify that with one of your colleague and  that's now clear for me :) 

Thanks,
