### ISSUE TITLE
Query is not returned in raw mode

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#712]
## Steps to reproduce
I have a query that involves parameter simulation. In pretty mode, the below is returned:
![image](https://user-images.githubusercontent.com/35210495/195518736-c0f38122-c93e-4ed7-9c7c-c817e6803a24.png)

In raw mode, nothing is returned:
![image](https://user-images.githubusercontent.com/35210495/195518855-b1740647-b24f-46ee-8e92-a6c07a68ed7e.png)

## Environment
- atoti: 0.7.0
- Python: 3.9.13
- Operating system: win32

**Comment by bloussou** [comment]
Do you have the code to reproduce the issue ? I did not manage to reproduce it using the code from the documentation example.

**Comment by HuifangYeo** [comment]
Hi @bloussou ,

I can't always replicate it as I believe it has to do with a series of activities (e.g. some table inserts in between)
e.g. in the below use case, you can see some of the queries with the `mode="raw"` commented off.
However, when I try to replicate it for this ticket, it seems to work fine when I just ran the whole notebook as it is.
[issue712.zip](https://github.com/atoti/atoti/files/9856450/issue712.zip)
