### ISSUE TITLE
bad operand type for unary ~: `method`

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#717]
## Steps to reproduce
The following deprecated message is displayed:
![image](https://user-images.githubusercontent.com/35210495/197769308-299d14ed-aa9a-49e2-a3be-371487dba142.png)

But when updating to `~level.isnull()`, occasionally I encounter the below:
![image](https://user-images.githubusercontent.com/35210495/197769486-a86e05bf-7e95-420c-8a86-c420ba132b0c.png)

I revert back to `!= None` and then `~level.isnull()` works again after:
![image](https://user-images.githubusercontent.com/35210495/197769622-887ac6d0-3800-46cc-acf5-6cbe3c65e600.png)

Use case: https://github.com/atoti/notebooks/blob/main//notebooks/01-use-cases/finance/insurance/customer360/03-main-csv.ipynb

## Environment

- atoti: 0.7.1
- Python: 3.9.13
- Operating system: win32

**Comment by Skyscimitar** [comment]
Hi Huifang,
In the second example there is actually a syntax error:

```diff
- (~l["NCD_YEARS"].isnull()) & (~l["PLAN_TYPE"].isnull))
+ (~l["NCD_YEARS"].isnull()) & (~l["PLAN_TYPE"].isnull()))
```

**Comment by HuifangYeo** [comment]
Thanks @Skyscimitar for spotting my mistake!
