### ISSUE TITLE
TypeError when running a QuerySession.query_mdx

### ISSUE THREAD

**Issue by mfabiani-av** [atoti/atoti#718]
## Steps to reproduce
- Create a QuerySession (mine is against AP 5.11)
`session = tt.QuerySession(url="http://localhost:9090",auth=tt.BasicAuthentication(username='***',password='***'))`
- Run a simple query
`session.query_mdx("SELECT NON EMPTY [AsOfDate].[AsOfDate].[AsOfDate].Members ON ROWS FROM [Cube] CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS")`

Although I get a result and it is displayed, I also get an error. Note that I get the same error if I use Cube.query(...).

## Actual Result

```
TypeError                                 Traceback (most recent call last)
File ~\AppData\Local\pypoetry\Cache\virtualenvs\atoti-latest-NxxypLr2-py3.10\lib\site-packages\IPython\core\formatters.py:973, in MimeBundleFormatter.__call__(self, obj, include, exclude)
    970     method = get_real_method(obj, self.print_method)
    972     if method is not None:
--> 973         return method(include=include, exclude=exclude)
    974     return None
    975 else:

TypeError: QueryResult._repr_mimebundle_() got some positional-only arguments passed as keyword arguments: 'include, exclude'
```
## Expected Result
No error?

## Environment
- atoti: 0.7.1
- Python: 3.10.8
- Operating system: win32

**Comment by mfabiani-av** [comment]
If you want to know the version of all the dependencies I can attach the poetry.lock file.

**Comment by mfabiani-av** [comment]
[poetry.zip](https://github.com/atoti/atoti/files/9871162/poetry.zip)

**Comment by tibdex** [comment]
@mfabiani-av could you try [this experimental build](https://github.com/activeviam/atoti/pull/4092)?

**Comment by mfabiani-av** [comment]
Error is gone with the experimental build.
