### ISSUE TITLE
Notebook hanged upon broken visualization

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#719]
## Steps to reproduce
I have some existing visualization. After I change slicing hierarchy, some visualizations broke and the notebook hangs:
![image](https://user-images.githubusercontent.com/35210495/198190663-7b6feaf9-291f-40ea-9e44-dece3743ecee.png)

## Environment

- atoti: 0.7.1
- Operating system: win32

**Comment by Skyscimitar** [comment]
Most likely related to https://github.com/atoti/atoti/issues/334 and https://github.com/atoti/atoti/issues/406

**Comment by tibdex** [comment]
The first error is indeed related to these issues but the fact that the notebook hangs indefinitely is due to this [internal issue](https://support.activeviam.com/jira/browse/UI-7920).
