### ISSUE TITLE
Google colab support

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#72]
## Description

Requested multiple time by users:

Does atoti work with google colab?

It does not seem to be possible at the moment: Google colab seems to use Python 3.6 which is incompatible with the required atoti Python version.

**Comment by fabiencelier** [comment]
From [this answer](https://stackoverflow.com/questions/60775160/install-python-3-8-kernel-in-google-colaboratory?noredirect=1&lq=1) it looks like there is no way to run Python >= 3.7 on google colab so I am closing this issue.

Feel free to reopen once Python >= 3.7 is supported.
