### ISSUE TITLE
loading_report made private but is still reflected in message.

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#721]
## Steps to reproduce
`loading_report` has been removed since 0.7.0 but the message is still showing: 
![image](https://user-images.githubusercontent.com/35210495/199940579-6a52d541-bfcf-4bb9-9bb9-8e8f6a665d41.png)

## Environment

- atoti: 0.7.1
- Python: 3.9.13
- Operating system: win32

**Comment by tibdex** [comment]
Thanks for reporting the issue Hui Fang, it will be fixed in the next release ;)
