### ISSUE TITLE
Error in atoti.UserContentStorageConfig

### ISSUE THREAD

**Issue by kiimot** [atoti/atoti#723]
Hi! I've been looking at this issue: https://github.com/atoti/atoti/issues/716
I don't know if it's the same problem, but it happens to me in both Oracle and MySQL. I have tried setting the database URL with JDBC and not setting it.

If it's the same problem...In the other issue you commented that this problem will be solved in the next release, correct?

¿This problem affects all types of databases?

Important: The connection to the database works, doing a read_sql()

## Steps to reproduce
![image](https://user-images.githubusercontent.com/95497490/202176722-e9fb8ae5-9382-46cd-95a7-b71564ee5261.png)

## Actual Result
Attached error logs: [server.log](https://github.com/atoti/atoti/files/10021287/server.log)
We inform the values ​​corresponding to the parameters of the url, but due to security policy we cannot give them:
![image](https://user-images.githubusercontent.com/95497490/202177891-8fba18cb-23b0-4089-8abf-e1b814bab8d6.png)

## Expected Result

Session is created and connects to the remote DB via JDBC

## Environment

- atoti: 0.7.1
- Python: 3.9.12
- Operating System: Windows 10 Enterprise x64

**Comment by tibdex** [comment]
Hi, 

Can you share some code to reproduce the issue?

Otherwise, it indeed looks similar to #716 which is going to be fixed in the next release (around end of November) so you could wait for that and try again.

**Comment by kiimot** [comment]
Hi!

The code is this:

> import atoti_sql as atoti_sql
> import atoti as tt
> 
> session = tt.Session(
>     user_content_storage = tt.UserContentStorageConfig(
>         url="jdbc:oracle:thin:[<user>/<password>]@<host>[:<port>]:<SID>",
>         driver=atoti_sql.drivers.ORACLE
>     )
> )

We inform the values ​​corresponding to the parameters of the url, but due to security policy we cannot give them

**Comment by kiimot** [comment]
Hi!

This issue is already resolved. It was solved with the new release 0.7.2...

Thanks!
