### ISSUE TITLE
Disaggregate function

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#73]
## Description
Marginal VaR is achieved using a formula post processor which makes use of the disaggregation operator. Firstly a temporary VaR vector is constructed by disaggregating the contribution for the selected book from the parent value, a VaR value at the required confidence level is extracted from that temporary vector and subtracted from the VaR value at the parent.

How to translate the existing DISAGGREGATION from the AP postprocessor to atoti:
```
<postProcessor pluginKey="FORMULA">
    <properties>
       <entry key="id" value="MarginVaR" />
       <entry key="formula"
            value="parentAggregatedValue[historical.VaR,Book],(string[SUM],parentAggregatedValue[historical.VECTOR,Book],aggregatedValue[historical.VECTOR],DISAGGREGATION),confidenceLevel[],VaR,-" />
     </properties>
 </postProcessor>
```
Currently we have in https://github.com/atoti/notebooks/blob/master/finance/value-at-risk/main.ipynb

```
m["Parent Position Vector Ex"] = atoti.agg.sum(
    m["Position Vector"],
    scope=atoti.scope.siblings(h["Trading Book Hierarchy"], exclude_self=True),
)

m["Parent VaR Ex"] = atoti.array.quantile(
    m["Parent Position Vector Ex"], m["Confidence Level"]
)
m["Parent VaR"] = atoti.parent_value(m["VaR"], h["Trading Book Hierarchy"])
m["Marginal VaR"] = m["Parent VaR"] - m["Parent VaR Ex"]
```

Is this the best way to achieve it?

**Comment by rcolle** [comment]
That's a good way of doing it.
A more "classic" way to compute the first part would be the following, but they should be pretty equivalent:

```python
parent_pnl_vector = atoti.parent_value(m["Position Vector"], h["Trading Book Hierarchy"])

```

**Comment by APolyakova** [comment]
related issue: https://github.com/atoti/atoti/issues/16

**Comment by rcolle** [comment]
Hi @HuifangYeo ,
I believe this question has been resolved so I'm closing the issue.
Feel free to reopen it if needed.
