### ISSUE TITLE
AtotiJavaException: Failed to discover format of file s3://... : Connection reset

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#730]
## Steps to reproduce

When we use `atoti.read_*` to read files stored on s3 buckets, sometimes it hangs while running on local machine.
Many times the automated testing on GitHub failed with error similar to the following:

Refer to : https://github.com/atoti/notebooks/actions/runs/3755735273/jobs/6381072157

```
AtotiJavaException: Failed to discover format of file s3://data.atoti.io/notebooks/customer360/Sub_Policy.csv : Connection reset
```

However, when I access the file directly using "https" instead of "s3", it is downloaded instantaneously. Is there a performance issue here? E.g. 

https://data.atoti.io/notebooks/intraday-liquidity/cashflow_202110.parquet
vs 
s3://data.atoti.io/notebooks/intraday-liquidity/cashflow_202110.parquet

## Environment

- atoti: 0.7.2
- Python: 3.9.13
- Operating system: win32

**Comment by tibdex** [comment]
Tracked in this [internal ticket](https://support.activeviam.com/jira/browse/PIVOT-6407) but since the error doesn't occur consistently it's hard to reproduce.

Do you know a notebook/file where the error always happens?

Thanks,

**Comment by HuifangYeo** [comment]
Sorry @tibdex, it's difficult to tell. There are no fixed notebooks where it always occurs. It happens at random timing, not sure if it's network traffic dependent. Since it's tracked internally, should I close this ticket?

**Comment by tibdex** [comment]
We can keep the issue open to make it easier to find for community users who might stumble it too.

**Comment by tibdex** [comment]
I'm postponing this since it's too hard to reproduce. If it happens again, please reopen.
