### ISSUE TITLE
ModuleNotFoundError: No module named 'atoti.cube'

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#731]
## Steps to reproduce

I just re-installed atoti on my env and I get the below error upon import of the atoti library:

<details><pre>
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 5
      1 import os
      3 # from atoti_plus import ADVANCED_APP_EXTENSION
----> 5 import atoti as tt

File ~\AppData\Roaming\Python\Python39\site-packages\atoti\__init__.py:26
     10 typecheck(BaseSession)
     12 from atoti_query import (
     13     Auth as Auth,
     14     BasicAuthentication as BasicAuthentication,
   (...)
     23     TokenAuthentication as TokenAuthentication,
     24 )
---> 26 from . import (  # pylint: disable=redefined-builtin
     27     agg as agg,
     28     array as array,
     29     experimental as experimental,
     30     math as math,
     31     scope as scope,
     32     string as string,
     33     type as type,
     34 )
     35 from ._eula import (
     36     EULA as __license__,
     37     hide_new_eula_message as hide_new_eula_message,
     38     hide_new_license_agreement_message as hide_new_license_agreement_message,
     39     print_eula_message,
     40 )
     41 from ._measure_metadata import *

File ~\AppData\Roaming\Python\Python39\site-packages\atoti\experimental\__init__.py:6
      1 """
      2 Warning:
      3     Experimental features are subject to breaking changes (even removals) in minor and/or patch releases.
      4 """
----> 6 from . import (
      7     _distributed as _distributed,
      8     agg as agg,
      9     finance as finance,
     10     stats as stats,
     11 )

File ~\AppData\Roaming\Python\Python39\site-packages\atoti\experimental\_distributed\__init__.py:9
      1 """
      2 atoti supports distributed clusters with several data cubes and one query cube.
      3 
      4 This is not the same as a query session: in a query session, the query cube connects to a remote data cube and query its content, while in a distributed setup, multiple data cubes can join a distributed cluster where a distributed cube can be queried to retrieve the union of their data.
      5 """
      7 from __future__ import annotations
----> 9 from ...cube import Cube
     10 from .cube import *
     11 from .session import *

ModuleNotFoundError: No module named 'atoti.cube'
</pre></details>

## Environment
```
atoti                     0.7.2
atoti-aws                 0.7.2
atoti-azure               0.7.2
atoti-core                0.7.2
atoti-gcp                 0.7.2
atoti-jupyterlab          0.7.2
atoti-kafka               0.7.2
atoti-plus                0.7.2
atoti-query               0.7.2
atoti-sql                 0.7.2
```

**Comment by tibdex** [comment]
Hi Hui Fang, I don't think there is anything wrong with 0.7.2 since we have some telemetry events coming from it and have received no complaints apart from this one.

- How did you install it Conda/pip/Poetry, which version of this tool?
- Can you try a new fresh install, clearing the cache of your package manager first?

**Comment by HuifangYeo** [comment]
Hi @tibdex,

I had 0.7.2 running in conda perfectly. Then I tried to install the DirectQuery plugin without credential.
It installed an older version of DirectQuery, which results in my atoti getting rolled back.

So I uninstalled and re-installed atoti and directQuery with credential after, encountering this exception.

I just deleted my conda env and re-created a new env. It's working now.
