### ISSUE TITLE
Date Hierarchy - Year wrongly parsed

### ISSUE THREAD

**Issue by EricDallAgnol** [atoti/atoti#735]
Hi team 👋 ,

Here is an issue I noticed using the [create_date_hierarchy](https://docs.atoti.io/latest/lib/atoti/atoti.cube.html#atoti.Cube.create_date_hierarchy)

Please let me know if you need more details,
Thanks,

## Steps to reproduce

- Create a base table with one key field as LOCAL_DATE
- Create a multilevel hierarchy from this field, using the [create_date_hierarchy](https://docs.atoti.io/latest/lib/atoti/atoti.cube.html#atoti.Cube.create_date_hierarchy)
- Load a small df with dates at the end/beginning of years
- For some, the "Year" is wrong

## Demo Notebook

`````python
import atoti as tt
import pandas as pd

def _create_base_table(session: tt.session.Session) -> tt.Table:
    return session.create_table("BaseStore",
    keys=["Date"],
    types={"Date" : tt.type.LOCAL_DATE})

session = tt.Session(port=9100)
_create_base_table(session)
session.create_cube(session.tables["BaseStore"], name="hello", mode="manual")

cube = session.cubes["hello"]
m, h  = cube.measures, cube.hierarchies

base_table = session.tables["BaseStore"]
h.update(
        {
        "Date": {
                "Date": base_table["Date"],
            }
        })


# Create date hierarchy
cube.create_date_hierarchy(
    "DateHierarchyYearMonthDay",
    column=base_table["Date"],
   levels={"Year": "YYYY", "Month": "MM", "Day": "dd"})

# Add the exact Date value as last level
cube.hierarchies["DateHierarchyYearMonthDay"] = {
    **h["DateHierarchyYearMonthDay"].levels, 
    "DateHierarchyYearMonthDay": base_table["Date"]
}

#Load dates
df = pd.DataFrame({
  "Date" : ["2022-12-30", "2022-12-31", "2023-01-01", "2023-01-02", "2023-12-30", "2023-12-31", "2024-01-01", "2024-12-30", "2024-12-31", "2025-01-01", "2025-01-02"],
})
df["Date"] = pd.to_datetime(df["Date"])
session.tables["BaseStore"].load_pandas(df)
`````

## Actual Result
![image](https://user-images.githubusercontent.com/83015366/214548903-17f3def9-840d-4c19-b3be-6623bc6e760f.png)

As you can notice, some dates are not correctly bucketed.
For instance, **"2023-01-01" is seeing as Year "2022"**, _but on the other hand, for "2025-01-01" it is seeing as Year "2025", which is right_
Also, **"2024-12-31" is seeing as Year "2025"**

## Expected Result

Have 2023-01-01 in the Year 2023 and 2024-12-31 in the Year 2024

## Environment

- atoti: 0.7.2
- Python: 3.8.3
- Operating system: win32

**Comment by fabiencelier** [comment]
Hello Eric,

From https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/time/format/DateTimeFormatter.html#patterns:
`YYYY` represent the "week based year" which forces the year to have exactly 52 or 53 weeks so days near the begining of 2023 might end up in 2022. See https://en.wikipedia.org/wiki/ISO_week_date for more details

If you want the true year you should use `yyyy`

**Comment by EricDallAgnol** [comment]
Hi Fabien,

Ok I understand now, it works indeed with `yyyy` !
Many thanks for your answer and the reactivity !!
