### ISSUE TITLE
 Totals are not calculated

### ISSUE THREAD

**Issue by kiimot** [atoti/atoti#741]
Good morning! I don't know if I'm doing something wrong or I'm leaving some parameter.

I am measuring a date difference with the date_diff in atoti.

Then, I  try to add the aggregated sum to that measure to get the totals to show up but they still don't show up

## Steps to reproduce
I've tried adding the corresponding scopes but it doesn't show the totals either, I don't know if it's because the calculation was done from a date
![image](https://user-images.githubusercontent.com/95497490/216957988-61db9394-d3aa-4b3f-816f-be25b51f67f8.png)

## Actual Result
![image](https://user-images.githubusercontent.com/95497490/216958237-a7aad4ec-5621-437c-a56e-7697b6543184.png)

## Expected Result

The DURATION column has been calculated from Python, not from Atoti, so when creating the cube it automatically creates the measure
![image](https://user-images.githubusercontent.com/95497490/216958421-d99d53dd-0e38-4f00-9752-b2bc734020b0.png)

## Environment

- atoti: 0.7.2
- Python: 3.10.9
- Operating System: Windows 10 Enterprise

**Comment by tibdex** [comment]
Hi,

You can keep your definition of `DURACTION_ATOTI` and then define this measure:

```python
m["DURACION_ATOTI_AGG"] = tt.agg.sum(
  m["DURACION_ATOTI"],
  scope=tt.OriginScope(l["DATE_INI"], l["DATE_FIN"])
)
```

`DURACION_ATOTI_AGG` should show totals (have values when `DATE_INI` and `DATE_FIN` are not expressed).
