### ISSUE TITLE
Can't change from seconds to datetime

### ISSUE THREAD

**Issue by kiimot** [atoti/atoti#749]
Good morning, I have been trying to create a measure by modifying an integer type field at time.

I have tried from functions created from scratch and methods that have datetime but none work.

## Steps to reproduce
I have a field called DURATION, type INT and the corresponding measures, DURATION.SUM and DURATION.MEAN
![image](https://user-images.githubusercontent.com/95497490/218683223-4d0cb830-bc76-41e6-a1e6-573044fd6c2c.png)

## Actual Result
![image](https://user-images.githubusercontent.com/95497490/218683223-4d0cb830-bc76-41e6-a1e6-573044fd6c2c.png)
I want to pass the seconds, to time format, using the timedelta(seconds=m['DURACION.SUM']) or timedelta(seconds=logs['DURACION']) method, but it gives me an error
![image](https://user-images.githubusercontent.com/95497490/218683601-e98871f1-3d19-4161-b78e-444ca4285339.png)

## Expected Result
The objective is to pass X seconds to HH:MM:SS format, but it does not allow me to pass the column or the measure to the method... Is it my mistake or is there another way to do it?
## Environment

- atoti: 0.7.2
- Python: 3.10.9
- Operating System: Windows 10 Enterprise

**Comment by rcolle** [comment]
Hi!
You need to choose the type of a field when creating a table (i.e. through `read_xxx` or `create_table`).
You can find the available types there: https://docs.atoti.io/latest/lib/atoti/atoti.type.html#module-atoti.type

**Comment by kiimot** [comment]
Hi!

The DURATION column is already an INTEGER, since it is the only type of value that the function accepts.
m['TEST'] = timedelta(seconds=m['DURATION.SUM'])

That is, the column I need in int type is already there, the problem is that it doesn't let me read the column or the autogenerated measure as an int value

Thanks!!

**Comment by fabiencelier** [comment]
Hi kiimot,

You cannot apply a `timedelta()` function to an atoti measure, you can only transform measures with atoti functions.
Sadly there is no out-of-the-box formatter for integer to time, nor way to transform integer to time.

What you can do is implement the logic yourself with `tt.string.concat`:

```python
m["DURATION.hours"] = tt.math.floor(m["DURATION"] / 3600)
m["DURATION.minutes"] = tt.math.floor( (m["DURATION"] - m["DURATION.hours"] * 3600) / 60)
m["DURATION.secondes"] = m["DURATION"] - (m["DURATION.hours"] * 3600) - (m["DURATION.minutes"] * 60)
m["DURATION.formatted"] = tt.string.concat(m["DURATION.hours"], m["DURATION.minutes"], m["DURATION.secondes"], separator=":")
```

This results in something like that:

![Screenshot from 2023-02-14 17-25-53](https://user-images.githubusercontent.com/17087544/218797435-3c0c9a94-323f-4901-9578-0e77e4cb7497.png)

**Comment by kiimot** [comment]
Hi!

Perfect, with this solution at least visually I can see it well. 

Thank you so much for your time!!
