### ISSUE TITLE
Add a argument to hide or display the priority in simulations and scenario .head

### ISSUE THREAD

**Issue by fabiencelier** [atoti/atoti#75]
The priority is quite advanced and hide a lot of noise to the simulations (which is already a complex subject).
It is good to have them but we should hide it by default to simplify.

.head of simulations and scenarios could take an argument like "show_priority" which is False by default

**Comment by fabiencelier** [comment]
Also we could hide the priority field from the UI by default and have a way to display it if necessary

**Comment by tibdex** [comment]
As discussed in https://github.com/atoti/atoti/issues/192#issuecomment-769207490, adding features to measure simulations isn't planned.
