### ISSUE TITLE
Getting Conda Can Not Find Packages when upgrading Atoti 

### ISSUE THREAD

**Issue by ncosgrov58** [atoti/atoti#779]
## Steps to reproduce
Trying to upgrade atoti,  using command  **conda update atoti**, this is an established environment where there has been no problem upgrading previously. Getting error back conda can not find atoti packages.  

## Actual Result
```
`(Atoti7New) C:\Users\ncosgrov>conda update atoti
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - C:/noarch::atoti-core==0.7.2=29abd44
  - C:/noarch::atoti-plus==0.7.2=29abd44
  - C:/noarch::atoti-jupyterlab==0.7.2=29abd44
  - C:/noarch::atoti-query==0.7.2=29abd44
  - C:/win-64::jdk4py==17.0.3.0=py310_0
  - C:/noarch::atoti==0.7.2=29abd44

Current channels:

  - https://conda.atoti.io/win-64
  - https://conda.atoti.io/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://xxxxxxxx:yyyyyyyyy@conda.atoti.io/win-64
  - https://xxxxxxxx:yyyyyyyyy@conda.atoti.io/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
`
Note that I updated a staging environment yesterday, same set of channels no issue.  

When I go to https://conda.atoti.io/win-64 I get a 404 error.

## Environment

- atoti:
- Python: 3.10.9
- Operating System: Window 64

**Comment by rcolle** [comment]
Works fine for me. However my channels setup is a bit different, I do not have any of the noarch/win64:
```
(myenv) C:\Users\user1>conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'
--add channels 'https://conda.atoti.io'   # highest priority
```

**Comment by ncosgrov58** [comment]
I don't know if we are set up different.  What I provided was the error dump.  If I execute the  get channels command I get:  

```
(atoti7new) C:\Users\ncosgrov>conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'https://xxxxxxxxx:yyyyyyyyy@conda.atoti.io'
--add channels 'conda-forge'
--add channels 'https://conda.atoti.io'   # highest priority
```

**Comment by ncosgrov58** [comment]
now getting error:  Downloading and Extracting Packages
atoti-plus-0.7.4     | 18.6 MB   |                                                                              |   0%

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.atoti.io/noarch/atoti-plus-0.7.4-cb607ee.tar.bz2>
Elapsed: 00:00.338230

An HTTP error occurred when trying to retrieve this URL.

**Comment by ncosgrov58** [comment]
OK the problem is resolved.  It seemed that an issue with Crowd that was causing atoti+ not to authenticate, but the error message was being blocked because the channel was not priority, we were just getting a "can not be found package".  Once the channel was made priority, the error showed and we could then pursue resolution.
