### ISSUE TITLE
Borrow pandas syntax

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#78]
## Description

This is just an idea to make the API look more familiar. atoti could reuse the same syntax that pandas uses, in the same spirit than https://koalas.readthedocs.io/en/latest/index.html was created for Spark. Or should it be a wrapper around atoti?

Example with [join/merge/append](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html) :
```python
# current
left_store.join(right_store, mapping={"key1": "key1"})
left_store.join(right_store, mapping={"key1": "key2"})

# new
merged_store = left_store.join(right_store, on=["key1"])
merged_store = atoti.merge(
    left_store, right_store, left_on=["key1"], right_on=["key2"]
)
```

Example with [groupby](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html):
```python
# current
m["Max price"] = tt.agg.max(sales_store["Unit price"])
cube.query(m["Max price"], levels=[lvl["Category"], lvl["Product"]])

# new
cube.groupby(["Category", "Product"]).agg({"Unit price": "max"})
```

Obviously this is a simplified view and trying to apply this to the whole API will raise a lot more challenges but you get the idea.

Related to https://github.com/atoti/atoti/issues/46

**Comment by rcolle** [comment]
>in the same spirit than https://koalas.readthedocs.io/en/latest/index.html was created for Spark.

First of all you have to remember that Spark and pandas are pretty much the same thing conceptually: dataframes on which you run queries and perform SQL like operations.
atoti is very different in the sense that measures are defined at as formulas on a conceptual cube, and their definition is used at runtime. It is therefore very difficult / impossible to apply the same concepts.

> Example with [join/merge/append](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html) :
> 
> ```python
> merged_store = atoti.merge(
>     left_store, right_store, left_on=["key1"], right_on=["key2"]
> )
> ```

I agree that join / merges are one area where we are all pretty similar.
However, pandas' merge API is a complete mess and realistically completely counter intuitive. Spark's API is much closer to a regular SQL join.
We therefore have to decide which public we want to cater to: people that only know about pandas and talk about "merge", or people that are familiar with SQL / Spark and use/understand the "classic" equijoin syntax that we currently offer.

> 
> Example with [groupby](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html):
> 
> ```python
> # current
> m["Max price"] = tt.agg.max(sales_store["Unit price"])
> cube.query(m["Max price"], levels=[lvl["Category"], lvl["Product"]])
> 
> # new
> cube.groupby(["Category", "Product"]).agg({"Unit price": "max"})
> ```

What would you expect this to do? 
Create the underlying behind the scene, run the query and return a dataframe?
Or define a new measure (that would need to be named)?

I don't believe that the first case has anything to do with building a BI application.

**Comment by tibdex** [comment]
Indeed we've seen several users surprised by the behavior of `Store.join()`.

When doing `left_store.join(right_store)` they expected it to either return a new store with the content of `right_store` inlined into `left_store` or for `left_store` to be mutated with a similar logic.

However, our `Store.join()` returns nothing and doesn't mutate the stores. Instead, it declares a join at the datastore/session level. On top of that, [depending on the cube creation mode, the join will also generate different hierarchies and measures](https://docs.atoti.io/0.4.1/lib/atoti.html#atoti.store.Store.join), so a join impacts more than just the store on which it's made.

Thus, maybe we should move this method to the `Session` like we did once for `create_cube()` wich used to be a method of `Store` too. It would look like that:

```diff
- sales_store.join(products_store, mapping={"Product": "Product"})
+ session.join(sales_store, products_store, mapping={"Product": "Product"})
```

The parameters could be called `left`/`right` or `source`/`destination`.

**Comment by rcolle** [comment]
Fair enough, but then why wouldn't they expect `session.join` to return a new store like `pandas.merge`?
I feel it simply moves the issue around.

**Comment by tibdex** [comment]
> Fair enough, but then why wouldn't they expect session.join to return a new store like `pandas.merge`?

It's subtle but:
- it's a different verb (`pandas.merge` Vs. `pandas.DataFrame.join`)
- an analogy can be made between our stores and pandas DataFrames but less between `pandas`'s root module and our `Session` instance.

So attaching the `join` method to the session actually moves our API away from pandas's one, which in this case might be a good thing to avoid confusing newcomers.

**Comment by jbe456** [comment]
I agree the initial idea expressed in this thread is a double edge sword (some would call it a bad idea): using a syntax people know of and are familiar with (pandas) on something which is fundamentally different and does not behave exactly the same (atoti).

My point was more to say that we could reuse the same verb and parameter names for similar concepts:
- `store.join` would have a parameter `on` instead of `mapping` and joining two stores would be done with `atoti.merge` or `session.merge` and provide parameters `left_on` and `right_on`.
- `levels` inside `cube.query` is almost equivalent to a `groupby`. We could almost rename `levels` into `groupby`: `cube.query(m["Max price"], groupby=[lvl["Category"], lvl["Product"]])` but that's more debatable since users need to deal with `measures` and `levels` concept anyway.

Those were my two main points. For the rest maybe it's better to keep it as a "comparison table" for #46 

Also, to nuance what I said, there is a `pivot_table` method in pandas: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html

```python
table = pd.pivot_table(df, values='D', index=['A', 'B'],
                    columns=['C'], aggfunc=np.sum)
```

So in fact the equivalence with `query` would rather be:
- `values` + `aggfunc` <=> `measures`
- `index` <=> `levels`
- `columns` <=> ?

**Comment by fabiencelier** [comment]
I am closing this issue.
I think we agree that we cannot and should not have a 100% similarities with pandas API.
If some specific parts of our API can be made clearer by using pandas syntax let's reopen individual tickets where we can discuss it in details.
