### ISSUE TITLE
Slow plotly charts

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#79]
Hello atoti,

I'm creating a plotly chart with 6000 points using cube.visualize() and it slows down jupyter lab very much. 

This is a recording from the notebook in this PR/branch: https://github.com/atoti/notebooks/pull/43

Browser: Firefox 77.0.1 (64-bit)

My machine
<img width="581" alt="image" src="https://user-images.githubusercontent.com/37184538/85084858-e2fc2500-b18a-11ea-9a01-9007e2c4a63d.png">

On this gif I'm showing how jupyter lab behaves. Similar slowliness happens in atoti app when I plot many points in a plotly chart. 
![slow jupyter lab](https://user-images.githubusercontent.com/37184538/85085094-96fdb000-b18b-11ea-9d92-486ce12cf09c.gif)

**Comment by tibdex** [comment]
Hi Anastasia, thanks for reporting this. I've opened an [internal ticket](https://support.activeviam.com/jira/browse/UI-4229) to see what can be done about it. In the meantime, you could look into adding some filters to your query to decrease the amount of points being plotted.
