### ISSUE TITLE
Ability to see axis titles in notebook charts from cube.visualize()

### ISSUE THREAD

**Issue by SamTaz** [atoti/atoti#8]
Hello, I am plotting a few charts in a notebook with atoti doing some `cube.visualize()` and I noticed that we do not have the x and y axis titles showing as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/39309622/78029176-737f5200-7360-11ea-810a-2297788dd038.png)

In the particular case of this example this is the margin per product category that is plotted. But since I have other indicators with the same unit as the margin (revenue for example), it is simply impossible to the user to know which measure has been plotted unless selecting the chart, then clicking on the atoti panel on the left and looking at what measure is plotted.

Would it be possible in the chart settings to be able to display axis titles ?

**Comment by HuifangYeo** [comment]
Normally if it's from Atoti UI, we can go to the state and add the below under the configuration of the chart:
```
                      "plotly":{
                            "layout":{
                                "xaxis": {
                                    "title": "Theoretical PnL"
                                },
                                "yaxis": {
                                    "title": "Tenor"
                                }
                            }
                        }
```
https://plotly.com/javascript/reference/#layout-xaxis-title-text

Not sure how it can be achieved in the notebook.

**Comment by SamTaz** [comment]
Didn't know we had access to the state here, that'll do for a workaround thanks !

But still great if we have some chart configuration for the axis title more easily available :)

**Comment by fabiencelier** [comment]
I have reported it to the ActiveUI team in an [internal ticket](https://support.activeviam.com/jira/browse/APS-12629)

**Comment by bloussou** [comment]
Hello,
A switch will be added in the style editor in the next release to display axis titles :tada:
