### ISSUE TITLE
Two paths are not reachable from one another and point to the same field

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#81]
## Steps to reproduce
Given the below stores:
![image](https://user-images.githubusercontent.com/35210495/85349480-1f37d880-b531-11ea-9553-e40ab4ef5728.png)

I get this exception during cube creation:
`These two paths are not reachable from one another and point to the same field: Trades_to_csaStore and Trades_to_collBalStore`

Proposed workaround is to use same name for the CSAId and CSAIdVM. This could be improved.

## Environment
- atoti: 0.4.1
- Python: 3.8.3
- Operating System: win32

**Comment by bloussou** [comment]
Hi @HuifangYeo,
Do you know if it is reproductible with the latest version ?
Best

**Comment by bloussou** [comment]
Closing this as there are no updates. Feel free to reopen it if you are still facing this issue
