### ISSUE TITLE
ability to query and see joined records

### ISSUE THREAD

**Issue by nidabouzid** [atoti/atoti#83]
## Description
We used to have this feature in the early stages of the product, it allows us to see joined records:
`store.head(n=10, joined_columns=True)`

Can this be integrated into the product or at least provide us the ability to query the stores with a where close so we can troubleshoot the joined data in case it does not show up.

**Comment by fabiencelier** [comment]
Related to https://github.com/atoti/atoti/issues/5

**Comment by tibdex** [comment]
Hi Nida, we don't plan to add back this option as it was only half-working. You can use:
- `session.stores.schema` to check that the joins are the ones you expect
- `cube.query()` to query a measure coming from a joined column on the levels you like
