### ISSUE TITLE
Lazy loaded pivot table keeps on loading

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#84]
## Steps to reproduce

- create a lazy loaded pivot table with many rows
- scroll down using the scrollbar

## Actual Result

![pivot-table-lazy-loading-flashing](https://user-images.githubusercontent.com/4415696/85734769-8dc99180-b6fd-11ea-83b8-771a3829bd9a.gif)

## Environment

- atoti: 0.4.2.20200625075349
- Operating System: linux
- Browser: Chromium Version 83.0.4103.116 (Official Build) Arch Linux (64-bit)

**Comment by rcolle** [comment]
The same problem happens in the app.
Assigning it to the UI team.

**Comment by rcolle** [comment]
Here is a sample code to reproduce the issue:

```python
import atoti as tt
session = tt.create_session()
store = session.read_csv("s3://nyc-tlc/trip data/fhv_tripdata_2015-01.csv")
cube = session.create_cube(store)
cube.visualize() # Add pickup_date on rows

# Same problem in the app
session.url
```
