### ISSUE TITLE
Integer field detected as long and ClassCastException

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#86]
## Steps to reproduce

```python
import pandas as pd

pandas_df = pd.DataFrame(
    data={
        "score": [1, 4, 2, 1, 5, 3, 5],
        "class": ["A", "B", "C", "D", "A", "E", "B"],
    }
)

import atoti
session = atoti.create_session()

store = session.read_pandas(pandas_df, store_name="my_store")
cube = session.create_cube(store)

m = cube.measures
lvl = cube.levels

m["5 star rate"] = atoti.filter(m["contributors.COUNT"], lvl["score"] == 5)/m["contributors.COUNT"]
```

## Actual Result

First thing is: `score` is detected as `long`. While it's not a problem per se, the type `integer` would be enough.

![image](https://user-images.githubusercontent.com/4415696/85847536-d76eb680-b7a7-11ea-9afc-6f33c8678c4c.png)

Secondly, when manipulating the field `score`, since it's a long, I get a ClassCastException when querying the `5 star rate` measure:

```
ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
```

How could I turn `5` into a `long` type when [Python 3 does not support anymore the type `long`](https://stackoverflow.com/questions/27632707/assign-and-print-long-variable-in-python)?

## Environment

- atoti: 0.4.2.20200625075349
- Python: 3.8.3
- Operating System: linux

**Comment by rcolle** [comment]
`score` should be a `long` since it's an `int64` in the pandas dataframe. That's the default setting for integer values in pandas.
You can cast it to an `int32` in the pandas dataframe and it should be correctly picked up by atoti.

I'll have a look at the `ClassCastException` though, that looks like a bug.

**Comment by bloussou** [comment]
I'm closing this since there is a workaround and know `read_pandas` is also supporting `types` parameter : https://docs.atoti.io/latest/lib/atoti.session.html#atoti.session.Session.read_pandas
