### ISSUE TITLE
contributors.COUNT returning empty cells instead of 0

### ISSUE THREAD

**Issue by cmariscalvo** [atoti/atoti#875]
Hi!

I am experiencing an issue as contributor.COUNT returns an empty cell instead of 0 when there is no match between rows and columns: 

![image](https://github.com/atoti/atoti/assets/101839447/945ffd75-5825-486d-8aa3-451c5420846d)

Is there a way that a value of 0 appears instead of empty cells?

I need to compute a calculated measure based on these values, and i can't do it properly as empty cells are not treated correctly.

My aim is to fill them with 0 values to compute some differences after. 

Thank you

**Comment by OPeyrusse** [comment]
You should be able to compute the difference even when the value is empty. Atoti follows the behavior of other standard BI tools, where `a - null = a` (same applying for multiple other operators).
Is this not working for you for some reasons? If so, can you share a notebook reproducing your issue, or at least snippets of code? Otherwise, it will be hard to help without further details.

**Comment by cmariscalvo** [comment]
Hi @OPeyrusse . 

a - null is working, the problem is when computing null -a.  As you see in this dashboard: 

![image](https://github.com/atoti/atoti/assets/101839447/0052367f-88ef-4bc3-94c9-4b1450eb4e25)

Diff measure is not being computed between 2024-03-26 and 2024-03-19. 

Diff measure is computed as the difference in contributors.COUNT between the actual date and the previous date available (i am sharing the mdx where i computed it). 

I have tried to fill in the NULL values using CoalesceEmpty (see MDX  too) but still is not filling them. 

As I am saying, it is working well when computing a-null, but not in the inverse way, null-a.

`WITH
 Member [Measures].[Diff] AS (
  (
    [TablaParametrica].[AsOfDate].CurrentMember,
    [Measures].[contributors.COUNT]
  ) - (
    [TablaParametrica].[AsOfDate].CurrentMember.lAG(
      1
    ),
    [Measures].[contributors.COUNT]
  )
)  
 Member [Measures].[NotZero] AS CoalesceEmpty(
  [Measures].[contributors.COUNT],
  0
) 
SELECT
  NON EMPTY Hierarchize(
    Descendants(
      {
        [TablaParametrica].[cnt origin].[AllMember]
      },
      1,
      SELF_AND_BEFORE
    )
  ) ON ROWS,
  NON EMPTY Crossjoin(
    Hierarchize(
      Descendants(
        {
          [TablaParametrica].[AsOfDate].[AllMember]
        },
        1,
        SELF_AND_BEFORE
      )
    ),
    {
      [Measures].[Diff],
      [Measures].[contributors.COUNT],
      [Measures].[NotZero]
    }
  ) ON COLUMNS
  FROM (
    SELECT
    Subset(
      Order(
        [TablaParametrica].[AsOfDate].[AS_OF_DATE].Members,
        [TablaParametrica].[AsOfDate].CurrentMember.MemberValue,
        BDESC
      ),
      0,
      10
    ) ON COLUMNS
    FROM [Parametric Table]
  )
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS`

**Comment by OPeyrusse** [comment]
Got it. Unfortunately, it is a standard behavior of Atoti - and MDX - to not compute values when there are no data.
The only workaround I can think of for now is to fill your table with fake rows not impacting your computation.

**Comment by cmariscalvo** [comment]
I am closing this issue as there is no possible solution to this problem. 

If there is no register for a specific contract across a date, it can not be treated directly in Atoti, though all possible dates appear on columns.
