### ISSUE TITLE
Control over chart legend order

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#88]
## Steps to reproduce

This could be reproduce with any level.

- `review_score` is a hierarchy/level whose default comparator displays members in the following order:

![image](https://user-images.githubusercontent.com/4415696/85858158-751fb100-b7bb-11ea-9597-0ae200976df1.png)

- Create a line chart
- Split by `review_score`

## Actual Result

We can see that the score displayed in the chart and legend are not sorted anymore:

![image](https://user-images.githubusercontent.com/4415696/85858614-38a08500-b7bc-11ea-91a6-9ab758fc57db.png)

## Expected Result

I would expect to either keep the default order or to be able to control it.

## Environment

- atoti: 0.4.2.20200625075349
- Operating System: linux
- Browser: Chromium Version 83.0.4103.116 (Official Build) Arch Linux (64-bit)

**Comment by jbe456** [comment]
## Workaround

The underlying implementation takes members as they come into the cellset.

For the above chart, here is the associated MDX & table:

```sql
SELECT
  NON EMPTY Crossjoin(
    [Hierarchies].[review_creation_week].[review_creation_week].Members,
    [Hierarchies].[review_score].[review_score].Members
  ) ON ROWS,
  NON EMPTY [Measures].[contributors.COUNT] ON COLUMNS
  FROM [Olist]
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
```

![image](https://user-images.githubusercontent.com/4415696/85915925-f7f04c80-b84b-11ea-9e1b-d6e2dcd5391b.png)

So the workaround is to manipulate the MDX so members would be received in a different order. In my case, swapping the two hierarchies and adding a sort gives me control over it: 

```sql
SELECT
  NON EMPTY Crossjoin(
    Order(
      [Hierarchies].[review_score].[review_score].Members,
      [Hierarchies].[review_score].CurrentMember.Name,
      ASC
    ),
    [Hierarchies].[review_creation_week].[review_creation_week].Members
  ) ON ROWS,
  NON EMPTY [Measures].[contributors.COUNT] ON COLUMNS
  FROM [Olist]
  CELL PROPERTIES VALUE, FORMATTED_VALUE, BACK_COLOR, FORE_COLOR, FONT_FLAGS
```

![image](https://user-images.githubusercontent.com/4415696/85915967-5e756a80-b84c-11ea-86bc-32d91b464415.png)

**Comment by tibdex** [comment]
Thanks for reporting the problem. It's related to https://community.plotly.com/t/customizing-the-order-of-legends/12668/2 and there doesn't seem to be a way to set a custom order through the Plotly configuration. So if we were to offer this ability, we would have to develop it in layer on top of Plotly.

**Comment by tibdex** [comment]
There hasn't been any progress on this. You can subscribe to the plotly thread to get updates.
