### ISSUE TITLE
agg.median ignores the scope origin

### ISSUE THREAD

**Issue by tibdex** [atoti/atoti#89]
## Steps to reproduce

Using the tutorial right after creating the cube:

```python
m["works"] = tt.agg.sum(m["Amount.MEAN"], scope=tt.scope.origin(lvl["Sale ID"]))
m["works"]._required_levels # ['Sale ID@Sale ID@Hierarchies']

m["does not work"] = tt.agg.median(m["Amount.MEAN"], scope=tt.scope.origin(lvl["Sale ID"]))
m["does not work"]._required_levels # []
```

## Environment

- atoti: 0.4.1
- Python: 3.8.3
- Operating System: linux

**Comment by tibdex** [comment]
These functions are also impacted: `var`, `std`, `quantile`. There may be others.

**Comment by rcolle** [comment]
I don't think this is an issue. It's normal that `median` does not have a required level since it's a full aggregation.
I'm actually surprised that `sum` does. It's probably a bug with th `_required_levels` attributes (likely ignores transmits = false)

**Comment by tibdex** [comment]
Yes I got surprised by the difference between the required levels but the aggregation works correctly, taking the scope into account.

**Comment by fabiencelier** [comment]
NamedMeasure._required_levels no longer return the levels if they are not transmitted.
