### ISSUE TITLE
Formatter for measure value not working

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#91]
## Steps to reproduce
I have a measure `m[CompetitorPrice.VALUE]`. The formatter is not taking effect.

![image](https://user-images.githubusercontent.com/35210495/86075418-8538d880-baba-11ea-90e2-b9e4100da6ad.png)

## Environment

- atoti: 0.4.1
- Python: 3.8.3
- Operating System: win32

**Comment by rcolle** [comment]
Hi,

`cube.query` returns a pandas `DataFrame`, which contains plain numbers.
You can look at how to to format pandas dataframe (e.g. [here](https://stackoverflow.com/questions/20937538/how-to-display-pandas-dataframe-of-floats-using-a-format-string-for-columns)).

Can you verify that the measure is correctly formatted in the ActiveUI extension / app?

**Comment by rcolle** [comment]
We could look into applying the formatters style to pandas:
https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

This is however a low priority task.

**Comment by HuifangYeo** [comment]
To begin with, the formatting was wrong in the ActiveUI extension. Thereafter I used to query to double confirm that it didn't take effect.

However, the behavior is inconsistent. I'm not sure if it's because it is due to some other change I made, the formatting is now working in the extension. (previously it didn't take effect even if I restart the kernel).

**Comment by tibdex** [comment]
Fixed since 0.4.3.
