### ISSUE TITLE
Normal distribution function

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#92]
## Description

A function that create a measure containing the normal distribution of another measure.

## Context

In order to perform some calculation on the SA-CCR demo, we are using the Normal Distribution function. We did it via the Taylor Expansion of the error function at the order 20. We couldn't go further because we faced an error with the size of the number. Nevertheless, we are doing the ISDA test and we need a more precise value of the Normal Distribution. Therefore it would be nice to have tt.norm(measure) that creates the Normal Distribution of the measure.

**Comment by rcolle** [comment]
I don't quite get what you want.
Can you provide an example of what you'd like, with the values of the measures on the relevant levels?
Thanks

**Comment by alexis-bvq** [comment]
In order to perform SA-CCR calculation we need to apply the normal Distribution function.
ISDA test are using this excel function with cumulative set to TRUE :
https://bettersolutions.com/excel/functions/norm-s-dist-function.htm#:~:text=Index%20%2D%20N-,NORM.,in%20a%20standard%20normal%20distribution.

In python, especially with pandas, it is easy to reproduce by applying this function (phi) to a column.

```
import pandas as pd
from math import erf, sqrt

df = pd.DataFrame({
    "l1" : ["A", "B", "C", "D", "E"],
    "m" : [0.000001, 0.5, 300000, -400000.0, -0.00000001]
})

def phi(x):
    a = x
    if (x < 0):
        a = -x
    #'Cumulative distribution function for the standard normal distribution'
    return (1.0 + erf(a / sqrt(2.0))) / 2

df["norm_distribution"] = df["m"].apply(phi)

print(df)
```

**Comment by fabiencelier** [comment]
So all you really need here is **erf** ?
If we add it then you would have all the building blocks to make phi

In the meantime it might be possible to implement the erf function using approximation such as this one: https://stackoverflow.com/a/457805/4678661

**Comment by alexis-bvq** [comment]
Yes erf would be enough.
I will try with the example you provided. We already tried with Taylor decomposition and it was okay as long as x < 3.

**Comment by alexis-bvq** [comment]
Thanks for finding this approximation it seems to work fine enough for ISDA test

**Comment by fabiencelier** [comment]
the `atoti.math.erf` and `atoti.math.erfc` will be included in the next release
