### ISSUE TITLE
Inconsistency about partitionning between documentation and atoti

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#95]
## Description
Hello, as I don't have more answer from the Atoti team on Slack, I create this issue. I have got information about the partitionning from my tests, from the Atoti documentation and from a member of the Atoti's team. From these 3 sources, I have got 3 different explanation that I can not combine.

Reading https://docs.atoti.io/0.4.1/lib/atoti.html?highlight=partition#atoti.session.Session.create_store, I understand that there is a default partitionning on all the stores.
However when I explicitely define a key partition on a referenced store, I have the following error:
```python
AtotiJavaException: Store BaseStore is not partitioned but references partitioned store Clients. Recommended action: Partition BaseStore.
                    Get the full logs with : session.logs_tail(-1)
                    Get the logs path with : session.logs_path
```
**Does it mean that explicitely adding some partitionning on a store will remove the default partitionning on all the other stores?**

We have used JMC in order to check the default partitionning (when no explicit partitionning was done) and it seems only to be applied on the base store when the documentation indicates something else.
**What is the correct answer?**

**Comment by rcolle** [comment]
Here are some additional information. We'll add them to the documentation:

1. Only base stores are automatically partitioned
2. Base stores are automatically partitioned by hashing their key fields. If there are no key fields, all the dictionarized fields are hashed.
3. Referenced stores can only use a sub-partitionning of the store referencing them.

As a side note, explicitly partitioning a store does not change anything to other stores.
