### ISSUE TITLE
Comparators on simulation level

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#96]
## Steps to reproduce
I created a simulation as follows:

```
simulation = price_index_cube.setup_simulation(
    "Distance Simulation", base_scenario="1 km", replace=[m["Distance Threshold"]]
)

lvl["Distance Simulation"].comparator = tt.comparator.ASC

simulation.scenarios["5 km"] = 5
simulation.scenarios["15 km"] = 15
simulation.scenarios["10 km"] = 10
simulation.scenarios["20 km"] = 20
```
The comparator doesn't affect the ordering of the scenarios:
![image](https://user-images.githubusercontent.com/35210495/86342804-af40f500-bc8a-11ea-8fc6-a84db7c97d93.png)

How can I achieve the ordering of 1km, 5km, 10km etc...?

## Environment

- atoti: 0.4.1
- Python: 3.8.3
- Operating System: win32

**Comment by HuifangYeo** [comment]
Currently I have to set it up as:
```
simulation = price_index_cube.setup_simulation(
    "Distance Simulation", base_scenario="01 km", replace=[m["Distance Threshold"]]
)

simulation.scenarios["05 km"] = 5
simulation.scenarios["15 km"] = 15
simulation.scenarios["10 km"] = 10
simulation.scenarios["20 km"] = 20
```

**Comment by Skyscimitar** [comment]
This is because the type of your simulation levels are strings, so alphabetically, "20 km" comes before "5 km"
you can use the `first_members` comparator to obtain the order you want:
```
lvl["Distance Simulation"].comparator = tt.comparator.first_members(
    ["1 km", "5 km", "10 km", "15 km", "20 km"]
)
```
