### ISSUE TITLE
Less than or equal

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#99]
## Steps to reproduce
I have applied Ranks on `ChurnProbabilities.SUM` and it's running from 1 to 1450.
![image](https://user-images.githubusercontent.com/35210495/86591640-85f2d280-bfc4-11ea-8432-805aefd5e136.png)

I tried to apply a filter on the `Churn Rank`:
![image](https://user-images.githubusercontent.com/35210495/86591713-a753be80-bfc4-11ea-982e-725831cdd13d.png)

While it should return me 1 - 600 since I used `Less than or equal to`, it returned me 1 to 559:
![image](https://user-images.githubusercontent.com/35210495/86591767-c9e5d780-bfc4-11ea-9c13-1596c4c29d62.png)

I'm using the atoti editor without manually manipulating the mdx.
Please refer to the last visualization in the attached.
[customer-churn-lessthanequal.zip](https://github.com/atoti/atoti/files/4878811/customer-churn-lessthanequal.zip)

## Environment

- atoti: 0.4.1
- Python: 3.8.3
- Operating System: win32

**Comment by bloussou** [comment]
Thanks for reporting, this will be fixed in next release.
Best
